// Code generated by cpybkc-gen-go. DO NOT EDIT.

package policy

import (
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
	"sync/atomic"
)

// literals is every byte string this package compares a field against: the
// literals of a transition's predicate, of an arm's predicate and of a guard
// over a bytes register.
//
// Each is the bytes a file under the descriptor's own axes holds there, which
// is what resolvedLiterals holds them as. A reader or a writer built under
// other axes — a converted copy of the same file, say — compares against
// them as a file under those axes spells them instead, re-expressed once,
// before its first record, by literalsFor. See docs/ir/SPEC.md, "A consumer
// may read under other axes, and re-expresses what it compares".
type literals struct {
	// lit1 is what FHD-RECORD-TYPE of PX-FILE-HEADER is compared against: the
	// literal "\xf0\xf0\xf0", "000" under cp037.
	lit1 []byte

	// lit2 is what PLC-RECORD-TYPE of PX-POLICY is compared against: the literal
	// "\xd7\xd3\xc3", "PLC" under cp037.
	lit2 []byte

	// lit3 is what FTR-RECORD-TYPE of PX-FILE-TRAILER is compared against: the
	// literal "\xf9\xf9\xf9", "999" under cp037.
	lit3 []byte

	// lit4 is what INS-RECORD-TYPE of PX-INSURED is compared against: the literal
	// "\xc9\xd5\xe2", "INS" under cp037.
	lit4 []byte

	// lit5 is what LOC-RECORD-TYPE of PX-LOCATION is compared against: the literal
	// "\xd3\xd6\xc3", "LOC" under cp037.
	lit5 []byte

	// lit6 is what VEH-RECORD-TYPE of PX-VEHICLE is compared against: the literal
	// "\xe5\xc5\xc8", "VEH" under cp037.
	lit6 []byte

	// lit7 is what DRV-RECORD-TYPE of PX-DRIVER is compared against: the literal
	// "\xc4\xd9\xe5", "DRV" under cp037.
	lit7 []byte

	// lit8 is what COV-RECORD-TYPE of PX-COVERAGE is compared against: the literal
	// "\xc3\xd6\xe5", "COV" under cp037.
	lit8 []byte

	// lit9 is what PRM-RECORD-TYPE of PX-PREMIUM is compared against: the literal
	// "\xd7\xd9\xd4", "PRM" under cp037.
	lit9 []byte

	// lit10 is what CLM-RECORD-TYPE of PX-CLAIM is compared against: the literal
	// "\xc3\xd3\xd4", "CLM" under cp037.
	lit10 []byte

	// lit11 is what ENR-RECORD-TYPE of PX-ENDORSEMENT is compared against: the
	// literal "\xc5\xd5\xd9", "ENR" under cp037.
	lit11 []byte
}

// resolvedLiterals is every literal as the descriptor resolved it. A reader or
// a writer under the descriptor's own axes compares against these and nothing
// else.
var resolvedLiterals = literals{
	lit1:  []byte("\xf0\xf0\xf0"),
	lit2:  []byte("\xd7\xd3\xc3"),
	lit3:  []byte("\xf9\xf9\xf9"),
	lit4:  []byte("\xc9\xd5\xe2"),
	lit5:  []byte("\xd3\xd6\xc3"),
	lit6:  []byte("\xe5\xc5\xc8"),
	lit7:  []byte("\xc4\xd9\xe5"),
	lit8:  []byte("\xc3\xd6\xe5"),
	lit9:  []byte("\xd7\xd9\xd4"),
	lit10: []byte("\xc3\xd3\xd4"),
	lit11: []byte("\xc5\xd5\xd9"),
}

// resolvedAxes is enc with the four axes a layout states — charset, sign
// convention, byte order and float format — put back to the ones this
// descriptor resolved, which is the encoding every literal in resolvedLiterals
// is spelled under.
func resolvedAxes(enc codec.Encoding) codec.Encoding {
	enc.Charset = codec.CP037()
	enc.Sign = codec.SignEBCDIC
	enc.ByteOrder = binary.BigEndian
	enc.Float = codec.FloatIEEE

	return enc
}

// heldLiterals is every re-expression this package has made, by the encoding
// it was made under. See reexpressedUnder.
var heldLiterals atomic.Pointer[[]reexpression[literals]]

// literalsFor is the literals as a file under enc spells them.
//
// Where enc is the descriptor's own on every axis an item compared here
// depends on — the charset — that is resolvedLiterals, and nothing is
// re-expressed: the comparisons a reader and a writer make are the ones the
// descriptor resolved. Otherwise it is literalsUnder's answer, worked out the
// first time this package meets enc and held after that — so the record
// methods, which are handed an encoding on every call, re-express once per
// encoding rather than once per record. Asking costs the comparisons that
// decide whether enc moves anything and, where it does, one lookup.
//
// A literal that has no spelling under enc is refused here, which is before
// any record is read or written under it.
func literalsFor(enc codec.Encoding) (*literals, error) {
	from := resolvedAxes(enc)

	if sameCharset(enc.Charset, from.Charset) {
		return &resolvedLiterals, nil
	}

	return reexpressedUnder(&heldLiterals, enc, literalsUnder)
}

// literalsUnder is every literal re-expressed under enc, each through the axes
// that reach the item it is compared against and no other: a literal whose
// item enc does not move is carried as it is, and never refused on its own
// account.
func literalsUnder(enc codec.Encoding) (*literals, error) {
	from := resolvedAxes(enc)
	l := resolvedLiterals

	var err error

	if l.lit1, err = reexpressText(l.lit1, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xf0\\xf0\\xf0\", \"000\" under cp037", "FHD-RECORD-TYPE", "PX-FILE-HEADER", err)
	}

	if l.lit2, err = reexpressText(l.lit2, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xd7\\xd3\\xc3\", \"PLC\" under cp037", "PLC-RECORD-TYPE", "PX-POLICY", err)
	}

	if l.lit3, err = reexpressText(l.lit3, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xf9\\xf9\\xf9\", \"999\" under cp037", "FTR-RECORD-TYPE", "PX-FILE-TRAILER", err)
	}

	if l.lit4, err = reexpressText(l.lit4, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xc9\\xd5\\xe2\", \"INS\" under cp037", "INS-RECORD-TYPE", "PX-INSURED", err)
	}

	if l.lit5, err = reexpressText(l.lit5, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xd3\\xd6\\xc3\", \"LOC\" under cp037", "LOC-RECORD-TYPE", "PX-LOCATION", err)
	}

	if l.lit6, err = reexpressText(l.lit6, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xe5\\xc5\\xc8\", \"VEH\" under cp037", "VEH-RECORD-TYPE", "PX-VEHICLE", err)
	}

	if l.lit7, err = reexpressText(l.lit7, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xc4\\xd9\\xe5\", \"DRV\" under cp037", "DRV-RECORD-TYPE", "PX-DRIVER", err)
	}

	if l.lit8, err = reexpressText(l.lit8, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xc3\\xd6\\xe5\", \"COV\" under cp037", "COV-RECORD-TYPE", "PX-COVERAGE", err)
	}

	if l.lit9, err = reexpressText(l.lit9, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xd7\\xd9\\xd4\", \"PRM\" under cp037", "PRM-RECORD-TYPE", "PX-PREMIUM", err)
	}

	if l.lit10, err = reexpressText(l.lit10, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xc3\\xd3\\xd4\", \"CLM\" under cp037", "CLM-RECORD-TYPE", "PX-CLAIM", err)
	}

	if l.lit11, err = reexpressText(l.lit11, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xc5\\xd5\\xd9\", \"ENR\" under cp037", "ENR-RECORD-TYPE", "PX-ENDORSEMENT", err)
	}

	return &l, nil
}

// reexpression is one re-expression a package has made: the encoding it was
// made under, and what came of it — the literals, or the refusal.
//
// A refusal is held as well as a success. It is a statement about the
// descriptor and the encoding and about nothing a record holds, so the answer
// the second time is the answer the first time, and working it out again per
// record is exactly the per-record re-expression docs/ir/SPEC.md forbids.
type reexpression[T any] struct {
	enc  codec.Encoding
	lits *T
	err  error
}

// reexpressionsKept is how many encodings a package remembers re-expressing
// under.
//
// A process reading one file under one encoding needs one. The number is not a
// performance claim about anything larger — a process juggling more encodings
// than this at once re-expresses again when one falls out, which is correct
// and merely slower — and it is small because every lookup walks it.
const reexpressionsKept = 4

// reexpressedUnder is the literals under enc, re-expressed by under the first
// time a package meets enc and read back from cache every time after.
//
// It exists for the record-level methods. UnmarshalCOBOL and MarshalCOBOL are
// codec's interfaces and take nothing but a codec.Reader or codec.Writer, so
// there is nowhere to hand them literals a caller re-expressed once; what they
// have is the encoding, on every call. A file-level reader and writer
// re-express once, when they are built, and reach this for that one time —
// which is also what puts their encoding here before the first record-level
// call asks.
//
// The cache is a copy-on-write list behind one atomic pointer rather than a map
// behind a lock: an encoding is not a comparable key in general (see
// [sameAxes]), a lookup is on every record of a converted file and a store is
// on the first, and two goroutines that miss together both re-express and both
// store, which costs a repetition and nothing else — the answer is a function
// of the encoding, so either store is the right one.
func reexpressedUnder[T any](cache *atomic.Pointer[[]reexpression[T]], enc codec.Encoding, under func(codec.Encoding) (*T, error)) (*T, error) {
	if known := cache.Load(); known != nil {
		for _, one := range *known {
			if sameAxes(one.enc, enc) {
				return one.lits, one.err
			}
		}
	}

	lits, err := under(enc)

	next := []reexpression[T]{{enc: enc, lits: lits, err: err}}
	if known := cache.Load(); known != nil {
		next = append(next, (*known)[:min(len(*known), reexpressionsKept-1)]...)
	}

	cache.Store(&next)

	return lits, err
}

// sameAxes reports whether two encodings agree on the four axes a layout states
// — charset, sign convention, byte order and float format — which are the four
// a literal is re-expressed through.
//
// The staircase is not compared. It is not an axis a literal moves along
// (docs/ir/SPEC.md, "The staircase is not an axis a consumer may replace"), and
// refusing one that is not the descriptor's is a check of its own, not this.
func sameAxes(a, b codec.Encoding) bool {
	return a.Sign == b.Sign && a.Float == b.Float && sameCharset(a.Charset, b.Charset) && sameByteOrder(a.ByteOrder, b.ByteOrder)
}

// sameCharset reports whether two charsets spell every byte alike.
//
// Compared as values where Go can compare them, which is every charset codec
// ships and almost every other, and by what they do where it cannot. A charset
// is an interface a caller may implement, and Go compares two interface values
// holding the same dynamic type by comparing the values — which panics where
// that type holds a slice, a map or a func, and a caller's charset built around
// a lookup table is exactly that type. Answering "different" for it would
// re-express the literals on every record the record methods read, since those
// ask again on every call; answering with a panic would take down a reader for
// handing it an encoding codec itself accepts. So such a pair is compared by its
// name, its space and the character each of the 256 bytes spells, which is
// everything a re-expression reads of a charset.
func sameCharset(a, b codec.Charset) bool {
	if same, ok := compared(a, b); ok {
		return same
	}

	if a.Name() != b.Name() || a.Space() != b.Space() {
		return false
	}

	for c := range 256 {
		if a.ToUnicode(byte(c)) != b.ToUnicode(byte(c)) {
			return false
		}
	}

	return true
}

// sameByteOrder reports whether two byte orders put the bytes of a value in the
// same order.
//
// By what they do rather than by value, for the reason [sameCharset] falls back
// to it and one more: binary.NativeEndian is a type of its own that agrees with
// one of the other two, and a literal cares only which.
//
// The two are asked to read the same two bytes rather than to write a value,
// because the record methods ask this on every call and a buffer handed to an
// interface method escapes: reading a package-level array allocates nothing.
func sameByteOrder(a, b binary.ByteOrder) bool {
	return a.Uint16(byteOrderProbe[:]) == b.Uint16(byteOrderProbe[:])
}

// byteOrderProbe is the two bytes [sameByteOrder] reads: 1 under a
// little-endian order and 256 under a big-endian one.
var byteOrderProbe = [2]byte{1, 0}

// compared is a == b where Go can compare the two, and ok false where it
// cannot rather than a panic.
func compared(a, b any) (same, ok bool) {
	defer func() {
		if recover() != nil {
			same, ok = false, false
		}
	}()

	return a == b, true
}

// literalError is why one literal has no spelling under the axes asked for:
// the axis it could not cross, and what about the literal stopped it.
//
// It is not the refusal a caller sees. It knows the literal's bytes and the
// axes and nothing about where the literal is compared, which is what
// [cannotReexpress] adds.
type literalError struct {
	// axis is the axis the literal could not cross, spelled with the value
	// asked for — "the charset ASCII", "the sign convention realia".
	axis string

	// reason is what about the literal stopped it, as a clause following the
	// axis: "which has no byte for '€'".
	reason string
}

// Error implements the error interface.
func (e literalError) Error() string {
	return "under " + e.axis + ", " + e.reason
}

// cannotReexpress is the refusal of a reader or a writer over one literal that
// has no spelling under the axes it was built with.
//
// It names the literal, the field it is compared against, the record holding
// that field and the axis, and says what docs/ir/SPEC.md requires it to: that
// no file under those axes holds that value in that field. It says as plainly
// that it is not about a file's data, because it is raised before any record is
// read and the adopter meeting it has made no mistake in their data or their
// layout — they have asked for axes under which the layout's own distinction
// cannot be written down, and this is where they learn that rather than where
// they start looking for a corrupt record.
func cannotReexpress(literal, field, record string, err error) error {
	return fmt.Errorf("%s is compared against %s, which a file cannot spell %v: no file under those axes holds that value in %s, "+
		"so no %s in one could be told apart by it. That is a property of the layout and the axes asked for, and not a fault in any file's data",
		field+" of "+record, literal, err, field, record)
}

// reexpressText is a literal compared against a text item — every byte of it
// a character under the charset from — as the same characters under the
// charset to.
//
// Byte by byte, which is how a file crosses a charset: a transfer rewrites
// each byte through the two code pages and keeps each character, including the
// padding the producer applied, which arrives as the new charset's own space.
// The width therefore does not change, and nothing about COBOL's comparison
// rules is applied here — they were applied when the literal was resolved
// (docs/ir/SPEC.md, "Each axis carries a literal the way a file crosses it").
//
// A charset that is the same value on both sides moves nothing and is answered
// without a translation, so a literal is never refused over an axis that did
// not change. Where the charset does change, the one failure is a character the
// charset to has no byte for, and that is a [literalError] for the refusal to
// name. A literal that comes out as the bytes it went in as — "01" between two
// EBCDIC code pages agreeing on every digit — is carried, not refused.
func reexpressText(lit []byte, from, to codec.Charset) ([]byte, error) {
	if sameCharset(from, to) {
		return lit, nil
	}

	out := make([]byte, len(lit))

	for i, b := range lit {
		r := from.ToUnicode(b)

		spelled, ok := to.FromUnicode(r)
		if !ok {
			return nil, literalError{
				axis:   "the charset " + to.Name(),
				reason: fmt.Sprintf("since it holds %q and %s has no byte for that character", r, to.Name()),
			}
		}

		out[i] = spelled
	}

	return out, nil
}
