// Code generated by cpybkc-gen-go. DO NOT EDIT.

package policy

// PxFileHeader is the PX-FILE-HEADER record, as docs/ir/SPEC.md resolved it.
type PxFileHeader struct {
	// FhdRecordType is FHD-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	FhdRecordType string

	// FhdExtractName is FHD-EXTRACT-NAME — alphanumeric, DISPLAY, 20 bytes.
	FhdExtractName string

	// FhdCycleDate is FHD-CYCLE-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	FhdCycleDate int32

	// FhdCycleTime is FHD-CYCLE-TIME — numeric, DISPLAY, 6 digits, unsigned, 6 bytes.
	FhdCycleTime int32

	// FhdCarrier is FHD-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	FhdCarrier string

	// FhdRegion is FHD-REGION — alphanumeric, DISPLAY, 2 bytes.
	FhdRegion string

	// FhdSourceSystem is FHD-SOURCE-SYSTEM — alphanumeric, DISPLAY, 8 bytes.
	FhdSourceSystem string

	// FhdRunNumber is FHD-RUN-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	FhdRunNumber int32

	// FhdFormatVersion is FHD-FORMAT-VERSION — numeric, DISPLAY, 3 digits, unsigned, 3 bytes.
	FhdFormatVersion int32

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxPolicy is the PX-POLICY record, as docs/ir/SPEC.md resolved it.
type PxPolicy struct {
	// PlcRecordType is PLC-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	PlcRecordType string

	// PlcPolicyNumber is PLC-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	PlcPolicyNumber string

	// PlcCarrier is PLC-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	PlcCarrier string

	// PlcTermEffDate is PLC-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	PlcTermEffDate int32

	// PlcSeq is PLC-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	PlcSeq int32

	// PlcProductCode is PLC-PRODUCT-CODE — alphanumeric, DISPLAY, 6 bytes.
	PlcProductCode string

	// PlcLob is PLC-LOB — alphanumeric, DISPLAY, 4 bytes.
	PlcLob string

	// PlcState is PLC-STATE — alphanumeric, DISPLAY, 2 bytes.
	PlcState string

	// PlcTermExpDate is PLC-TERM-EXP-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	PlcTermExpDate int32

	// PlcIssueDate is PLC-ISSUE-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	PlcIssueDate int32

	// PlcStatus is PLC-STATUS — alphanumeric, DISPLAY, 2 bytes.
	PlcStatus string

	// PlcCancelDate is PLC-CANCEL-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	PlcCancelDate int32

	// PlcCancelReason is PLC-CANCEL-REASON — alphanumeric, DISPLAY, 3 bytes.
	PlcCancelReason string

	// PlcAgencyCode is PLC-AGENCY-CODE — alphanumeric, DISPLAY, 8 bytes.
	PlcAgencyCode string

	// PlcProducerCode is PLC-PRODUCER-CODE — alphanumeric, DISPLAY, 8 bytes.
	PlcProducerCode string

	// PlcBillMethod is PLC-BILL-METHOD — alphanumeric, DISPLAY, 2 bytes.
	PlcBillMethod string

	// PlcPayPlan is PLC-PAY-PLAN — alphanumeric, DISPLAY, 3 bytes.
	PlcPayPlan string

	// PlcTermMonths is PLC-TERM-MONTHS — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	PlcTermMonths int32

	// PlcWrittenPremium is PLC-WRITTEN-PREMIUM — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	PlcWrittenPremium int64

	// PlcRenewalCount is PLC-RENEWAL-COUNT — numeric, DISPLAY, 3 digits, unsigned, 3 bytes.
	PlcRenewalCount int32

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxInsured is the PX-INSURED record, as docs/ir/SPEC.md resolved it.
type PxInsured struct {
	// InsRecordType is INS-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	InsRecordType string

	// InsPolicyNumber is INS-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	InsPolicyNumber string

	// InsCarrier is INS-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	InsCarrier string

	// InsTermEffDate is INS-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	InsTermEffDate int32

	// InsSeq is INS-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	InsSeq int32

	// InsRole is INS-ROLE — alphanumeric, DISPLAY, 2 bytes.
	InsRole string

	// InsLastName is INS-LAST-NAME — alphanumeric, DISPLAY, 30 bytes.
	InsLastName string

	// InsFirstName is INS-FIRST-NAME — alphanumeric, DISPLAY, 20 bytes.
	InsFirstName string

	// InsMiddleInitial is INS-MIDDLE-INITIAL — alphanumeric, DISPLAY, 1 byte.
	InsMiddleInitial string

	// InsAddressLine1 is INS-ADDRESS-LINE-1 — alphanumeric, DISPLAY, 35 bytes.
	InsAddressLine1 string

	// InsAddressLine2 is INS-ADDRESS-LINE-2 — alphanumeric, DISPLAY, 35 bytes.
	InsAddressLine2 string

	// InsCity is INS-CITY — alphanumeric, DISPLAY, 25 bytes.
	InsCity string

	// InsState is INS-STATE — alphanumeric, DISPLAY, 2 bytes.
	InsState string

	// InsPostalCode is INS-POSTAL-CODE — alphanumeric, DISPLAY, 9 bytes.
	InsPostalCode string

	// InsCountry is INS-COUNTRY — alphanumeric, DISPLAY, 3 bytes.
	InsCountry string

	// InsBirthDate is INS-BIRTH-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	InsBirthDate int32

	// InsGender is INS-GENDER — alphanumeric, DISPLAY, 1 byte.
	InsGender string

	// InsMaritalStatus is INS-MARITAL-STATUS — alphanumeric, DISPLAY, 1 byte.
	InsMaritalStatus string

	// InsTaxIdLast4 is INS-TAX-ID-LAST-4 — alphanumeric, DISPLAY, 4 bytes.
	InsTaxIdLast4 string

	// InsEmailOnFile is INS-EMAIL-ON-FILE — alphanumeric, DISPLAY, 1 byte.
	InsEmailOnFile string

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxLocation is the PX-LOCATION record, as docs/ir/SPEC.md resolved it.
type PxLocation struct {
	// LocRecordType is LOC-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	LocRecordType string

	// LocPolicyNumber is LOC-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	LocPolicyNumber string

	// LocCarrier is LOC-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	LocCarrier string

	// LocTermEffDate is LOC-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	LocTermEffDate int32

	// LocSeq is LOC-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	LocSeq int32

	// LocLocationNumber is LOC-LOCATION-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	LocLocationNumber int32

	// LocAddressLine1 is LOC-ADDRESS-LINE-1 — alphanumeric, DISPLAY, 35 bytes.
	LocAddressLine1 string

	// LocCity is LOC-CITY — alphanumeric, DISPLAY, 25 bytes.
	LocCity string

	// LocState is LOC-STATE — alphanumeric, DISPLAY, 2 bytes.
	LocState string

	// LocPostalCode is LOC-POSTAL-CODE — alphanumeric, DISPLAY, 9 bytes.
	LocPostalCode string

	// LocCountyCode is LOC-COUNTY-CODE — alphanumeric, DISPLAY, 5 bytes.
	LocCountyCode string

	// LocTerritory is LOC-TERRITORY — alphanumeric, DISPLAY, 4 bytes.
	LocTerritory string

	// LocProtectionClass is LOC-PROTECTION-CLASS — alphanumeric, DISPLAY, 2 bytes.
	LocProtectionClass string

	// LocConstructionCode is LOC-CONSTRUCTION-CODE — alphanumeric, DISPLAY, 2 bytes.
	LocConstructionCode string

	// LocOccupancyCode is LOC-OCCUPANCY-CODE — alphanumeric, DISPLAY, 3 bytes.
	LocOccupancyCode string

	// LocYearBuilt is LOC-YEAR-BUILT — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	LocYearBuilt int32

	// LocSquareFeet is LOC-SQUARE-FEET — numeric, DISPLAY, 6 digits, unsigned, 6 bytes.
	LocSquareFeet int32

	// LocNumberOfStories is LOC-NUMBER-OF-STORIES — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	LocNumberOfStories int32

	// LocDistanceToFire is LOC-DISTANCE-TO-FIRE — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	// The value is unscaled: the item's value is this field times 10^-1.
	LocDistanceToFire int32

	// LocFloodZone is LOC-FLOOD-ZONE — alphanumeric, DISPLAY, 4 bytes.
	LocFloodZone string

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxVehicle is the PX-VEHICLE record, as docs/ir/SPEC.md resolved it.
type PxVehicle struct {
	// VehRecordType is VEH-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	VehRecordType string

	// VehPolicyNumber is VEH-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	VehPolicyNumber string

	// VehCarrier is VEH-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	VehCarrier string

	// VehTermEffDate is VEH-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	VehTermEffDate int32

	// VehSeq is VEH-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	VehSeq int32

	// VehUnitNumber is VEH-UNIT-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	VehUnitNumber int32

	// VehVin is VEH-VIN — alphanumeric, DISPLAY, 17 bytes.
	VehVin string

	// VehModelYear is VEH-MODEL-YEAR — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	VehModelYear int32

	// VehMake is VEH-MAKE — alphanumeric, DISPLAY, 15 bytes.
	VehMake string

	// VehModel is VEH-MODEL — alphanumeric, DISPLAY, 20 bytes.
	VehModel string

	// VehBodyStyle is VEH-BODY-STYLE — alphanumeric, DISPLAY, 4 bytes.
	VehBodyStyle string

	// VehVehicleUse is VEH-VEHICLE-USE — alphanumeric, DISPLAY, 2 bytes.
	VehVehicleUse string

	// VehGarageState is VEH-GARAGE-STATE — alphanumeric, DISPLAY, 2 bytes.
	VehGarageState string

	// VehGaragePostal is VEH-GARAGE-POSTAL — alphanumeric, DISPLAY, 9 bytes.
	VehGaragePostal string

	// VehAnnualMileage is VEH-ANNUAL-MILEAGE — numeric, DISPLAY, 6 digits, unsigned, 6 bytes.
	VehAnnualMileage int32

	// VehSymbol is VEH-SYMBOL — alphanumeric, DISPLAY, 3 bytes.
	VehSymbol string

	// VehAntiTheft is VEH-ANTI-THEFT — alphanumeric, DISPLAY, 1 byte.
	VehAntiTheft string

	// VehCostNew is VEH-COST-NEW — numeric, DISPLAY, 7 digits, unsigned, 7 bytes.
	VehCostNew int32

	// VehLienholderName is VEH-LIENHOLDER-NAME — alphanumeric, DISPLAY, 30 bytes.
	VehLienholderName string

	// VehLeasedFlag is VEH-LEASED-FLAG — alphanumeric, DISPLAY, 1 byte.
	VehLeasedFlag string

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxDriver is the PX-DRIVER record, as docs/ir/SPEC.md resolved it.
type PxDriver struct {
	// DrvRecordType is DRV-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	DrvRecordType string

	// DrvPolicyNumber is DRV-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	DrvPolicyNumber string

	// DrvCarrier is DRV-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	DrvCarrier string

	// DrvTermEffDate is DRV-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	DrvTermEffDate int32

	// DrvSeq is DRV-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	DrvSeq int32

	// DrvDriverNumber is DRV-DRIVER-NUMBER — numeric, DISPLAY, 3 digits, unsigned, 3 bytes.
	DrvDriverNumber int32

	// DrvLastName is DRV-LAST-NAME — alphanumeric, DISPLAY, 30 bytes.
	DrvLastName string

	// DrvFirstName is DRV-FIRST-NAME — alphanumeric, DISPLAY, 20 bytes.
	DrvFirstName string

	// DrvBirthDate is DRV-BIRTH-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	DrvBirthDate int32

	// DrvGender is DRV-GENDER — alphanumeric, DISPLAY, 1 byte.
	DrvGender string

	// DrvMaritalStatus is DRV-MARITAL-STATUS — alphanumeric, DISPLAY, 1 byte.
	DrvMaritalStatus string

	// DrvLicenseState is DRV-LICENSE-STATE — alphanumeric, DISPLAY, 2 bytes.
	DrvLicenseState string

	// DrvLicenseNumber is DRV-LICENSE-NUMBER — alphanumeric, DISPLAY, 20 bytes.
	DrvLicenseNumber string

	// DrvLicenseDate is DRV-LICENSE-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	DrvLicenseDate int32

	// DrvRelationToIns is DRV-RELATION-TO-INS — alphanumeric, DISPLAY, 2 bytes.
	DrvRelationToIns string

	// DrvRatedUnit is DRV-RATED-UNIT — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	DrvRatedUnit int32

	// DrvGoodStudent is DRV-GOOD-STUDENT — alphanumeric, DISPLAY, 1 byte.
	DrvGoodStudent string

	// DrvTrainingFlag is DRV-TRAINING-FLAG — alphanumeric, DISPLAY, 1 byte.
	DrvTrainingFlag string

	// DrvPoints is DRV-POINTS — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	DrvPoints int32

	// DrvExcludedFlag is DRV-EXCLUDED-FLAG — alphanumeric, DISPLAY, 1 byte.
	DrvExcludedFlag string

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxCoverage is the PX-COVERAGE record, as docs/ir/SPEC.md resolved it.
type PxCoverage struct {
	// CovRecordType is COV-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	CovRecordType string

	// CovPolicyNumber is COV-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	CovPolicyNumber string

	// CovCarrier is COV-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	CovCarrier string

	// CovTermEffDate is COV-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	CovTermEffDate int32

	// CovSeq is COV-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	CovSeq int32

	// CovLocationNumber is COV-LOCATION-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	CovLocationNumber int32

	// CovUnitNumber is COV-UNIT-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	CovUnitNumber int32

	// CovCoverageCode is COV-COVERAGE-CODE — alphanumeric, DISPLAY, 6 bytes.
	CovCoverageCode string

	// CovCoverageDesc is COV-COVERAGE-DESC — alphanumeric, DISPLAY, 30 bytes.
	CovCoverageDesc string

	// CovLimit1 is COV-LIMIT-1 — numeric, PACKED-DECIMAL, 13 digits, signed, 7 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	CovLimit1 int64

	// CovLimit2 is COV-LIMIT-2 — numeric, PACKED-DECIMAL, 13 digits, signed, 7 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	CovLimit2 int64

	// CovDeductible is COV-DEDUCTIBLE — numeric, PACKED-DECIMAL, 9 digits, signed, 5 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	CovDeductible int32

	// CovDeductibleType is COV-DEDUCTIBLE-TYPE — alphanumeric, DISPLAY, 2 bytes.
	CovDeductibleType string

	// CovEffDate is COV-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	CovEffDate int32

	// CovExpDate is COV-EXP-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	CovExpDate int32

	// CovFormCode is COV-FORM-CODE — alphanumeric, DISPLAY, 8 bytes.
	CovFormCode string

	// CovClassCode is COV-CLASS-CODE — alphanumeric, DISPLAY, 6 bytes.
	CovClassCode string

	// CovRate is COV-RATE — numeric, PACKED-DECIMAL, 10 digits, signed, 6 bytes.
	// The value is unscaled: the item's value is this field times 10^-5.
	CovRate int64

	// CovExposureBasis is COV-EXPOSURE-BASIS — alphanumeric, DISPLAY, 2 bytes.
	CovExposureBasis string

	// CovWaiverFlag is COV-WAIVER-FLAG — alphanumeric, DISPLAY, 1 byte.
	CovWaiverFlag string

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxPremium is the PX-PREMIUM record, as docs/ir/SPEC.md resolved it.
type PxPremium struct {
	// PrmRecordType is PRM-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	PrmRecordType string

	// PrmPolicyNumber is PRM-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	PrmPolicyNumber string

	// PrmCarrier is PRM-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	PrmCarrier string

	// PrmTermEffDate is PRM-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	PrmTermEffDate int32

	// PrmSeq is PRM-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	PrmSeq int32

	// PrmCoverageCode is PRM-COVERAGE-CODE — alphanumeric, DISPLAY, 6 bytes.
	PrmCoverageCode string

	// PrmTransactionCode is PRM-TRANSACTION-CODE — alphanumeric, DISPLAY, 4 bytes.
	PrmTransactionCode string

	// PrmTransactionDate is PRM-TRANSACTION-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	PrmTransactionDate int32

	// PrmAccountingPeriod is PRM-ACCOUNTING-PERIOD — numeric, DISPLAY, 6 digits, unsigned, 6 bytes.
	PrmAccountingPeriod int32

	// PrmWrittenAmount is PRM-WRITTEN-AMOUNT — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	PrmWrittenAmount int64

	// PrmEarnedAmount is PRM-EARNED-AMOUNT — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	PrmEarnedAmount int64

	// PrmUnearnedAmount is PRM-UNEARNED-AMOUNT — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	PrmUnearnedAmount int64

	// PrmCommissionAmount is PRM-COMMISSION-AMOUNT — numeric, PACKED-DECIMAL, 9 digits, signed, 5 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	PrmCommissionAmount int32

	// PrmCommissionRate is PRM-COMMISSION-RATE — numeric, PACKED-DECIMAL, 7 digits, signed, 4 bytes.
	// The value is unscaled: the item's value is this field times 10^-4.
	PrmCommissionRate int32

	// PrmTaxAmount is PRM-TAX-AMOUNT — numeric, PACKED-DECIMAL, 9 digits, signed, 5 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	PrmTaxAmount int32

	// PrmFeeAmount is PRM-FEE-AMOUNT — numeric, PACKED-DECIMAL, 9 digits, signed, 5 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	PrmFeeAmount int32

	// PrmSurchargeAmount is PRM-SURCHARGE-AMOUNT — numeric, PACKED-DECIMAL, 9 digits, signed, 5 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	PrmSurchargeAmount int32

	// PrmCurrency is PRM-CURRENCY — alphanumeric, DISPLAY, 3 bytes.
	PrmCurrency string

	// PrmGlAccount is PRM-GL-ACCOUNT — alphanumeric, DISPLAY, 10 bytes.
	PrmGlAccount string

	// PrmStatutoryLine is PRM-STATUTORY-LINE — alphanumeric, DISPLAY, 4 bytes.
	PrmStatutoryLine string

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxClaim is the PX-CLAIM record, as docs/ir/SPEC.md resolved it.
type PxClaim struct {
	// ClmRecordType is CLM-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	ClmRecordType string

	// ClmPolicyNumber is CLM-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	ClmPolicyNumber string

	// ClmCarrier is CLM-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	ClmCarrier string

	// ClmTermEffDate is CLM-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	ClmTermEffDate int32

	// ClmSeq is CLM-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	ClmSeq int32

	// ClmClaimNumber is CLM-CLAIM-NUMBER — alphanumeric, DISPLAY, 14 bytes.
	ClmClaimNumber string

	// ClmLossDate is CLM-LOSS-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	ClmLossDate int32

	// ClmReportedDate is CLM-REPORTED-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	ClmReportedDate int32

	// ClmClosedDate is CLM-CLOSED-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	ClmClosedDate int32

	// ClmStatus is CLM-STATUS — alphanumeric, DISPLAY, 2 bytes.
	ClmStatus string

	// ClmCauseOfLoss is CLM-CAUSE-OF-LOSS — alphanumeric, DISPLAY, 4 bytes.
	ClmCauseOfLoss string

	// ClmCoverageCode is CLM-COVERAGE-CODE — alphanumeric, DISPLAY, 6 bytes.
	ClmCoverageCode string

	// ClmLocationNumber is CLM-LOCATION-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	ClmLocationNumber int32

	// ClmUnitNumber is CLM-UNIT-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	ClmUnitNumber int32

	// ClmAdjusterCode is CLM-ADJUSTER-CODE — alphanumeric, DISPLAY, 8 bytes.
	ClmAdjusterCode string

	// ClmPaidIndemnity is CLM-PAID-INDEMNITY — numeric, PACKED-DECIMAL, 13 digits, signed, 7 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	ClmPaidIndemnity int64

	// ClmPaidExpense is CLM-PAID-EXPENSE — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	ClmPaidExpense int64

	// ClmReserveIndemnity is CLM-RESERVE-INDEMNITY — numeric, PACKED-DECIMAL, 13 digits, signed, 7 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	ClmReserveIndemnity int64

	// ClmReserveExpense is CLM-RESERVE-EXPENSE — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	ClmReserveExpense int64

	// ClmSubrogationFlag is CLM-SUBROGATION-FLAG — alphanumeric, DISPLAY, 1 byte.
	ClmSubrogationFlag string

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxEndorsement is the PX-ENDORSEMENT record, as docs/ir/SPEC.md resolved it.
type PxEndorsement struct {
	// EnrRecordType is ENR-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	EnrRecordType string

	// EnrPolicyNumber is ENR-POLICY-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	EnrPolicyNumber string

	// EnrCarrier is ENR-CARRIER — alphanumeric, DISPLAY, 4 bytes.
	EnrCarrier string

	// EnrTermEffDate is ENR-TERM-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	EnrTermEffDate int32

	// EnrSeq is ENR-SEQ — numeric, DISPLAY, 5 digits, unsigned, 5 bytes.
	EnrSeq int32

	// EnrEndorsementNumber is ENR-ENDORSEMENT-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	EnrEndorsementNumber int32

	// EnrFormNumber is ENR-FORM-NUMBER — alphanumeric, DISPLAY, 12 bytes.
	EnrFormNumber string

	// EnrFormEdition is ENR-FORM-EDITION — alphanumeric, DISPLAY, 6 bytes.
	EnrFormEdition string

	// EnrFormTitle is ENR-FORM-TITLE — alphanumeric, DISPLAY, 40 bytes.
	EnrFormTitle string

	// EnrEffDate is ENR-EFF-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	EnrEffDate int32

	// EnrExpDate is ENR-EXP-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	EnrExpDate int32

	// EnrTransactionCode is ENR-TRANSACTION-CODE — alphanumeric, DISPLAY, 4 bytes.
	EnrTransactionCode string

	// EnrTransactionDate is ENR-TRANSACTION-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	EnrTransactionDate int32

	// EnrPremiumDelta is ENR-PREMIUM-DELTA — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	EnrPremiumDelta int64

	// EnrLocationNumber is ENR-LOCATION-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	EnrLocationNumber int32

	// EnrUnitNumber is ENR-UNIT-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	EnrUnitNumber int32

	// EnrCoverageCode is ENR-COVERAGE-CODE — alphanumeric, DISPLAY, 6 bytes.
	EnrCoverageCode string

	// EnrMandatoryFlag is ENR-MANDATORY-FLAG — alphanumeric, DISPLAY, 1 byte.
	EnrMandatoryFlag string

	// EnrPrintFlag is ENR-PRINT-FLAG — alphanumeric, DISPLAY, 1 byte.
	EnrPrintFlag string

	// EnrStateFiled is ENR-STATE-FILED — alphanumeric, DISPLAY, 2 bytes.
	EnrStateFiled string

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// PxFileTrailer is the PX-FILE-TRAILER record, as docs/ir/SPEC.md resolved it.
type PxFileTrailer struct {
	// FtrRecordType is FTR-RECORD-TYPE — alphanumeric, DISPLAY, 3 bytes.
	FtrRecordType string

	// FtrCycleDate is FTR-CYCLE-DATE — numeric, DISPLAY, 8 digits, unsigned, 8 bytes.
	FtrCycleDate int32

	// FtrPolicyCount is FTR-POLICY-COUNT — numeric, DISPLAY, 9 digits, unsigned, 9 bytes.
	FtrPolicyCount int32

	// FtrDetailCount is FTR-DETAIL-COUNT — numeric, DISPLAY, 9 digits, unsigned, 9 bytes.
	FtrDetailCount int32

	// FtrWrittenPremium is FTR-WRITTEN-PREMIUM — numeric, PACKED-DECIMAL, 15 digits, signed, 8 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	FtrWrittenPremium int64

	// FtrPaidLoss is FTR-PAID-LOSS — numeric, PACKED-DECIMAL, 15 digits, signed, 8 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	FtrPaidLoss int64

	// FtrHashPolicyNumber is FTR-HASH-POLICY-NUMBER — numeric, DISPLAY, 15 digits, unsigned, 15 bytes.
	FtrHashPolicyNumber int64

	// FtrRunNumber is FTR-RUN-NUMBER — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
	FtrRunNumber int32

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}
