// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Companion
func (r *Binding) AsCompanion() *Companion { // companion (../../../daggerverse/cpybkc/main.go:79:6)
	q := r.query.Select("asCompanion")

	return &Companion{
		query: q,
	}
}

// Cpybkc is one cpybkc image, plus the coordinates a later composition needs in
// order to find a published image that matches it.
//
// Every function on it is either a builder returning a new Cpybkc or a terminal
// that runs something, so a call chain reads as the image being assembled and
// then used; nothing here mutates.
type Companion struct { // companion (../../../daggerverse/cpybkc/main.go:79:6)
	query *querybuilder.Selection

	id *ID
}

func (r *Companion) WithGraphQLQuery(q *querybuilder.Selection) *Companion {
	return &Companion{
		query: q,
	}
}

// A unique identifier for this Companion.
func (r *Companion) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Companion) XXX_GraphQLType() string {
	return "Companion"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Companion) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Companion) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Companion) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Companion) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Companion{query: selectNode(dag.query, id, "Companion")}
	return nil
}

// Image is the image this module resolved, for a caller who wants to do
// something with it other than what this module offers — run a cpybkc
// subcommand by hand, look at what is in it, or push it somewhere of their own:
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  image with-exec --use-entrypoint --args=--version stdout
//
// Note the --use-entrypoint. The image's entrypoint is the CLI and the literal
// value of it is not part of the contract (docs/container/SPEC.md, "The CLI's
// own path is not part of the contract"), so an exec that named a path instead
// would be reaching for the one thing that document reserves the right to move.
//
// Publishing the image elsewhere is a reasonable thing to do — it is the same
// image the registry served — but a copy is not a release of cpybkc and carries
// none of the signatures or attestations one does (docs/container/SPEC.md, "What
// a tag carries besides the image"), because those are attached to the digest
// this project published and not to the bytes.
func (r *Companion) Image() *Container { // companion (../../../daggerverse/cpybkc/main.go:178:1)
	q := r.query.Select("image")

	return &Container{
		query: q,
	}
}

// AsNode returns this Companion as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Companion) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Create or update a binding of type Companion in the environment
func (r *Env) WithCompanionInput(name string, value *Companion, description string) *Env { // companion (../../../daggerverse/cpybkc/main.go:79:6)
	assertNotNil("value", value)
	q := r.query.Select("withCompanionInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Companion output to be assigned in the environment
func (r *Env) WithCompanionOutput(name string, description string) *Env { // companion (../../../daggerverse/cpybkc/main.go:79:6)
	q := r.query.Select("withCompanionOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// CompanionOpts contains options for Query.Companion
type CompanionOpts struct {
	//
	// The tag of the published cpybkc image to run.
	//
	// It defaults to the moving major tag "v0", which follows every release in
	// that major version: a caller who passes nothing keeps up with fixes and
	// stays inside the base-image contract's compatibility guarantees. Escalate
	// deliberately — "v0" follows releases, "v0.3.1" pins one release, and only a
	// digest pins the bytes. A digest is not a tag, so it goes to --image rather
	// than here.
	//
	//
	// Default: "v0"
	Version string // companion (../../../daggerverse/cpybkc/main.go:126:2)
	//
	// The registry repository the image is pulled from, as `<host>/<path>` with no
	// tag.
	//
	// It is an argument because where the image lives is not something the
	// base-image contract promises — a mirror, an internal registry or an
	// air-gapped copy serving the same digests satisfies every requirement in that
	// document identically, and a caller behind one should not have to give up
	// this module to use it. Companion images derive from it by the rule this
	// project publishes them under, so redirecting this redirects the family
	// rather than the base image alone.
	//
	//
	// Default: "ghcr.io/zaba505/cpybkc"
	Repository string // companion (../../../daggerverse/cpybkc/main.go:139:2)
	//
	// Run in this container instead of pulling one, replacing it entirely.
	//
	// It has to keep the promises the base-image contract makes — cpybkc as the
	// entrypoint, the plugin directory on PATH, a user that can execute what is in
	// it — because that is all this module drives it through. Nothing here checks
	// that, and nothing could: a container is not required to have come from a
	// registry at all.
	//
	// This is how cpybkc's own pipeline checks the module against the image it
	// just built rather than against the last release (#64), how a caller tries a
	// change to cpybkc before it ships, and how a build pins the image by digest —
	// a reference no tag argument can express, and the only one that pins bytes.
	//
	Image *Container // companion (../../../daggerverse/cpybkc/main.go:153:2)
}

// New selects the cpybkc release to run:
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  --version=v0.3.1 --repository=registry.internal/mirrors/cpybkc image
//
// The defaults pull the published base image, which carries the CLI and no
// generator at all — cpybkc's own generator reaches a user the way a stranger's
// does, as a separate image built `FROM` the base (docs/container/SPEC.md, "Why
// cpybkc's own generator is not in the base image"). So an image that generates
// anything is a composition the caller asked for rather than one the base image
// decided for them.
//
// The three arguments are two ways of naming an image and are not combined: pass
// image and neither of the others is used to pull anything.
func (r *Query) Companion(opts ...CompanionOpts) *Companion { // companion (../../../daggerverse/cpybkc/main.go:115:1)
	q := r.query.Select("companion")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `repository` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repository) {
			q = q.Arg("repository", opts[i].Repository)
		}
		// `image` optional argument
		if !querybuilder.IsZeroValue(opts[i].Image) {
			q = q.Arg("image", opts[i].Image)
		}
	}

	return &Companion{
		query: q,
	}
}
