// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Companion
func (r *Binding) AsCompanion() *Companion { // companion (../../../daggerverse/cpybkc/main.go:220:6)
	q := r.query.Select("asCompanion")

	return &Companion{
		query: q,
	}
}

// Cpybkc is one cpybkc image, plus the coordinates for resolving images related
// to it.
//
// A function on it is a builder returning a new Cpybkc, a terminal that runs
// something, or an accessor handing back what was resolved, so a call chain
// reads as the image being assembled and then used; nothing here mutates.
type Companion struct { // companion (../../../daggerverse/cpybkc/main.go:220:6)
	query *querybuilder.Selection

	id *ID
}
type WithCompanionFunc func(r *Companion) *Companion

// With calls the provided function with current Companion.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Companion) With(f WithCompanionFunc) *Companion {
	return f(r)
}

func (r *Companion) WithGraphQLQuery(q *querybuilder.Selection) *Companion {
	return &Companion{
		query: q,
	}
}

// CompanionGenerateOpts contains options for Companion.Generate
type CompanionGenerateOpts struct {
	//
	// The project manifest to read, relative to the root of source.
	//
	// It defaults to nothing, which leaves cpybkc reading `cpybkc.json` at the
	// root of the mounted project — the CLI's own default, applied by the CLI,
	// against the working directory this module puts the project at. There is no
	// upward search and no second manifest, so a project keeping its manifest
	// somewhere else says so here.
	//
	// A relative path resolves against that project root, because that is the
	// directory the CLI resolves a path typed on the command line against. It
	// cannot be "-": a manifest's own paths are relative to the directory holding
	// it, and a manifest arriving on a stream is in no directory.
	//
	Manifest string // companion (../../../daggerverse/cpybkc/main.go:568:2)
}

// Generate runs cpybkc over a project and hands back the project as it should
// now be committed:
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  generate --source . export --path .
//
// Nothing is written to the host. The Directory that comes back is a value like
// any other, and exporting it is the caller's separate, explicit step — which is
// also what disposes of the ownership problem a bind mount has, where generated
// files land owned by whichever UID the container ran as and a host user who is
// not that UID owns none of their own project. Dagger's export writes as the
// person running it, so the image's pinned user never reaches the host.
//
// What comes back is the **whole project directory**, not only the files a
// generator produced. A generator's output lands where the manifest says, which
// is ordinarily inside the source tree, and a run also prunes what a previous
// run generated and no longer would — so the generated files alone cannot
// express half of what a run did. `generate --source . export --path .` is
// therefore the ordinary use, and it is a full statement of the run rather than
// an overlay that leaves deletions behind.
func (r *Companion) Generate(source *Directory, opts ...CompanionGenerateOpts) *Directory { // companion (../../../daggerverse/cpybkc/main.go:545:1)
	assertNotNil("source", source)
	q := r.query.Select("generate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `manifest` optional argument
		if !querybuilder.IsZeroValue(opts[i].Manifest) {
			q = q.Arg("manifest", opts[i].Manifest)
		}
	}
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Companion.
func (r *Companion) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Companion) XXX_GraphQLType() string {
	return "Companion"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Companion) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Companion) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Companion) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Companion) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Companion{query: selectNode(dag.query, id, "Companion")}
	return nil
}

// Image is the image this module resolved and composed, for a caller who wants
// to do something with it other than what this module offers — run a cpybkc
// subcommand by hand, look at what is in it, publish a derived image holding
// their generators, or make it one variant of a multi-platform index:
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  image with-exec --use-entrypoint --args=--version stdout
//
// Note the --use-entrypoint. The image's entrypoint is the CLI and the literal
// value of it is not part of the contract (docs/container/SPEC.md, "The CLI's
// own path is not part of the contract"), so an exec that named a path instead
// would be reaching for the one thing that document reserves the right to move.
//
// Publishing the image elsewhere is a reasonable thing to do — it is the same
// image the registry served — but a copy is not a release of cpybkc and carries
// none of the signatures or attestations one does (docs/container/SPEC.md, "What
// a tag carries besides the image"), because those are attached to the digest
// this project published and not to the bytes.
func (r *Companion) Image() *Container { // companion (../../../daggerverse/cpybkc/main.go:521:1)
	q := r.query.Select("image")

	return &Container{
		query: q,
	}
}

// CompanionRunOpts contains options for Companion.Run
type CompanionRunOpts struct {
	//
	// The project to run over, mounted at /src and made the working directory.
	//
	// It is optional because half the reason this function exists is the
	// invocations that have no project — `--version` and `--help` read nothing and
	// contact nothing. With no source the container is the image as it was
	// resolved, and cpybkc runs in whatever directory the image left it in.
	//
	Source *Directory // companion (../../../daggerverse/cpybkc/main.go:632:2)
}

// Run is the escape hatch: cpybkc invoked with an argument vector this module
// has no opinion about, in a container handed back whole.
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  run --source . --args=--emit-ir,- stdout
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  run --args=--help stdout
//
// It exists so that Generate does not have to grow an argument every time
// docs/cli/SPEC.md's flag table does. A flag that replaces the action rather
// than configuring it (--emit-ir is terminal: no generator runs and nothing is
// merged or pruned), one that may only appear beside another (--emit-ir-format
// without --emit-ir is a usage error), and one that answers a question about the
// program rather than about a project (--version, --help) are all things a
// command line states plainly and a set of Dagger arguments states badly.
//
// A container rather than a directory, because the uncurated invocations are the
// ones whose answer is not a tree. --emit-ir may write to standard output, and
// --version and --help write nothing else at all; a Directory return would make
// the escape hatch unable to reach exactly the flags it exists for. A caller who
// does want the tree takes it from the container, where the project is still
// mounted at /src:
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  run --source . --args=--manifest,build/cpybkc.json \
//	  directory --path=/src export --path .
//
// Nothing here is validated. A vector this module checked would be a second,
// unversioned reading of a contract the CLI already implements, and its
// diagnostics are better than anything guessed at from out here: what an
// unrecognised flag is, whether a flag may repeat and what a usage error exits
// with are all docs/cli/SPEC.md's, and the exec's failure carries them back
// verbatim.
func (r *Companion) Run(args []string, opts ...CompanionRunOpts) *Container { // companion (../../../daggerverse/cpybkc/main.go:619:1)
	q := r.query.Select("run")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}
	q = q.Arg("args", args)

	return &Container{
		query: q,
	}
}

// CompanionWithGeneratorOpts contains options for Companion.WithGenerator
type CompanionWithGeneratorOpts struct {
	//
	// Take the executable from this image instead of pulling the published
	// generator image for name.
	//
	// Any image carrying the generator in the plugin directory will do, including
	// one that was never published. It has to be for the same platform as the
	// image being composed into, which is checked, because a mismatch here is
	// checkable and its exec-time failure is not legible.
	//
	Image *Container // companion (../../../daggerverse/cpybkc/main.go:406:2)
}

// WithGenerator adds one generator to the image by copying its executable out of
// a generator image:
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  with-generator --name hello --image ghcr.io/example/cpybkc-gen-hello:v1 \
//	  generate --source . export --path .
//
// This is the whole of adding a generator without writing a Dockerfile. The file
// is taken out of the image at the path the base-image contract promises, which
// is what `COPY --from` does, and it works just as well for a generator image
// this project has never heard of — that is what image is for. Repeated calls
// compose, so a project whose manifest names three generators is three calls and
// one image.
//
// With no image, the generator this project publishes for name is pulled:
// `<repository>-gen-<name>:<version>`, against the same coordinates the CLI image
// came from. A generator from one release beside a CLI from another is a pairing
// nobody tested, and defaulting to it is how somebody would end up in one without
// having said so.
//
// The generator is pulled for the platform the container being composed into was
// resolved for, not for the engine's. That is the whole of what this module does
// about multi-platform: composing an amd64 generator into an arm64 image produces
// an image that builds and pushes and then fails at exec with the kernel's
// message rather than cpybkc's, which is a long way from the call that caused it.
func (r *Companion) WithGenerator(name string, opts ...CompanionWithGeneratorOpts) *Companion { // companion (../../../daggerverse/cpybkc/main.go:393:1)
	q := r.query.Select("withGenerator")
	for i := len(opts) - 1; i >= 0; i-- {
		// `image` optional argument
		if !querybuilder.IsZeroValue(opts[i].Image) {
			q = q.Arg("image", opts[i].Image)
		}
	}
	q = q.Arg("name", name)

	return &Companion{
		query: q,
	}
}

// WithGeneratorExecutable adds one generator to the image from an executable
// file, for a generator that ships no image — most often one the caller has just
// built in the same pipeline:
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  with-generator-executable --name hello --executable ./cpybkc-gen-hello \
//	  generate --source . export --path .
//
// It is the generator author's path, before there is anything of theirs to pull.
// Checking a plugin against a real cpybkc run is the first thing they need and
// the last thing a published image can give them.
//
// The file lands as cpybkc-gen-<name> whatever it was called before, because
// discovery is by filename and nothing inside the executable is consulted.
//
// It has to be a statically linked native executable for the image's platform,
// and that is the caller's to meet rather than this module's to check: it is the
// same requirement docs/container/SPEC.md's worked example states as
// `CGO_ENABLED=0`, a File says nothing about what it is, and a dynamically linked
// or foreign-architecture generator fails at exec time with the kernel's message
// rather than cpybkc's. WithGenerator can check the platform half of that because
// a container states one; here there is nothing to read.
func (r *Companion) WithGeneratorExecutable(name string, executable *File) *Companion { // companion (../../../daggerverse/cpybkc/main.go:477:1)
	assertNotNil("executable", executable)
	q := r.query.Select("withGeneratorExecutable")
	q = q.Arg("name", name)
	q = q.Arg("executable", executable)

	return &Companion{
		query: q,
	}
}

// AsNode returns this Companion as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Companion) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Create or update a binding of type Companion in the environment
func (r *Env) WithCompanionInput(name string, value *Companion, description string) *Env { // companion (../../../daggerverse/cpybkc/main.go:220:6)
	assertNotNil("value", value)
	q := r.query.Select("withCompanionInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Companion output to be assigned in the environment
func (r *Env) WithCompanionOutput(name string, description string) *Env { // companion (../../../daggerverse/cpybkc/main.go:220:6)
	q := r.query.Select("withCompanionOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// CompanionOpts contains options for Query.Companion
type CompanionOpts struct {
	//
	// The tag of the published cpybkc image to run.
	//
	// It defaults to the moving major tag "v0", which follows every release in
	// that major version: a caller who passes nothing keeps up with fixes and
	// stays inside the base-image contract's compatibility guarantees. Escalate
	// deliberately — "v0" follows releases, "v0.3.1" pins one release, and only a
	// digest pins the bytes. A digest is not a tag, so it goes to --image rather
	// than here.
	//
	//
	// Default: "v0"
	Version string // companion (../../../daggerverse/cpybkc/main.go:284:2)
	//
	// The registry repository the image is pulled from, as `<host>/<path>` with no
	// tag.
	//
	// It is an argument because where the image lives is not something the
	// base-image contract promises — a mirror, an internal registry or an
	// air-gapped copy serving the same digests satisfies every requirement in that
	// document identically, and a caller behind one should not have to give up
	// this module to use it. Companion images derive from it by the rule this
	// project publishes them under, so redirecting this redirects the family
	// rather than the base image alone.
	//
	//
	// Default: "ghcr.io/zaba505/cpybkc"
	Repository string // companion (../../../daggerverse/cpybkc/main.go:297:2)
	//
	// Run in this container instead of pulling one, replacing it entirely.
	//
	// It has to keep the promises the base-image contract makes — cpybkc as the
	// entrypoint, the plugin directory on PATH, a user that can execute what is in
	// it — because that is all this module drives it through. Nothing here checks
	// that, and nothing could: a container is not required to have come from a
	// registry at all.
	//
	// This is how cpybkc's own pipeline checks the module against the image it
	// just built rather than against the last release (#64), how a caller tries a
	// change to cpybkc before it ships, and how a build pins the image by digest —
	// a reference no tag argument can express, and the only one that pins bytes.
	//
	Image *Container // companion (../../../daggerverse/cpybkc/main.go:311:2)
	//
	// Pull the image for this platform, as `GOOS/GOARCH`, instead of for the
	// engine's own.
	//
	// It is what makes a derived image for another architecture reachable at all:
	// a composition is one platform, and without this an amd64 engine could only
	// ever compose an amd64 image. Every generator composed in afterwards follows
	// it, so the platform is stated once, here, rather than on each call that
	// could contradict the last.
	//
	// A multi-platform derived image is therefore one composition per platform,
	// published as variants of one index — see this module's comment. That loop
	// belongs to the caller because the index does: which platforms a derived
	// image serves is a property of who will run it.
	//
	// Empty is the engine's own platform, which is what makes an ordinary
	// `dagger call` from a checkout do the obvious thing.
	//
	Platform string // companion (../../../daggerverse/cpybkc/main.go:329:2)
}

// New selects the cpybkc release to run:
//
//	dagger call -m github.com/Zaba505/cpybkc/daggerverse/cpybkc \
//	  --version=v0.3.1 --repository=registry.internal/mirrors/cpybkc image
//
// The defaults pull the published base image, which carries the CLI and no
// generator at all — cpybkc's own generator reaches a user the way a stranger's
// does, as a separate image built `FROM` the base (docs/container/SPEC.md, "Why
// cpybkc's own generator is not in the base image"). So an image that generates
// anything is a composition the caller asked for rather than one the base image
// decided for them.
//
// image replaces the container that would otherwise be pulled, so passing it
// means version and repository name nothing that gets fetched here. They are not
// thereby inert: they stay on the module as the coordinates WithGenerator
// resolves companion images against, which is why an air-gapped caller passing a
// container from their own registry should pass --repository beside it rather
// than instead of it.
func (r *Query) Companion(opts ...CompanionOpts) *Companion { // companion (../../../daggerverse/cpybkc/main.go:273:1)
	q := r.query.Select("companion")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `repository` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repository) {
			q = q.Arg("repository", opts[i].Repository)
		}
		// `image` optional argument
		if !querybuilder.IsZeroValue(opts[i].Image) {
			q = q.Arg("image", opts[i].Image)
		}
		// `platform` optional argument
		if !querybuilder.IsZeroValue(opts[i].Platform) {
			q = q.Arg("platform", opts[i].Platform)
		}
	}

	return &Companion{
		query: q,
	}
}
