// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The record tier of this package's generated tests: one case per record the
// layout describes, and one per arm of an alternation inside one.
//
// Each case carries the bytes it reads as a literal, decodes them, checks every
// field against the value the literal was laid out with, and writes the record
// back out byte for byte. The bytes are synthesized from the layout rather than
// read from a file, so they are what to hold against the file on your desk: the
// comment column names the item, the offset summed from the widths ahead of it,
// and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports sep.
package sep_test

import (
	"bytes"
	"github.com/Zaba505/cobol-go/codec"
	"github.com/Zaba505/cpybkc/cmd/cpybkc-gen-go/internal/sep"
	"testing"
)

// TestLineRecordReadsBackTheBytesItWasReadFrom is LINE-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestLineRecordReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // LINE-TEXT @0 X(5)
		0x00, 0x00, 0x6d, // LINE-AMOUNT @5 S9(3)V9(2) PACKED-DECIMAL
	}

	r, err := codec.NewReader(bytes.NewReader(in), sep.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record sep.LineRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.LineText != "AAAAA" {
		t.Errorf("LINE-TEXT: got %q, want %q", record.LineText, "AAAAA")
	}

	if record.LineAmount != -6 {
		t.Errorf("LINE-AMOUNT: got %d, want %d", record.LineAmount, -6)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, sep.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
