// Code generated by cpybkc-gen-go. DO NOT EDIT.

package orders

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
	"io"
	"strings"
)

// Record is one record of the file this package describes: what a [Reader]
// produces and what a [Writer] takes.
//
// It is codec's two interfaces together rather than a method this generator
// invented. Every record type here already implements both, and a marker method
// would be an identifier neither the copybook nor the layout wrote — which is
// the thing this generator refuses to produce everywhere else. A value that is
// not one of this package's record types satisfies it too, and the writer
// reports one rather than emitting it.
type Record interface {
	codec.Unmarshaler
	codec.Marshaler
}

// readAhead is the reader's buffer, which is bufio's own default: this file's
// framing puts a record's bytes in hand before a predicate is evaluated
// against them, so nothing has to be seen in front of a record.
const readAhead = 4096

// Reader reads the records of one file, walking the automaton this descriptor
// carries.
//
// One record at a time and in this order, which is docs/ir/SPEC.md's "Where
// framing is consumed, and where it is emitted": test for end of input at a
// record boundary, consume the framing in front of the record, evaluate the
// state's transitions — guards first, then predicates, in the order the state
// carries them — admit the record the first one that matches names, check the
// framing against that record's extent, consume the framing behind it, and apply
// that transition's bindings.
//
// The file is never held. What this carries is one record's bytes and the
// register file the automaton remembers in, whatever the file's size.
type Reader struct {
	src *bufio.Reader
	enc codec.Encoding

	// state is where in the automaton the read is, as a position in the switch
	// [Reader.Next] walks. The descriptor's state nodes are numbered by ascending
	// identifier, so a state is a small integer rather than a lookup.
	state int

	// ordinal is which record of the file has been read, counting from one, so
	// that a diagnostic can say where.
	ordinal int

	// done is whether the end of the file has been reached and reported.
	done bool

	// look is the bytes a predicate of the current state is evaluated against.
	look []byte

	// data is the record the framing states the length of, reassembled where
	// the file split it into segments. It is reused between records.
	data []byte
}

// NewReader reads the records of r under enc.
//
// Neither the charset, the zoned sign convention, the byte order, the
// floating-point format nor the binary width staircase is chosen here. They are
// properties of the file in hand rather than of this descriptor's items, so the
// caller states all five at once — [Encoding] is what this descriptor resolved,
// and a file of these records converted to another character set is read by
// passing a different one.
func NewReader(r io.Reader, enc codec.Encoding) (*Reader, error) {
	if r == nil {
		return nil, codec.ErrNilReader
	}

	if err := enc.Validate(); err != nil {
		return nil, err
	}

	return &Reader{
		src:   bufio.NewReaderSize(r, readAhead),
		enc:   enc,
		state: 0,
	}, nil
}

// Next is the next record of the file, or io.EOF where the file is complete.
//
// io.EOF means that and only that. A file cut short is reported as an error of
// its own and never wraps io.EOF, so a caller stepping through records tells
// the two apart with errors.Is and does not have to read the message.
//
// A file that ends in a state that does not accept, or whose acceptance guards
// do not all hold, is reported as truncated rather than returning the records
// that were read: an automaton whose accepting states nobody checks detects
// nothing.
func (r *Reader) Next() (Record, error) {
	if r.done {
		return nil, io.EOF
	}

	// End of input is tested here, at a record boundary, and nowhere else. By
	// the time it runs, framing behind the record before this one has been
	// consumed as the framing it is, so a file whose last record carries a
	// well-formed trailing delimiter is complete rather than holding a record
	// the layout does not describe.
	if _, err := r.src.Peek(1); err != nil {
		if !errors.Is(err, io.EOF) {
			return nil, fmt.Errorf("reading record %d: %w", r.ordinal+1, err)
		}

		r.done = true

		if err := r.accepts(); err != nil {
			return nil, err
		}

		return nil, io.EOF
	}

	r.ordinal++

	if err := r.leading(); err != nil {
		return nil, err
	}

	switch r.state {
	case 0: // the state the descriptor carries as node 2
		// Its one transition, which admits ORDER-RECORD and carries no predicate: it
		// matches every record, and this state offers nowhere else for one to go.
		rec := new(OrderRecord)

		if err := r.admit(rec); err != nil {
			return nil, err
		}

		r.state = 1

		return rec, nil
	case 1: // the state the descriptor carries as node 3
		// Its one transition, which admits TABLE-RECORD and carries no predicate: it
		// matches every record, and this state offers nowhere else for one to go.
		rec := new(TableRecord)

		if err := r.admit(rec); err != nil {
			return nil, err
		}

		r.state = 2

		return rec, nil
	case 2: // the state the descriptor carries as node 4
		expected := make([]string, 0, 1)

		// Transition 1, which admits SYNC-RECORD.
		expected = append(expected, "SYNC-RECORD")
		if matches4At0(r.look) {
			rec := new(SyncRecord)

			if err := r.admit(rec); err != nil {
				return nil, err
			}

			r.state = 3

			return rec, nil
		}

		return nil, r.undescribed(expected, "")
	case 3: // the state the descriptor carries as node 5
		// Its one transition, which admits ENTRY-RECORD and carries no predicate: it
		// matches every record, and this state offers nowhere else for one to go.
		rec := new(EntryRecord)

		if err := r.admit(rec); err != nil {
			return nil, err
		}

		r.state = 4

		return rec, nil
	case 4: // the state the descriptor carries as node 6
		// Its one transition, which admits TRAILER-RECORD and carries no predicate: it
		// matches every record, and this state offers nowhere else for one to go.
		rec := new(TrailerRecord)

		if err := r.admit(rec); err != nil {
			return nil, err
		}

		r.state = 5

		return rec, nil
	case 5: // the state the descriptor carries as node 7
		return nil, r.undescribed(nil, "")
	default:
		return nil, fmt.Errorf("record %d: the automaton is in a state this file does not carry", r.ordinal)
	}
}

// accepts is the truncation rule: a file is complete where the state the read
// ends in accepts and its acceptance guards all hold, and truncated otherwise.
//
// Guarded acceptance is what makes the last iteration of a count detectable. A
// state that reads details while a counter is positive would otherwise have to
// accept unconditionally, and would accept a file stopping three details short
// of what its own header promised.
func (r *Reader) accepts() error {
	switch r.state {
	case 5:
		return nil
	default:
		return fmt.Errorf("the file ends after %d records and the layout describes a record to come", r.ordinal)
	}
}

// undescribed is what a state says when none of its transitions took the record
// in front of the reader.
//
// A record excluded by a guard is reported as that rather than as a record the
// layout does not describe, because the two send a reader of the diagnostic to
// different places: the first is a record that does not belong at this point in
// the file, the second a record type the layout is missing.
func (r *Reader) undescribed(expected []string, excluded string) error {
	if excluded != "" {
		return fmt.Errorf("record %d does not belong here: %s", r.ordinal, excluded)
	}

	if len(expected) == 0 {
		return fmt.Errorf("record %d is a record the layout does not describe, and the automaton is in a state admitting none", r.ordinal)
	}

	return fmt.Errorf("record %d is a record the layout does not describe, and the automaton expected one of %s", r.ordinal, strings.Join(expected, ", "))
}

// leading consumes the framing in front of a record: the record descriptor word DFSMS defines,
// whose length this reader checks against the extent of the record it admits
// rather than taking a record's end from.
//
// Framing bytes belong to the dataset and not to any record: no item covers
// them, they are not slack, and no predicate ever sees one.
func (r *Reader) leading() error {
	var word [4]byte

	if _, err := io.ReadFull(r.src, word[:]); err != nil {
		return fmt.Errorf("the file ends inside the record descriptor word in front of record %d: %v", r.ordinal, err)
	}

	stated := int(word[0])<<8 | int(word[1])
	if stated < 4 {
		return fmt.Errorf("the record descriptor word in front of record %d states %d bytes, and 4 of them are the word itself", r.ordinal, stated)
	}

	r.data = r.data[:0]

	if err := r.fill(stated - 4); err != nil {
		return fmt.Errorf("the file ends part-way through record %d, which its record descriptor word states is %d bytes: %v", r.ordinal, stated-4, err)
	}

	r.look = r.data

	return nil
}

// admit decodes one record and takes its end from its extent.
//
// The input is never searched for a delimiter and a descriptor word's length is
// never preferred to the extent. Scanning is the obvious way to write a
// line-oriented reader and is wrong on exactly these files: a PIC S9(3)V99
// COMP-3 field holding +152.50 is the bytes 15 25 0C, and both 0x15 and 0x25
// are line delimiters on some mainframe code page. A reader counting the extent
// never reads those bytes as anything but the number they are.
func (r *Reader) admit(rec Record) error {
	src := bytes.NewReader(r.data)

	cr, err := codec.NewReader(src, r.enc)
	if err != nil {
		return fmt.Errorf("reading record %d: %w", r.ordinal, err)
	}

	if err := rec.UnmarshalCOBOL(cr); err != nil {
		if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
			return fmt.Errorf("the framing states record %d is %d bytes and the extent of the record it admits is longer than that: %v", r.ordinal, len(r.data), err)
		}

		return fmt.Errorf("reading record %d: %w", r.ordinal, err)
	}

	// The framing checked against the extent, which is what a framed file buys
	// over an unframed one: a wrong width or a mis-selected transition is an
	// error at the record it happened on rather than silence.
	if src.Len() != 0 {
		return fmt.Errorf("the framing states record %d is %d bytes and the extent of the record it admits is %d", r.ordinal, len(r.data), len(r.data)-src.Len())
	}

	return nil
}

// fill appends the next n bytes of the input to the record in hand.
func (r *Reader) fill(n int) error {
	if n < 0 {
		return io.ErrUnexpectedEOF
	}

	at := len(r.data)

	if cap(r.data)-at < n {
		grown := make([]byte, at+n)
		copy(grown, r.data)
		r.data = grown
	}

	r.data = r.data[:at+n]

	_, err := io.ReadFull(r.src, r.data[at:])

	return err
}

// matches4At0 is the predicate selecting transition 1 of the state the descriptor
// carries as node 4: it admits SYNC-RECORD.
//
// A target that is not wholly inside the bytes it is handed does not match. A
// reader hands it the record the framing bounds, or as much of the input as it
// can see where the framing bounds nothing; a writer hands it the whole of the
// record it is about to emit.
func matches4At0(b []byte) bool {
	if len(b) < 1 {
		return false
	}

	return bytes.Equal(b[0:1], []byte("\xe8"))
}

// Writer writes the records of one file, walking the automaton this descriptor
// carries in the other direction.
//
// Its caller names a record and supplies that record's values. It narrows to
// the transitions leaving the state it is in that admit such a record and whose
// guards all hold, evaluates their predicates in the order the state carries
// them, and takes the first that carries no predicate or whose predicate matches
// the bytes it is about to emit. A record satisfying none is reported rather
// than emitted: refusing where the mistake was made costs one diagnostic, and
// emitting costs a file somebody has to read before anyone finds out.
//
// Nothing is buffered beyond the record in hand. A count in a header is never
// back-filled from the records behind it, because holding a group to count it
// gives up exactly the streaming this type exists to have — and because a
// writer that has emitted a record cannot reach back into a stream it does not
// own.
type Writer struct {
	dst io.Writer
	enc codec.Encoding

	// state is where in the automaton the write is, numbered as [Reader.state] is.
	state int

	// ordinal is how many records have been written, so that a diagnostic can
	// say where.
	ordinal int

	// raw is the record in hand, laid out before it is emitted: a predicate is
	// evaluated against the bytes that are about to go out, so they exist
	// before the transition is chosen. It is reused between records.
	raw bytes.Buffer
}

// NewWriter writes records into w under enc.
//
// The five axes are the caller's for the reason they are on [NewReader]: they are
// properties of the file being written rather than of this descriptor's items.
func NewWriter(w io.Writer, enc codec.Encoding) (*Writer, error) {
	if w == nil {
		return nil, codec.ErrNilWriter
	}

	if err := enc.Validate(); err != nil {
		return nil, err
	}

	return &Writer{
		dst:   w,
		enc:   enc,
		state: 0,
	}, nil
}

// Write emits one record.
//
// A value that is not one of this file's record types is reported rather than
// emitted: no transition admits a record the descriptor does not carry, and
// [Record] is satisfied by anything codec can encode.
func (w *Writer) Write(rec Record) error {
	switch v := rec.(type) {
	case *EntryRecord:
		return w.writeEntryRecord(v)
	case *OrderRecord:
		return w.writeOrderRecord(v)
	case *SyncRecord:
		return w.writeSyncRecord(v)
	case *TableRecord:
		return w.writeTableRecord(v)
	case *TrailerRecord:
		return w.writeTrailerRecord(v)
	default:
		return fmt.Errorf("record %d: this file's records are ENTRY-RECORD, ORDER-RECORD, SYNC-RECORD, TABLE-RECORD and TRAILER-RECORD, and a %T is none of them", w.ordinal+1, rec)
	}
}

// Close ends the file, and reports a state that does not accept — or whose
// acceptance guards do not all hold — rather than closing it.
//
// A group that promised four details and was given three is caught here. It is
// the reader's truncation rule from the other side, and a writer skipping the
// check emits the truncated file its reader complains about one build later.
//
// It does not close the io.Writer it was handed, which belongs to the caller.
func (w *Writer) Close() error {
	switch w.state {
	case 5:
		return nil
	default:
		return fmt.Errorf("the file is closed after %d records and the layout describes a record to come", w.ordinal)
	}
}

// writeEntryRecord emits one ENTRY-RECORD.
//
// The record is laid out first and the transition is chosen against those
// bytes, because what a predicate tests is what is about to be emitted.
func (w *Writer) writeEntryRecord(rec *EntryRecord) error {
	w.raw.Reset()

	cw, err := codec.NewWriter(&w.raw, w.enc)
	if err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	if err := rec.MarshalCOBOL(cw); err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	raw := w.raw.Bytes()

	switch w.state {
	case 3: // the state the descriptor carries as node 5
		// Transition 1 of that state.
		if err := w.emit(raw); err != nil {
			return err
		}

		w.state = 4
		w.ordinal++

		return nil
	}

	return w.refuse("ENTRY-RECORD", "")
}

// writeOrderRecord emits one ORDER-RECORD.
//
// The record is laid out first and the transition is chosen against those
// bytes, because what a predicate tests is what is about to be emitted.
func (w *Writer) writeOrderRecord(rec *OrderRecord) error {
	w.raw.Reset()

	cw, err := codec.NewWriter(&w.raw, w.enc)
	if err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	if err := rec.MarshalCOBOL(cw); err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	raw := w.raw.Bytes()

	switch w.state {
	case 0: // the state the descriptor carries as node 2
		// Transition 1 of that state.
		if err := w.emit(raw); err != nil {
			return err
		}

		w.state = 1
		w.ordinal++

		return nil
	}

	return w.refuse("ORDER-RECORD", "")
}

// writeSyncRecord emits one SYNC-RECORD.
//
// The record is laid out first and the transition is chosen against those
// bytes, because what a predicate tests is what is about to be emitted.
func (w *Writer) writeSyncRecord(rec *SyncRecord) error {
	w.raw.Reset()

	cw, err := codec.NewWriter(&w.raw, w.enc)
	if err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	if err := rec.MarshalCOBOL(cw); err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	raw := w.raw.Bytes()

	switch w.state {
	case 2: // the state the descriptor carries as node 4
		// Transition 1 of that state.
		if matches4At0(raw) {
			if err := w.emit(raw); err != nil {
				return err
			}

			w.state = 3
			w.ordinal++

			return nil
		}
	}

	return w.refuse("SYNC-RECORD", "")
}

// writeTableRecord emits one TABLE-RECORD.
//
// The record is laid out first and the transition is chosen against those
// bytes, because what a predicate tests is what is about to be emitted.
func (w *Writer) writeTableRecord(rec *TableRecord) error {
	w.raw.Reset()

	cw, err := codec.NewWriter(&w.raw, w.enc)
	if err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	if err := rec.MarshalCOBOL(cw); err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	raw := w.raw.Bytes()

	switch w.state {
	case 1: // the state the descriptor carries as node 3
		// Transition 1 of that state.
		if err := w.emit(raw); err != nil {
			return err
		}

		w.state = 2
		w.ordinal++

		return nil
	}

	return w.refuse("TABLE-RECORD", "")
}

// writeTrailerRecord emits one TRAILER-RECORD.
//
// The record is laid out first and the transition is chosen against those
// bytes, because what a predicate tests is what is about to be emitted.
func (w *Writer) writeTrailerRecord(rec *TrailerRecord) error {
	w.raw.Reset()

	cw, err := codec.NewWriter(&w.raw, w.enc)
	if err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	if err := rec.MarshalCOBOL(cw); err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	raw := w.raw.Bytes()

	switch w.state {
	case 4: // the state the descriptor carries as node 6
		// Transition 1 of that state.
		if err := w.emit(raw); err != nil {
			return err
		}

		w.state = 5
		w.ordinal++

		return nil
	}

	return w.refuse("TRAILER-RECORD", "")
}

// refuse is what a writer says when no transition leaving the state it is in
// took the record it was asked to write.
//
// Two things bring a caller here and the message covers both, because the
// writer's walk is narrowed before any predicate runs: the state may admit no
// record of this type at all, which is a record written out of order, or it may
// admit one and be selected by a predicate this record's values do not satisfy.
//
// Either way the record does not belong at this point in the file with the
// values it has, and the value a predicate tests is the caller's: a writer
// checks it and reports it when it is wrong rather than deriving one that would
// satisfy the test and storing it into the field.
func (w *Writer) refuse(record string, excluded string) error {
	if excluded != "" {
		return fmt.Errorf("record %d is a %s and does not belong here: %s", w.ordinal+1, record, excluded)
	}

	return fmt.Errorf("record %d is a %s and no transition leaving the state the automaton is in takes it: that state admits no %s here, or one it admits is selected by a predicate this record's values do not satisfy. It is reported rather than emitted", w.ordinal+1, record, record)
}

// emit writes one record's bytes with this file's framing around them.
//
// The record descriptor word DFSMS defines stands in front of each record and
// states the record's length including itself.
func (w *Writer) emit(raw []byte) error {
	stated := len(raw) + 4
	if stated > 0xFFFF {
		return fmt.Errorf("record %d is %d bytes and a record descriptor word states a length of two bytes", w.ordinal+1, len(raw))
	}

	if _, err := w.dst.Write([]byte{byte(stated >> 8), byte(stated), 0, 0}); err != nil {
		return err
	}

	_, err := w.dst.Write(raw)

	return err
}
