// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The file tier of this package's generated tests: one case per path through the
// automaton this layout describes, and between them every transition predicate it
// carries and every literal of a set-membership one.
//
// Each case carries a whole file as a literal — the framing as well as the records
// — reads it with the generated Reader, checks that the record types came back in
// the order the automaton admits them, writes them back with the generated Writer
// and checks that the bytes are the bytes it started from. The file is synthesized
// from the layout rather than read from a dataset, so it is what to hold against
// the file on your desk: the comment column names each run, the offset inside its
// record, and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports orders.
package orders_test

import (
	"bytes"
	"errors"
	"github.com/Zaba505/cpybkc/cmd/cpybkc-gen-go/internal/orders"
	"io"
	"testing"
)

// TestAnOrderRecordThenATableRecordThenASyncRecordThenAnEntryRecordThenATrailerRecord
// is a file of ORDER-RECORD, TABLE-RECORD, SYNC-RECORD, ENTRY-RECORD and
// TRAILER-RECORD: the bytes below, the records they read back as, and the same
// bytes written back.
//
// The discriminators it walks: SYNC-FLAG holding "\xe8".
func TestAnOrderRecordThenATableRecordThenASyncRecordThenAnEntryRecordThenATrailerRecord(t *testing.T) {
	t.Parallel()

	in := []byte{
		0x00, 0x5a, 0x00, 0x00, // record 1: the record descriptor word — 90 bytes, itself included
		0xf0, 0xf0, 0xf0, 0xf0, 0xf1, // record 1: ORDER-ID @0 9(5)
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, // record 1: CUSTOMER-NAME @5 X(20)
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, //
		0xc6, 0xc6, 0xc6, 0xc6, //
		0xb9, 0xba, // record 1: (slack) @25 2 bytes no item covers
		0x00, 0x00, 0x02, 0x8d, // record 1: ORDER-TOTAL @27 S9(5)V9(2) PACKED-DECIMAL
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, // record 1: LINE-ITEM(1).SKU @31 X(8)
		0xff, 0xd8, // record 1: LINE-ITEM(1).QUANTITY @39 S9(4) BINARY
		0xc9,                                           // record 1: LINE-ITEM(1).(slack) @41 1 byte no item covers
		0xca,                                           // record 1: LINE-ITEM(1).FILLER @42 X(1)
		0xd9, 0xd9, 0xd9, 0xd9, 0xd9, 0xd9, 0xd9, 0xd9, // record 1: LINE-ITEM(2).SKU @43 X(8)
		0xff, 0xcc, // record 1: LINE-ITEM(2).QUANTITY @51 S9(4) BINARY
		0xd5,                                           // record 1: LINE-ITEM(2).(slack) @53 1 byte no item covers
		0xd6,                                           // record 1: LINE-ITEM(2).FILLER @54 X(1)
		0xc4, 0xc4, 0xc4, 0xc4, 0xc4, 0xc4, 0xc4, 0xc4, // record 1: LINE-ITEM(3).SKU @55 X(8)
		0xff, 0xc0, // record 1: LINE-ITEM(3).QUANTITY @63 S9(4) BINARY
		0xe1,                   // record 1: LINE-ITEM(3).(slack) @65 1 byte no item covers
		0xe2,                   // record 1: LINE-ITEM(3).FILLER @66 X(1)
		0xe3, 0xe4, 0xe5, 0xe6, // record 1: FILLER @67 X(4)
		0xe3, 0xe3, // record 1: NOTE-CODE @71 X(2)
		0xf0, 0xf0, 0xf1, // record 1: DETAIL-COUNT @73 9(3)
		0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, // record 1: DETAIL(1).DETAIL-TEXT @76 X(10)
		0xe8, 0xe8, //
		0x00, 0x0c, 0x00, 0x00, // record 2: the record descriptor word — 12 bytes, itself included
		0xf0, 0xf1, // record 2: PAIR-COUNT @0 9(2)
		0xc3, 0xc3, 0xc3, // record 2: LEFT-ITEM(1).LEFT-TEXT @2 X(3)
		0xc6, 0xc6, // record 2: RIGHT-ITEM(1).RIGHT-TEXT @5 X(2)
		0xc8,                   // record 2: BLOCK(1).BLOCK-ITEM(1).BLOCK-TEXT @7 X(1)
		0x00, 0x14, 0x00, 0x00, // record 3: the record descriptor word — 20 bytes, itself included
		0xe8,             // record 3: SYNC-FLAG @0 X(1)
		0xa1, 0xa2, 0xa3, // record 3: (slack) @1 3 bytes no item covers
		0xff, 0xff, 0xff, 0xfb, // record 3: SYNC-COUNTER @4 S9(9) BINARY
		0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, // record 3: (slack) @8 8 bytes no item covers
		0x00, 0x19, 0x00, 0x00, // record 4: the record descriptor word — 25 bytes, itself included
		0xc4,                   // record 4: ENTRY(1).ENTRY-TYPE @0 X(1)
		0xc2, 0xc2, 0xc2, 0xc2, // record 4: ENTRY(1).ENTRY-DETAIL.DETAIL-SKU @1 X(4)
		0xff, 0xfa, // record 4: ENTRY(1).ENTRY-DETAIL.DETAIL-QTY @5 S9(4) BINARY
		0xc4,                   // record 4: ENTRY(2).ENTRY-TYPE @7 X(1)
		0xc9, 0xc9, 0xc9, 0xc9, // record 4: ENTRY(2).ENTRY-DETAIL.DETAIL-SKU @8 X(4)
		0xff, 0xf3, // record 4: ENTRY(2).ENTRY-DETAIL.DETAIL-QTY @12 S9(4) BINARY
		0xc4,                   // record 4: ENTRY(3).ENTRY-TYPE @14 X(1)
		0xd7, 0xd7, 0xd7, 0xd7, // record 4: ENTRY(3).ENTRY-DETAIL.DETAIL-SKU @15 X(4)
		0xff, 0xec, // record 4: ENTRY(3).ENTRY-DETAIL.DETAIL-QTY @19 S9(4) BINARY
		0x00, 0x2f, 0x00, 0x00, // record 5: the record descriptor word — 47 bytes, itself included
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // record 5: GRAND-TOTAL @0 S9(20) PACKED-DECIMAL
		0x00, 0x00, 0x1d, //
		0x41, 0xc8, 0x00, 0x00, // record 5: EXCHANGE-RATE @11 COMP-1
		0xaf, 0xb0, 0xb1, 0xb2, // record 5: TABLE-INDEX @15 INDEX
		0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, // record 5: PRINTED-TOTAL(1) @19 numeric-edited, 12 bytes
		0xe3, 0xe3, 0xe3, 0xe3, //
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, // record 5: PRINTED-TOTAL(2) @31 numeric-edited, 12 bytes
		0xc6, 0xc6, 0xc6, 0xc6, //
	}

	r, err := orders.NewReader(bytes.NewReader(in), orders.Encoding())
	if err != nil {
		t.Fatalf("NewReader: %v", err)
	}

	var records []orders.Record

	for {
		rec, err := r.Next()
		if errors.Is(err, io.EOF) {
			break
		}

		if err != nil {
			t.Fatalf("Next: %v", err)
		}

		records = append(records, rec)
	}

	if len(records) != 5 {
		t.Fatalf("the file holds 5 records and the reader produced %d", len(records))
	}

	if _, ok := records[0].(*orders.OrderRecord); !ok {
		t.Fatalf("record 1 is ORDER-RECORD and came back as a %T, want a *orders.OrderRecord", records[0])
	}

	if _, ok := records[1].(*orders.TableRecord); !ok {
		t.Fatalf("record 2 is TABLE-RECORD and came back as a %T, want a *orders.TableRecord", records[1])
	}

	record3, ok := records[2].(*orders.SyncRecord)
	if !ok {
		t.Fatalf("record 3 is SYNC-RECORD and came back as a %T, want a *orders.SyncRecord", records[2])
	}

	if record3.SyncFlag != "Y" {
		t.Errorf("SYNC-FLAG: got %q, want %q", record3.SyncFlag, "Y")
	}

	if _, ok := records[3].(*orders.EntryRecord); !ok {
		t.Fatalf("record 4 is ENTRY-RECORD and came back as a %T, want a *orders.EntryRecord", records[3])
	}

	if _, ok := records[4].(*orders.TrailerRecord); !ok {
		t.Fatalf("record 5 is TRAILER-RECORD and came back as a %T, want a *orders.TrailerRecord", records[4])
	}

	var out bytes.Buffer

	w, err := orders.NewWriter(&out, orders.Encoding())
	if err != nil {
		t.Fatalf("NewWriter: %v", err)
	}

	for _, rec := range records {
		if err := w.Write(rec); err != nil {
			t.Fatalf("Write: %v", err)
		}
	}

	if err := w.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the file does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
