// Code generated by cpybkc-gen-go. DO NOT EDIT.

package member

import (
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
)

// Encoding is the byte-level interpretation of the files these records live in:
// the five axes as they were resolved — four the layout declared, and the binary
// width staircase the copybook's items were laid out under.
//
// None of the five has a default and every one of them fails silently when
// wrong, so codec has no usable zero-value Reader and this function is how a
// caller states all five at once:
//
//	r, err := codec.NewReader(f, Encoding())
//
// Binary is the odd one. The other four say how a byte becomes a value; this one
// says how many bytes a COMP item is, which is a property of the compiler that
// wrote the file rather than of the copybook — PIC S9(2) COMP is two bytes under
// IBM Enterprise COBOL and one under GnuCOBOL's default. It is the staircase the
// offsets in these records were computed under, so changing it here does not
// reinterpret the file, it describes a different one.
//
// It is a value a caller passes rather than one anything applies on its own. A
// file this descriptor describes that was converted to another character set is
// read by passing a different Encoding, not by regenerating.
func Encoding() codec.Encoding {
	return codec.Encoding{
		Charset:   codec.CP037(),
		Sign:      codec.SignEBCDIC,
		ByteOrder: binary.BigEndian,
		Float:     codec.FloatIEEE,
		Binary:    codec.BinarySize248,
	}
}

// Every record reads and writes itself, which is codec's Unmarshaler and
// Marshaler. Asserted here so that a drift in either interface fails in the
// file that implements it.
var (
	_ codec.Unmarshaler = (*MemberRecord)(nil)
	_ codec.Marshaler   = (*MemberRecord)(nil)
)

// zeroFill is what a writer emits for a run of bytes a record its caller built
// rather than read carries none for: zero bytes, 27 of them at the most, sliced
// to the run's own width.
//
// Three kinds of run reach it. A slack node and an item the copybook gives no
// data-name hold bytes no program names. An item the layout says carries a
// payload rather than characters is a []byte a caller can name and set, and
// this is what it gets where they left it nil.
//
// Zero rather than a space, and the reason differs by run. Charset is a
// property of a field and slack is not a field, so there is no charset to
// resolve a space against and zero is the byte that names none. A FILLER is a
// field and does have one, and filling it with spaces would be choosing a value
// on behalf of a caller who never had one to give. A payload item has no pad
// byte that is not also a legal value of it — the space that pads a text item
// is a byte such an item may hold — so a writer handed nothing writes zeros
// rather than choosing a byte that could have been data.
//
// Those bytes were never in a file, so nothing is being overwritten — a record
// that was read carries the bytes it was read from and they are emitted
// instead. See docs/ir/SPEC.md, "What the descriptor determines, a writer
// supplies".
var zeroFill = make([]byte, 27)

// resized is s with n zero occurrences in it.
//
// s is read for its type as much as for its capacity, and that is why this is a
// function rather than a make: a group inside a record is an anonymous struct
// type, which has no name to write inside a make. Type inference supplies what
// there is no identifier for, and nothing here reflects.
func resized[T any](s []T, n int) []T {
	if n <= cap(s) {
		s = s[:n]
		clear(s)

		return s
	}

	return make([]T, n)
}

// fresh is a zeroed arm to decode into, reusing the one the record already holds
// where it holds one.
//
// It exists for the reason resized does: an arm's body is an anonymous struct type,
// so there is no name for a new to take, and the pointer's own type is what
// supplies it.
func fresh[T any](p *T) *T {
	if p != nil {
		var zero T
		*p = zero

		return p
	}

	return new(T)
}

// UnmarshalCOBOL reads one MEMBER-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (m *MemberRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	// entry2 reads one occurrence of MBR-ADDRESS, which carries a variant and so is read
	// whole before it is walked. It is built here rather than inside the loop
	// over those occurrences, and rewound onto each occurrence's bytes there.
	var entry2 *codec.Reader
	if entry2, err = codec.NewBytesReader(nil, r.Encoding()); err != nil {
		return fmt.Errorf("MEMBER-RECORD: building the decoder the occurrences of MBR-ADDRESS are read through: %w", err)
	}

	if m.MbrMemberId, err = r.ReadAlphanumeric(10); err != nil {
		return fmt.Errorf("MEMBER-RECORD: reading MBR-MEMBER-ID: %w", err)
	}

	if m.MbrName, err = r.ReadAlphanumeric(30); err != nil {
		return fmt.Errorf("MEMBER-RECORD: reading MBR-NAME: %w", err)
	}

	if m.MbrAddressCount, err = r.ReadZonedInt32(1, codec.SignUnsigned); err != nil {
		return fmt.Errorf("MEMBER-RECORD: reading MBR-ADDRESS-COUNT: %w", err)
	}

	n1 := int(m.MbrAddressCount)
	if n1 < 1 || n1 > 3 {
		return fmt.Errorf("MEMBER-RECORD: MBR-ADDRESS occurs 1 to 3 times depending on MBR-ADDRESS-COUNT, and the record's count is %d", n1)
	}
	m.MbrAddress = resized(m.MbrAddress, n1)
	for i0 := range m.MbrAddress {
		var occurrence1 []byte
		if occurrence1, err = r.ReadBytes(61); err != nil {
			return fmt.Errorf("MEMBER-RECORD: reading its bytes in occurrence %d of MBR-ADDRESS: %w", i0, err)
		}
		entry2.Reset(occurrence1)
		switch i0 + 1 {
		case 1:
			m.MbrAddress[i0].AdrHome = fresh(m.MbrAddress[i0].AdrHome)
			m.MbrAddress[i0].AdrWork = nil
			m.MbrAddress[i0].AdrMail = nil
			if m.MbrAddress[i0].AdrHome.AhmStreet, err = entry2.ReadAlphanumeric(30); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AHM-STREET in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrHome.AhmCity, err = entry2.ReadAlphanumeric(20); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AHM-CITY in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrHome.AhmRegion, err = entry2.ReadAlphanumeric(2); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AHM-REGION in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrHome.AhmPostal, err = entry2.ReadAlphanumeric(9); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AHM-POSTAL in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}
		case 2:
			m.MbrAddress[i0].AdrWork = fresh(m.MbrAddress[i0].AdrWork)
			m.MbrAddress[i0].AdrHome = nil
			m.MbrAddress[i0].AdrMail = nil
			if m.MbrAddress[i0].AdrWork.AwkEmployer, err = entry2.ReadAlphanumeric(30); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AWK-EMPLOYER in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrWork.AwkStreet, err = entry2.ReadAlphanumeric(20); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AWK-STREET in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrWork.AwkRegion, err = entry2.ReadAlphanumeric(2); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AWK-REGION in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrWork.AwkPostal, err = entry2.ReadAlphanumeric(9); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AWK-POSTAL in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}
		case 3:
			m.MbrAddress[i0].AdrMail = fresh(m.MbrAddress[i0].AdrMail)
			m.MbrAddress[i0].AdrHome = nil
			m.MbrAddress[i0].AdrWork = nil
			if m.MbrAddress[i0].AdrMail.AmlBox, err = entry2.ReadAlphanumeric(12); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AML-BOX in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrMail.AmlCity, err = entry2.ReadAlphanumeric(20); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AML-CITY in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrMail.AmlRegion, err = entry2.ReadAlphanumeric(2); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading AML-REGION in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if m.MbrAddress[i0].AdrMail.slack[0], err = entry2.ReadBytes(27); err != nil {
				return fmt.Errorf("MEMBER-RECORD: reading the 27 bytes no item of it covers in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}
		}
	}

	if m.MbrStatus, err = r.ReadAlphanumeric(1); err != nil {
		return fmt.Errorf("MEMBER-RECORD: reading MBR-STATUS: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this MEMBER-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
//
// The arm of a table whose entries are chosen by their position is the
// descriptor's too. The schedule assigns one arm to each occurrence, so that
// arm is written whatever the record holds, and a caller that filled in
// another is reported rather than picked between.
func (m *MemberRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	// entry2 lays out one occurrence of MBR-ADDRESS, which carries a variant and so is
	// laid out whole, so that it is the width every other occurrence of it is
	// whichever arm the schedule assigned it.
	// It is built here rather than inside the loop over those occurrences, and
	// rewound onto its own buffer there.
	var entry2 *codec.Writer
	if entry2, err = codec.NewBytesWriter(nil, w.Encoding()); err != nil {
		return fmt.Errorf("MEMBER-RECORD: building the encoder the occurrences of MBR-ADDRESS are written through: %w", err)
	}

	if err = w.WriteAlphanumeric(m.MbrMemberId, 10); err != nil {
		return fmt.Errorf("MEMBER-RECORD: writing MBR-MEMBER-ID: %w", err)
	}

	if err = w.WriteAlphanumeric(m.MbrName, 30); err != nil {
		return fmt.Errorf("MEMBER-RECORD: writing MBR-NAME: %w", err)
	}

	count1 := len(m.MbrAddress)
	if count1 < 1 || count1 > 3 {
		return fmt.Errorf("MEMBER-RECORD: MBR-ADDRESS occurs 1 to 3 times depending on MBR-ADDRESS-COUNT, and the record holds %d occurrences of it", count1)
	}
	if err = w.WriteZonedInt32(int32(count1), 1, codec.SignUnsigned); err != nil {
		return fmt.Errorf("MEMBER-RECORD: writing MBR-ADDRESS-COUNT: %w", err)
	}

	for i0 := range m.MbrAddress {
		entry2.Reset(entry2.Bytes())
		switch i0 + 1 {
		case 1:
			if m.MbrAddress[i0].AdrWork != nil {
				return fmt.Errorf("MEMBER-RECORD: a writer emits the arm the schedule assigns and never the one its caller named, and the schedule assigns ADR-HOME to this occurrence while the record holds ADR-WORK in occurrence %d of MBR-ADDRESS", i0)
			}
			if m.MbrAddress[i0].AdrMail != nil {
				return fmt.Errorf("MEMBER-RECORD: a writer emits the arm the schedule assigns and never the one its caller named, and the schedule assigns ADR-HOME to this occurrence while the record holds ADR-MAIL in occurrence %d of MBR-ADDRESS", i0)
			}
			if m.MbrAddress[i0].AdrHome == nil {
				return fmt.Errorf("MEMBER-RECORD: the schedule assigns ADR-HOME to this occurrence and the record holds no arm of the alternation over ADR-HOME in occurrence %d of MBR-ADDRESS", i0)
			}
			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrHome.AhmStreet, 30); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AHM-STREET in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrHome.AhmCity, 20); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AHM-CITY in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrHome.AhmRegion, 2); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AHM-REGION in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrHome.AhmPostal, 9); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AHM-POSTAL in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}
		case 2:
			if m.MbrAddress[i0].AdrHome != nil {
				return fmt.Errorf("MEMBER-RECORD: a writer emits the arm the schedule assigns and never the one its caller named, and the schedule assigns ADR-WORK to this occurrence while the record holds ADR-HOME in occurrence %d of MBR-ADDRESS", i0)
			}
			if m.MbrAddress[i0].AdrMail != nil {
				return fmt.Errorf("MEMBER-RECORD: a writer emits the arm the schedule assigns and never the one its caller named, and the schedule assigns ADR-WORK to this occurrence while the record holds ADR-MAIL in occurrence %d of MBR-ADDRESS", i0)
			}
			if m.MbrAddress[i0].AdrWork == nil {
				return fmt.Errorf("MEMBER-RECORD: the schedule assigns ADR-WORK to this occurrence and the record holds no arm of the alternation over ADR-HOME in occurrence %d of MBR-ADDRESS", i0)
			}
			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrWork.AwkEmployer, 30); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AWK-EMPLOYER in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrWork.AwkStreet, 20); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AWK-STREET in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrWork.AwkRegion, 2); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AWK-REGION in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrWork.AwkPostal, 9); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AWK-POSTAL in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}
		case 3:
			if m.MbrAddress[i0].AdrHome != nil {
				return fmt.Errorf("MEMBER-RECORD: a writer emits the arm the schedule assigns and never the one its caller named, and the schedule assigns ADR-MAIL to this occurrence while the record holds ADR-HOME in occurrence %d of MBR-ADDRESS", i0)
			}
			if m.MbrAddress[i0].AdrWork != nil {
				return fmt.Errorf("MEMBER-RECORD: a writer emits the arm the schedule assigns and never the one its caller named, and the schedule assigns ADR-MAIL to this occurrence while the record holds ADR-WORK in occurrence %d of MBR-ADDRESS", i0)
			}
			if m.MbrAddress[i0].AdrMail == nil {
				return fmt.Errorf("MEMBER-RECORD: the schedule assigns ADR-MAIL to this occurrence and the record holds no arm of the alternation over ADR-HOME in occurrence %d of MBR-ADDRESS", i0)
			}
			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrMail.AmlBox, 12); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AML-BOX in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrMail.AmlCity, 20); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AML-CITY in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			if err = entry2.WriteAlphanumeric(m.MbrAddress[i0].AdrMail.AmlRegion, 2); err != nil {
				return fmt.Errorf("MEMBER-RECORD: writing AML-REGION in occurrence %d of MBR-ADDRESS: %w", i0, err)
			}

			switch {
			case m.MbrAddress[i0].AdrMail.slack[0] == nil:
				if err = entry2.WriteBytes(zeroFill[:27]); err != nil {
					return fmt.Errorf("MEMBER-RECORD: writing 27 zero bytes for slack this record carries none for in occurrence %d of MBR-ADDRESS: %w", i0, err)
				}
			case len(m.MbrAddress[i0].AdrMail.slack[0]) != 27:
				return fmt.Errorf("MEMBER-RECORD: a writer reports a retained run rather than truncating or padding it, and the run for a slack node of 27 bytes is %d in occurrence %d of MBR-ADDRESS", len(m.MbrAddress[i0].AdrMail.slack[0]), i0)
			default:
				if err = entry2.WriteBytes(m.MbrAddress[i0].AdrMail.slack[0]); err != nil {
					return fmt.Errorf("MEMBER-RECORD: writing the 27 bytes no item of it covers in occurrence %d of MBR-ADDRESS: %w", i0, err)
				}
			}
		}
		if err = w.WriteBytes(entry2.Bytes()); err != nil {
			return fmt.Errorf("MEMBER-RECORD: writing its bytes in occurrence %d of MBR-ADDRESS: %w", i0, err)
		}
	}

	if err = w.WriteAlphanumeric(m.MbrStatus, 1); err != nil {
		return fmt.Errorf("MEMBER-RECORD: writing MBR-STATUS: %w", err)
	}

	return nil
}
