// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The file tier of this package's generated tests: one case per path through the
// automaton this layout describes, and between them every transition predicate it
// carries and every literal of a set-membership one.
//
// Each case carries a whole file as a literal — the framing as well as the records
// — reads it with the generated Reader, checks that the record types came back in
// the order the automaton admits them, writes them back with the generated Writer
// and checks that the bytes are the bytes it started from. The file is synthesized
// from the layout rather than read from a dataset, so it is what to hold against
// the file on your desk: the comment column names each run, the offset inside its
// record, and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports member.
package member_test

import (
	"bytes"
	"errors"
	"github.com/Zaba505/cpybkc/example/member/member"
	"io"
	"testing"
)

// TestTwoMemberRecords is a file of two MEMBER-RECORD records: the bytes
// below, the records they read back as, and the same bytes written back.
func TestTwoMemberRecords(t *testing.T) {
	t.Parallel()

	in := []byte{
		0x00, 0x6b, 0x00, 0x00, // record 1: the record descriptor word — 107 bytes, itself included
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // record 1: MBR-MEMBER-ID @0 X(10)
		0xc1, 0xc1, //
		0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, // record 1: MBR-NAME @10 X(30)
		0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, //
		0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, //
		0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, //
		0xf1,                                           // record 1: MBR-ADDRESS-COUNT @40 9(1)
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, // record 1: MBR-ADDRESS(1).ADR-HOME.AHM-STREET @41 X(30)
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, //
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, //
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, //
		0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, // record 1: MBR-ADDRESS(1).ADR-HOME.AHM-CITY @71 X(20)
		0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, //
		0xe3, 0xe3, 0xe3, 0xe3, //
		0xd5, 0xd5, // record 1: MBR-ADDRESS(1).ADR-HOME.AHM-REGION @91 X(2)
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, // record 1: MBR-ADDRESS(1).ADR-HOME.AHM-POSTAL @93 X(9)
		0xd7,                   //
		0xe8,                   // record 1: MBR-STATUS @102 X(1)
		0x00, 0x6b, 0x00, 0x00, // record 2: the record descriptor word — 107 bytes, itself included
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // record 2: MBR-MEMBER-ID @0 X(10)
		0xc1, 0xc1, //
		0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, // record 2: MBR-NAME @10 X(30)
		0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, //
		0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, //
		0xd2, 0xd2, 0xd2, 0xd2, 0xd2, 0xd2, //
		0xf1,                                           // record 2: MBR-ADDRESS-COUNT @40 9(1)
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, // record 2: MBR-ADDRESS(1).ADR-HOME.AHM-STREET @41 X(30)
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, //
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, //
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, //
		0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, // record 2: MBR-ADDRESS(1).ADR-HOME.AHM-CITY @71 X(20)
		0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, 0xe3, //
		0xe3, 0xe3, 0xe3, 0xe3, //
		0xd5, 0xd5, // record 2: MBR-ADDRESS(1).ADR-HOME.AHM-REGION @91 X(2)
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, 0xd7, // record 2: MBR-ADDRESS(1).ADR-HOME.AHM-POSTAL @93 X(9)
		0xd7, //
		0xe8, // record 2: MBR-STATUS @102 X(1)
	}

	r, err := member.NewReader(bytes.NewReader(in), member.Encoding())
	if err != nil {
		t.Fatalf("NewReader: %v", err)
	}

	var records []member.Record

	for {
		rec, err := r.Next()
		if errors.Is(err, io.EOF) {
			break
		}

		if err != nil {
			t.Fatalf("Next: %v", err)
		}

		records = append(records, rec)
	}

	if len(records) != 2 {
		t.Fatalf("the file holds 2 records and the reader produced %d", len(records))
	}

	if _, ok := records[0].(*member.MemberRecord); !ok {
		t.Fatalf("record 1 is MEMBER-RECORD and came back as a %T, want a *member.MemberRecord", records[0])
	}

	if _, ok := records[1].(*member.MemberRecord); !ok {
		t.Fatalf("record 2 is MEMBER-RECORD and came back as a %T, want a *member.MemberRecord", records[1])
	}

	var out bytes.Buffer

	w, err := member.NewWriter(&out, member.Encoding())
	if err != nil {
		t.Fatalf("NewWriter: %v", err)
	}

	for _, rec := range records {
		if err := w.Write(rec); err != nil {
			t.Fatalf("Write: %v", err)
		}
	}

	if err := w.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the file does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
