// Code generated by cpybkc-gen-go. DO NOT EDIT.

package member

// MemberRecord is the MEMBER-RECORD record, as docs/ir/SPEC.md resolved it.
type MemberRecord struct {
	// MbrMemberId is MBR-MEMBER-ID — alphanumeric, DISPLAY, 10 bytes.
	MbrMemberId string

	// MbrName is MBR-NAME — alphanumeric, DISPLAY, 30 bytes.
	MbrName string

	// MbrAddressCount is MBR-ADDRESS-COUNT — numeric, DISPLAY, 1 digit, unsigned, 1 byte.
	MbrAddressCount int32

	// MbrAddress is MBR-ADDRESS — a group of 1 member, OCCURS 1 TO 3 DEPENDING ON MBR-ADDRESS-COUNT.
	MbrAddress []struct {
		// AdrHome is ADR-HOME — a group of 4 members.
		//
		// It is one alternative over one run of bytes, beside AdrWork and AdrMail: exactly one of
		// them is non-nil in an occurrence, and it is the one the record holds.
		//
		// The layout says which of them, and no byte of an occurrence does: this arm
		// is occurrence 1 of the table, and a writer emits the arm the schedule
		// assigns whatever this record holds — a caller that filled in another is
		// reported rather than picked between.
		// See docs/ir/SPEC.md, "An arm may be selected by its position in the table".
		AdrHome *struct {
			// AhmStreet is AHM-STREET — alphanumeric, DISPLAY, 30 bytes.
			AhmStreet string

			// AhmCity is AHM-CITY — alphanumeric, DISPLAY, 20 bytes.
			AhmCity string

			// AhmRegion is AHM-REGION — alphanumeric, DISPLAY, 2 bytes.
			AhmRegion string

			// AhmPostal is AHM-POSTAL — alphanumeric, DISPLAY, 9 bytes.
			AhmPostal string
		}

		// AdrWork is ADR-WORK — a group of 4 members.
		//
		// It is one alternative over one run of bytes, beside AdrHome and AdrMail: exactly one of
		// them is non-nil in an occurrence, and it is the one the record holds.
		//
		// The layout says which of them, and no byte of an occurrence does: this arm
		// is occurrence 2 of the table, and a writer emits the arm the schedule
		// assigns whatever this record holds — a caller that filled in another is
		// reported rather than picked between.
		// See docs/ir/SPEC.md, "An arm may be selected by its position in the table".
		AdrWork *struct {
			// AwkEmployer is AWK-EMPLOYER — alphanumeric, DISPLAY, 30 bytes.
			AwkEmployer string

			// AwkStreet is AWK-STREET — alphanumeric, DISPLAY, 20 bytes.
			AwkStreet string

			// AwkRegion is AWK-REGION — alphanumeric, DISPLAY, 2 bytes.
			AwkRegion string

			// AwkPostal is AWK-POSTAL — alphanumeric, DISPLAY, 9 bytes.
			AwkPostal string
		}

		// AdrMail is ADR-MAIL — a group of 4 members.
		//
		// It is one alternative over one run of bytes, beside AdrHome and AdrWork: exactly one of
		// them is non-nil in an occurrence, and it is the one the record holds.
		//
		// The layout says which of them, and no byte of an occurrence does: this arm
		// is occurrence 3 of the table, and a writer emits the arm the schedule
		// assigns whatever this record holds — a caller that filled in another is
		// reported rather than picked between.
		// See docs/ir/SPEC.md, "An arm may be selected by its position in the table".
		AdrMail *struct {
			// AmlBox is AML-BOX — alphanumeric, DISPLAY, 12 bytes.
			AmlBox string

			// AmlCity is AML-CITY — alphanumeric, DISPLAY, 20 bytes.
			AmlCity string

			// AmlRegion is AML-REGION — alphanumeric, DISPLAY, 2 bytes.
			AmlRegion string

			// slack is the bytes retained for the slack nodes among this item's
			// members, in the order those nodes occupy the record: one run each, as
			// they stood when the record was read, and one set of them per occurrence
			// of this struct. A nil run is one the record does not carry; an empty run
			// is a run of no bytes, and the two are not the same.
			//
			// They travel with the record and there is nothing here for a caller to do.
			// See docs/ir/SPEC.md, "Slack survives a read".
			slack [1][]byte
		}
	}

	// MbrStatus is MBR-STATUS — alphanumeric, DISPLAY, 1 byte.
	MbrStatus string
}
