// Copyright (c) 2026 Richard Carson Derr
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/Zaba505/cpybkc/irpb"
)

// generatedFile is the one file this generator writes so far: the package's
// doc file, carrying the package clause and nothing else.
//
// The structs, the decode and encode methods, the file-level reader and writer
// and the codec assertions are #49–#53, and each lands as a file beside this
// one. A package that is nothing but a package clause is still a package that
// compiles, which is what makes the scaffold something a user can point cpybkc
// at rather than a program that is not finished.
const generatedFile = "doc.go"

// generatedBy is the line Go's own tooling reads to know a file was not written
// by hand. `^// Code generated .* DO NOT EDIT\.$` is the form cmd/go matches,
// and matching it is what keeps generated output out of a vet run's blame and
// out of a reviewer's way.
const generatedBy = "// Code generated by " + pluginName + ". DO NOT EDIT."

// generate writes this invocation's output beneath out.
//
// The descriptor is a parameter and its nodes are not read: what is generated
// from them is #49–#53's, and the signature is the one those stories fill in
// rather than one they have to invent. What is settled here is everything
// around them — where files go, that they are gofmt-clean, and that the same
// descriptor and the same options produce the same bytes.
//
// docs/plugin/SPEC.md's "Determinism" is met by there being nothing in the
// output that is not a function of those two: no timestamp, no hostname, no
// user, no absolute path, and no value read from anywhere but the arguments.
// The generator's own name is in the output and is allowed to be — it is a
// property of the executable rather than of the invocation, and output that
// changes when the generator is upgraded is expected.
func generate(descriptor *irpb.Descriptor, out string, opts options) error {
	source := fmt.Sprintf("%s\n\npackage %s\n", generatedBy, opts.packageName)

	// Formatted rather than trusted to be formatted. It costs nothing on a file
	// this size, and it is the check that makes "generated code is gofmt-clean"
	// a property of the program rather than of whoever wrote the template that
	// produced it — which is worth having in place before #49 starts producing
	// declarations.
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("failed to format the generated %s: %w", generatedFile, err)
	}

	// Written directly beneath out, and beneath it only: docs/plugin/SPEC.md
	// gives this program an empty, writable directory of its own and forbids it
	// to write anywhere else. The path is joined here rather than anywhere a
	// file name could arrive from outside this program.
	path := filepath.Join(out, generatedFile)

	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", generatedFile, err)
	}

	return nil
}
