// Copyright (c) 2026 Richard Carson Derr
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"github.com/Zaba505/cpybkc/irpb"
)

// generatedFile is the package's doc file, carrying the package clause and
// nothing else. It is written for every descriptor, including one carrying no
// record node at all: a package that is nothing but a package clause is still a
// package that compiles, which is what makes the output something a user can
// point cpybkc at rather than a program that is not finished.
//
// The record structs land beside it in [recordsFile]. The decode and encode
// methods, the file-level reader and writer and the codec assertions are
// #51–#53, and each lands as a file of its own for the same reason.
const generatedFile = "doc.go"

// generatedBy is the line Go's own tooling reads to know a file was not written
// by hand. `^// Code generated .* DO NOT EDIT\.$` is the form cmd/go matches,
// and matching it is what keeps generated output out of a vet run's blame and
// out of a reviewer's way.
const generatedBy = "// Code generated by " + pluginName + ". DO NOT EDIT."

// generate writes this invocation's output beneath out.
//
// docs/plugin/SPEC.md's "Determinism" is met by there being nothing in the
// output that is not a function of the descriptor and the options: no
// timestamp, no hostname, no user, no absolute path, and no value read from
// anywhere but the arguments. The generator's own name is in the output and is
// allowed to be — it is a property of the executable rather than of the
// invocation, and output that changes when the generator is upgraded is
// expected.
//
// Every file is composed and formatted before any is written, so that a
// descriptor this generator refuses leaves the output directory as it found it
// — empty. A generator that wrote as it went would hand cpybkc a directory it
// is entitled to merge, holding half a package.
func generate(descriptor *irpb.Descriptor, out string, opts options) error {
	sources := map[string]string{
		generatedFile: fmt.Sprintf("%s\n\npackage %s\n", generatedBy, opts.packageName),
	}

	structs, err := records(descriptor, opts)
	if err != nil {
		return err
	}

	// Absent, rather than a file holding a package clause and no declaration,
	// where the descriptor carries no record node. There is nothing in such a
	// file that doc.go does not already say.
	if structs != "" {
		sources[recordsFile] = structs
	}

	names := make([]string, 0, len(sources))
	for name := range sources {
		names = append(names, name)
	}

	sort.Strings(names)

	formatted := make(map[string][]byte, len(sources))

	for _, name := range names {
		// Formatted rather than trusted to be formatted. It is the check that
		// makes "generated code is gofmt-clean" a property of the program
		// rather than of whoever wrote the template that produced it, and on a
		// struct emitter it is also what decides the indentation, so that
		// nothing here has to count tabs.
		b, err := format.Source([]byte(sources[name]))
		if err != nil {
			return fmt.Errorf("failed to format the generated %s: %w", name, err)
		}

		formatted[name] = b
	}

	for _, name := range names {
		// Written directly beneath out, and beneath it only: docs/plugin/SPEC.md
		// gives this program an empty, writable directory of its own and forbids
		// it to write anywhere else. The path is joined here rather than anywhere
		// a file name could arrive from outside this program.
		if err := os.WriteFile(filepath.Join(out, name), formatted[name], 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", name, err)
		}
	}

	return nil
}
