// Code generated by cpybkc-gen-go. DO NOT EDIT.

package ledger

import (
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
)

// Encoding is the byte-level interpretation of the files these records live in:
// the five axes as they were resolved — four the layout declared, and the binary
// width staircase the copybook's items were laid out under.
//
// None of the five has a default and every one of them fails silently when
// wrong, so codec has no usable zero-value Reader and this function is how a
// caller states all five at once:
//
//	r, err := codec.NewReader(f, Encoding())
//
// Binary is the odd one. The other four say how a byte becomes a value; this one
// says how many bytes a COMP item is, which is a property of the compiler that
// wrote the file rather than of the copybook — PIC S9(2) COMP is two bytes under
// IBM Enterprise COBOL and one under GnuCOBOL's default. It is the staircase the
// offsets in these records were computed under, so changing it here does not
// reinterpret the file, it describes a different one.
//
// It is a value a caller passes rather than one anything applies on its own. A
// file this descriptor describes that was converted to another character set is
// read by passing a different Encoding, not by regenerating.
func Encoding() codec.Encoding {
	return codec.Encoding{
		Charset:   codec.CP037(),
		Sign:      codec.SignEBCDIC,
		ByteOrder: binary.BigEndian,
		Float:     codec.FloatIEEE,
		Binary:    codec.BinarySize248,
	}
}

// Every record reads and writes itself, which is codec's Unmarshaler and
// Marshaler. Asserted here so that a drift in either interface fails in the
// file that implements it.
var (
	_ codec.Unmarshaler = (*LedgerHeader)(nil)
	_ codec.Marshaler   = (*LedgerHeader)(nil)
	_ codec.Unmarshaler = (*LedgerTrailer)(nil)
	_ codec.Marshaler   = (*LedgerTrailer)(nil)
	_ codec.Unmarshaler = (*DebitPosting)(nil)
	_ codec.Marshaler   = (*DebitPosting)(nil)
	_ codec.Unmarshaler = (*DebitPostingRef)(nil)
	_ codec.Marshaler   = (*DebitPostingRef)(nil)
	_ codec.Unmarshaler = (*CreditPosting)(nil)
	_ codec.Marshaler   = (*CreditPosting)(nil)
	_ codec.Unmarshaler = (*CreditPostingRef)(nil)
	_ codec.Marshaler   = (*CreditPostingRef)(nil)
	_ codec.Unmarshaler = (*MemoPosting)(nil)
	_ codec.Marshaler   = (*MemoPosting)(nil)
	_ codec.Unmarshaler = (*MemoPostingRef)(nil)
	_ codec.Marshaler   = (*MemoPostingRef)(nil)
)

// zeroFill is what a writer emits for a run of bytes a record its caller built
// rather than read carries none for: zero bytes, 8 of them at the most, sliced
// to the run's own width.
//
// Three kinds of run reach it. A slack node and an item the copybook gives no
// data-name hold bytes no program names. An item the layout says carries a
// payload rather than characters is a []byte a caller can name and set, and
// this is what it gets where they left it nil.
//
// Zero rather than a space, and the reason differs by run. Charset is a
// property of a field and slack is not a field, so there is no charset to
// resolve a space against and zero is the byte that names none. A FILLER is a
// field and does have one, and filling it with spaces would be choosing a value
// on behalf of a caller who never had one to give. A payload item has no pad
// byte that is not also a legal value of it — the space that pads a text item
// is a byte such an item may hold — so a writer handed nothing writes zeros
// rather than choosing a byte that could have been data.
//
// Those bytes were never in a file, so nothing is being overwritten — a record
// that was read carries the bytes it was read from and they are emitted
// instead. See docs/ir/SPEC.md, "What the descriptor determines, a writer
// supplies".
var zeroFill = make([]byte, 8)

// UnmarshalCOBOL reads one LEDGER-HEADER out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (p *LedgerHeader) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if p.HdrType, err = r.ReadAlphanumeric(2); err != nil {
		return fmt.Errorf("LEDGER-HEADER: reading HDR-TYPE: %w", err)
	}

	if p.HdrLedgerId, err = r.ReadAlphanumeric(10); err != nil {
		return fmt.Errorf("LEDGER-HEADER: reading HDR-LEDGER-ID: %w", err)
	}

	if p.HdrPeriod, err = r.ReadZonedInt32(6, codec.SignUnsigned); err != nil {
		return fmt.Errorf("LEDGER-HEADER: reading HDR-PERIOD: %w", err)
	}

	if p.HdrCurrency, err = r.ReadAlphanumeric(3); err != nil {
		return fmt.Errorf("LEDGER-HEADER: reading HDR-CURRENCY: %w", err)
	}

	if p.HdrCount, err = r.ReadZonedInt32(3, codec.SignUnsigned); err != nil {
		return fmt.Errorf("LEDGER-HEADER: reading HDR-COUNT: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this LEDGER-HEADER into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (p *LedgerHeader) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(p.HdrType, 2); err != nil {
		return fmt.Errorf("LEDGER-HEADER: writing HDR-TYPE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.HdrLedgerId, 10); err != nil {
		return fmt.Errorf("LEDGER-HEADER: writing HDR-LEDGER-ID: %w", err)
	}

	if err = w.WriteZonedInt32(p.HdrPeriod, 6, codec.SignUnsigned); err != nil {
		return fmt.Errorf("LEDGER-HEADER: writing HDR-PERIOD: %w", err)
	}

	if err = w.WriteAlphanumeric(p.HdrCurrency, 3); err != nil {
		return fmt.Errorf("LEDGER-HEADER: writing HDR-CURRENCY: %w", err)
	}

	if err = w.WriteZonedInt32(p.HdrCount, 3, codec.SignUnsigned); err != nil {
		return fmt.Errorf("LEDGER-HEADER: writing HDR-COUNT: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one LEDGER-TRAILER out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (p *LedgerTrailer) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if p.TrlType, err = r.ReadAlphanumeric(2); err != nil {
		return fmt.Errorf("LEDGER-TRAILER: reading TRL-TYPE: %w", err)
	}

	if p.TrlCount, err = r.ReadZonedInt32(6, codec.SignUnsigned); err != nil {
		return fmt.Errorf("LEDGER-TRAILER: reading TRL-COUNT: %w", err)
	}

	if p.TrlNet, err = r.ReadPackedInt64(15); err != nil {
		return fmt.Errorf("LEDGER-TRAILER: reading TRL-NET: %w", err)
	}

	if p.filler[0], err = r.ReadBytes(8); err != nil {
		return fmt.Errorf("LEDGER-TRAILER: reading the 8 bytes of an item the copybook gives no data-name: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this LEDGER-TRAILER into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (p *LedgerTrailer) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(p.TrlType, 2); err != nil {
		return fmt.Errorf("LEDGER-TRAILER: writing TRL-TYPE: %w", err)
	}

	if err = w.WriteZonedInt32(p.TrlCount, 6, codec.SignUnsigned); err != nil {
		return fmt.Errorf("LEDGER-TRAILER: writing TRL-COUNT: %w", err)
	}

	if err = w.WritePackedInt64(p.TrlNet, 15, codec.Signed); err != nil {
		return fmt.Errorf("LEDGER-TRAILER: writing TRL-NET: %w", err)
	}

	switch {
	case p.filler[0] == nil:
		if err = w.WriteBytes(zeroFill[:8]); err != nil {
			return fmt.Errorf("LEDGER-TRAILER: writing 8 zero bytes for an item the copybook gives no data-name and this record carries none for: %w", err)
		}
	case len(p.filler[0]) != 8:
		return fmt.Errorf("LEDGER-TRAILER: a writer reports a retained run rather than truncating or padding it, and the run for an item of 8 bytes the copybook gives no data-name is %d", len(p.filler[0]))
	default:
		if err = w.WriteBytes(p.filler[0]); err != nil {
			return fmt.Errorf("LEDGER-TRAILER: writing the 8 bytes of an item the copybook gives no data-name: %w", err)
		}
	}

	return nil
}

// UnmarshalCOBOL reads one POSTING-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (p *DebitPosting) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if p.PstAccount, err = r.ReadAlphanumeric(10); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-ACCOUNT: %w", err)
	}

	if p.PstSequence, err = r.ReadZonedInt32(2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-SEQUENCE: %w", err)
	}

	if p.PstType, err = r.ReadAlphanumeric(2); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TYPE: %w", err)
	}

	if p.PstDebit.PdbCostCentre, err = r.ReadAlphanumeric(6); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PDB-COST-CENTRE: %w", err)
	}

	if p.PstDebit.PdbAmount, err = r.ReadPackedInt64(13); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PDB-AMOUNT: %w", err)
	}

	if p.PstDebit.PdbMemo, err = r.ReadAlphanumeric(15); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PDB-MEMO: %w", err)
	}

	if p.PstTail, err = r.ReadAlphanumeric(8); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TAIL: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this POSTING-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (p *DebitPosting) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(p.PstAccount, 10); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-ACCOUNT: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstSequence, 2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-SEQUENCE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstType, 2); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TYPE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstDebit.PdbCostCentre, 6); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PDB-COST-CENTRE: %w", err)
	}

	if err = w.WritePackedInt64(p.PstDebit.PdbAmount, 13, codec.Signed); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PDB-AMOUNT: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstDebit.PdbMemo, 15); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PDB-MEMO: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstTail, 8); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TAIL: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one POSTING-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (p *DebitPostingRef) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if p.PstAccount, err = r.ReadAlphanumeric(10); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-ACCOUNT: %w", err)
	}

	if p.PstSequence, err = r.ReadZonedInt32(2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-SEQUENCE: %w", err)
	}

	if p.PstType, err = r.ReadAlphanumeric(2); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TYPE: %w", err)
	}

	if p.PstDebit.PdbCostCentre, err = r.ReadAlphanumeric(6); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PDB-COST-CENTRE: %w", err)
	}

	if p.PstDebit.PdbAmount, err = r.ReadPackedInt64(13); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PDB-AMOUNT: %w", err)
	}

	if p.PstDebit.PdbMemo, err = r.ReadAlphanumeric(15); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PDB-MEMO: %w", err)
	}

	if p.PstTailRef.PtrBatch, err = r.ReadZonedInt32(4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PTR-BATCH: %w", err)
	}

	if p.PstTailRef.PtrLine, err = r.ReadZonedInt32(4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PTR-LINE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this POSTING-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (p *DebitPostingRef) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(p.PstAccount, 10); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-ACCOUNT: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstSequence, 2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-SEQUENCE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstType, 2); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TYPE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstDebit.PdbCostCentre, 6); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PDB-COST-CENTRE: %w", err)
	}

	if err = w.WritePackedInt64(p.PstDebit.PdbAmount, 13, codec.Signed); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PDB-AMOUNT: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstDebit.PdbMemo, 15); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PDB-MEMO: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstTailRef.PtrBatch, 4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PTR-BATCH: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstTailRef.PtrLine, 4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PTR-LINE: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one POSTING-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (p *CreditPosting) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if p.PstAccount, err = r.ReadAlphanumeric(10); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-ACCOUNT: %w", err)
	}

	if p.PstSequence, err = r.ReadZonedInt32(2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-SEQUENCE: %w", err)
	}

	if p.PstType, err = r.ReadAlphanumeric(2); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TYPE: %w", err)
	}

	if p.PstCredit.PcrSource, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PCR-SOURCE: %w", err)
	}

	if p.PstCredit.PcrAmount, err = r.ReadPackedInt64(11); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PCR-AMOUNT: %w", err)
	}

	if p.PstCredit.PcrReference, err = r.ReadAlphanumeric(14); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PCR-REFERENCE: %w", err)
	}

	if p.slack[0], err = r.ReadBytes(4); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading the 4 bytes no item of it covers: %w", err)
	}

	if p.PstTail, err = r.ReadAlphanumeric(8); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TAIL: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this POSTING-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (p *CreditPosting) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(p.PstAccount, 10); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-ACCOUNT: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstSequence, 2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-SEQUENCE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstType, 2); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TYPE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstCredit.PcrSource, 4); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PCR-SOURCE: %w", err)
	}

	if err = w.WritePackedInt64(p.PstCredit.PcrAmount, 11, codec.Signed); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PCR-AMOUNT: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstCredit.PcrReference, 14); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PCR-REFERENCE: %w", err)
	}

	switch {
	case p.slack[0] == nil:
		if err = w.WriteBytes(zeroFill[:4]); err != nil {
			return fmt.Errorf("POSTING-RECORD: writing 4 zero bytes for slack this record carries none for: %w", err)
		}
	case len(p.slack[0]) != 4:
		return fmt.Errorf("POSTING-RECORD: a writer reports a retained run rather than truncating or padding it, and the run for a slack node of 4 bytes is %d", len(p.slack[0]))
	default:
		if err = w.WriteBytes(p.slack[0]); err != nil {
			return fmt.Errorf("POSTING-RECORD: writing the 4 bytes no item of it covers: %w", err)
		}
	}

	if err = w.WriteAlphanumeric(p.PstTail, 8); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TAIL: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one POSTING-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (p *CreditPostingRef) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if p.PstAccount, err = r.ReadAlphanumeric(10); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-ACCOUNT: %w", err)
	}

	if p.PstSequence, err = r.ReadZonedInt32(2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-SEQUENCE: %w", err)
	}

	if p.PstType, err = r.ReadAlphanumeric(2); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TYPE: %w", err)
	}

	if p.PstCredit.PcrSource, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PCR-SOURCE: %w", err)
	}

	if p.PstCredit.PcrAmount, err = r.ReadPackedInt64(11); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PCR-AMOUNT: %w", err)
	}

	if p.PstCredit.PcrReference, err = r.ReadAlphanumeric(14); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PCR-REFERENCE: %w", err)
	}

	if p.slack[0], err = r.ReadBytes(4); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading the 4 bytes no item of it covers: %w", err)
	}

	if p.PstTailRef.PtrBatch, err = r.ReadZonedInt32(4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PTR-BATCH: %w", err)
	}

	if p.PstTailRef.PtrLine, err = r.ReadZonedInt32(4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PTR-LINE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this POSTING-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (p *CreditPostingRef) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(p.PstAccount, 10); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-ACCOUNT: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstSequence, 2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-SEQUENCE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstType, 2); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TYPE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstCredit.PcrSource, 4); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PCR-SOURCE: %w", err)
	}

	if err = w.WritePackedInt64(p.PstCredit.PcrAmount, 11, codec.Signed); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PCR-AMOUNT: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstCredit.PcrReference, 14); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PCR-REFERENCE: %w", err)
	}

	switch {
	case p.slack[0] == nil:
		if err = w.WriteBytes(zeroFill[:4]); err != nil {
			return fmt.Errorf("POSTING-RECORD: writing 4 zero bytes for slack this record carries none for: %w", err)
		}
	case len(p.slack[0]) != 4:
		return fmt.Errorf("POSTING-RECORD: a writer reports a retained run rather than truncating or padding it, and the run for a slack node of 4 bytes is %d", len(p.slack[0]))
	default:
		if err = w.WriteBytes(p.slack[0]); err != nil {
			return fmt.Errorf("POSTING-RECORD: writing the 4 bytes no item of it covers: %w", err)
		}
	}

	if err = w.WriteZonedInt32(p.PstTailRef.PtrBatch, 4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PTR-BATCH: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstTailRef.PtrLine, 4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PTR-LINE: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one POSTING-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (p *MemoPosting) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if p.PstAccount, err = r.ReadAlphanumeric(10); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-ACCOUNT: %w", err)
	}

	if p.PstSequence, err = r.ReadZonedInt32(2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-SEQUENCE: %w", err)
	}

	if p.PstType, err = r.ReadAlphanumeric(2); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TYPE: %w", err)
	}

	if p.PstBody, err = r.ReadAlphanumeric(28); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-BODY: %w", err)
	}

	if p.PstTail, err = r.ReadAlphanumeric(8); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TAIL: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this POSTING-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (p *MemoPosting) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(p.PstAccount, 10); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-ACCOUNT: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstSequence, 2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-SEQUENCE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstType, 2); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TYPE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstBody, 28); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-BODY: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstTail, 8); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TAIL: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one POSTING-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (p *MemoPostingRef) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if p.PstAccount, err = r.ReadAlphanumeric(10); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-ACCOUNT: %w", err)
	}

	if p.PstSequence, err = r.ReadZonedInt32(2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-SEQUENCE: %w", err)
	}

	if p.PstType, err = r.ReadAlphanumeric(2); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-TYPE: %w", err)
	}

	if p.PstBody, err = r.ReadAlphanumeric(28); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PST-BODY: %w", err)
	}

	if p.PstTailRef.PtrBatch, err = r.ReadZonedInt32(4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PTR-BATCH: %w", err)
	}

	if p.PstTailRef.PtrLine, err = r.ReadZonedInt32(4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: reading PTR-LINE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this POSTING-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (p *MemoPostingRef) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(p.PstAccount, 10); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-ACCOUNT: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstSequence, 2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-SEQUENCE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstType, 2); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-TYPE: %w", err)
	}

	if err = w.WriteAlphanumeric(p.PstBody, 28); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PST-BODY: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstTailRef.PtrBatch, 4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PTR-BATCH: %w", err)
	}

	if err = w.WriteZonedInt32(p.PstTailRef.PtrLine, 4, codec.SignUnsigned); err != nil {
		return fmt.Errorf("POSTING-RECORD: writing PTR-LINE: %w", err)
	}

	return nil
}
