// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The record tier of this package's generated tests: one case per record the
// layout describes, and one per arm of an alternation inside one.
//
// Each case carries the bytes it reads as a literal, decodes them, checks every
// field against the value the literal was laid out with, and writes the record
// back out byte for byte. The bytes are synthesized from the layout rather than
// read from a file, so they are what to hold against the file on your desk: the
// comment column names the item, the offset summed from the widths ahead of it,
// and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports ledger.
package ledger_test

import (
	"bytes"
	"github.com/Zaba505/cobol-go/codec"
	"github.com/Zaba505/cpybkc/example/ledger"
	"testing"
)

// TestLedgerHeaderReadsBackTheBytesItWasReadFrom is LEDGER-HEADER: the bytes
// below, every field they decode into, and the same bytes written back.
func TestLedgerHeaderReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xf0, 0xf1, // HDR-TYPE @0 X(2)
		0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, // HDR-LEDGER-ID @2 X(10)
		0xc3, 0xc3, //
		0xf0, 0xf0, 0xf0, 0xf0, 0xf1, 0xf3, // HDR-PERIOD @12 9(6)
		0xe2, 0xe2, 0xe2, // HDR-CURRENCY @18 X(3)
		0xf0, 0xf2, 0xf2, // HDR-COUNT @21 9(3)
	}

	r, err := codec.NewReader(bytes.NewReader(in), ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record ledger.LedgerHeader

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.HdrType != "01" {
		t.Errorf("HDR-TYPE: got %q, want %q", record.HdrType, "01")
	}

	if record.HdrLedgerId != "CCCCCCCCCC" {
		t.Errorf("HDR-LEDGER-ID: got %q, want %q", record.HdrLedgerId, "CCCCCCCCCC")
	}

	if record.HdrPeriod != 13 {
		t.Errorf("HDR-PERIOD: got %d, want %d", record.HdrPeriod, 13)
	}

	if record.HdrCurrency != "SSS" {
		t.Errorf("HDR-CURRENCY: got %q, want %q", record.HdrCurrency, "SSS")
	}

	if record.HdrCount != 22 {
		t.Errorf("HDR-COUNT: got %d, want %d", record.HdrCount, 22)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestLedgerTrailerReadsBackTheBytesItWasReadFrom is LEDGER-TRAILER: the bytes
// below, every field they decode into, and the same bytes written back.
func TestLedgerTrailerReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xf9, 0xf9, // TRL-TYPE @0 X(2)
		0xf0, 0xf0, 0xf0, 0xf0, 0xf0, 0xf3, // TRL-COUNT @2 9(6)
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9d, // TRL-NET @8 S9(13)V9(2) PACKED-DECIMAL
		0xb0, 0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, // FILLER @16 X(8)
	}

	r, err := codec.NewReader(bytes.NewReader(in), ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record ledger.LedgerTrailer

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.TrlType != "99" {
		t.Errorf("TRL-TYPE: got %q, want %q", record.TrlType, "99")
	}

	if record.TrlCount != 3 {
		t.Errorf("TRL-COUNT: got %d, want %d", record.TrlCount, 3)
	}

	if record.TrlNet != -9 {
		t.Errorf("TRL-NET: got %d, want %d", record.TrlNet, -9)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestDebitPostingReadsBackTheBytesItWasReadFrom is POSTING-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestDebitPostingReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // PST-ACCOUNT @0 X(10)
		0xc1, 0xc1, //
		0xf1, 0xf1, // PST-SEQUENCE @10 9(2)
		0xc4, 0xc1, // PST-TYPE @12 X(2)
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // PST-DEBIT.PDB-COST-CENTRE @14 X(6)
		0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x1d, // PST-DEBIT.PDB-AMOUNT @20 S9(11)V9(2) PACKED-DECIMAL
		0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, // PST-DEBIT.PDB-MEMO @27 X(15)
		0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, //
		0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, // PST-TAIL @42 X(8)
	}

	r, err := codec.NewReader(bytes.NewReader(in), ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record ledger.DebitPosting

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.PstAccount != "AAAAAAAAAA" {
		t.Errorf("PST-ACCOUNT: got %q, want %q", record.PstAccount, "AAAAAAAAAA")
	}

	if record.PstSequence != 11 {
		t.Errorf("PST-SEQUENCE: got %d, want %d", record.PstSequence, 11)
	}

	if record.PstType != "DA" {
		t.Errorf("PST-TYPE: got %q, want %q", record.PstType, "DA")
	}

	if record.PstDebit.PdbCostCentre != "OOOOOO" {
		t.Errorf("PST-DEBIT.PDB-COST-CENTRE: got %q, want %q", record.PstDebit.PdbCostCentre, "OOOOOO")
	}

	if record.PstDebit.PdbAmount != -21 {
		t.Errorf("PST-DEBIT.PDB-AMOUNT: got %d, want %d", record.PstDebit.PdbAmount, -21)
	}

	if record.PstDebit.PdbMemo != "BBBBBBBBBBBBBBB" {
		t.Errorf("PST-DEBIT.PDB-MEMO: got %q, want %q", record.PstDebit.PdbMemo, "BBBBBBBBBBBBBBB")
	}

	if record.PstTail != "QQQQQQQQ" {
		t.Errorf("PST-TAIL: got %q, want %q", record.PstTail, "QQQQQQQQ")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestDebitPostingRefReadsBackTheBytesItWasReadFrom is POSTING-RECORD: the
// bytes below, every field they decode into, and the same bytes written back.
func TestDebitPostingRefReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // PST-ACCOUNT @0 X(10)
		0xc1, 0xc1, //
		0xf1, 0xf1, // PST-SEQUENCE @10 9(2)
		0xc4, 0xc2, // PST-TYPE @12 X(2)
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // PST-DEBIT.PDB-COST-CENTRE @14 X(6)
		0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x1d, // PST-DEBIT.PDB-AMOUNT @20 S9(11)V9(2) PACKED-DECIMAL
		0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, // PST-DEBIT.PDB-MEMO @27 X(15)
		0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, 0xc2, //
		0xf0, 0xf0, 0xf4, 0xf3, // PST-TAIL-REF.PTR-BATCH @42 9(4)
		0xf0, 0xf0, 0xf4, 0xf7, // PST-TAIL-REF.PTR-LINE @46 9(4)
	}

	r, err := codec.NewReader(bytes.NewReader(in), ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record ledger.DebitPostingRef

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.PstAccount != "AAAAAAAAAA" {
		t.Errorf("PST-ACCOUNT: got %q, want %q", record.PstAccount, "AAAAAAAAAA")
	}

	if record.PstSequence != 11 {
		t.Errorf("PST-SEQUENCE: got %d, want %d", record.PstSequence, 11)
	}

	if record.PstType != "DB" {
		t.Errorf("PST-TYPE: got %q, want %q", record.PstType, "DB")
	}

	if record.PstDebit.PdbCostCentre != "OOOOOO" {
		t.Errorf("PST-DEBIT.PDB-COST-CENTRE: got %q, want %q", record.PstDebit.PdbCostCentre, "OOOOOO")
	}

	if record.PstDebit.PdbAmount != -21 {
		t.Errorf("PST-DEBIT.PDB-AMOUNT: got %d, want %d", record.PstDebit.PdbAmount, -21)
	}

	if record.PstDebit.PdbMemo != "BBBBBBBBBBBBBBB" {
		t.Errorf("PST-DEBIT.PDB-MEMO: got %q, want %q", record.PstDebit.PdbMemo, "BBBBBBBBBBBBBBB")
	}

	if record.PstTailRef.PtrBatch != 43 {
		t.Errorf("PST-TAIL-REF.PTR-BATCH: got %d, want %d", record.PstTailRef.PtrBatch, 43)
	}

	if record.PstTailRef.PtrLine != 47 {
		t.Errorf("PST-TAIL-REF.PTR-LINE: got %d, want %d", record.PstTailRef.PtrLine, 47)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestCreditPostingReadsBackTheBytesItWasReadFrom is POSTING-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestCreditPostingReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // PST-ACCOUNT @0 X(10)
		0xc1, 0xc1, //
		0xf1, 0xf1, // PST-SEQUENCE @10 9(2)
		0xc3, 0xc1, // PST-TYPE @12 X(2)
		0xd6, 0xd6, 0xd6, 0xd6, // PST-CREDIT.PCR-SOURCE @14 X(4)
		0x00, 0x00, 0x00, 0x00, 0x01, 0x9d, // PST-CREDIT.PCR-AMOUNT @18 S9(9)V9(2) PACKED-DECIMAL
		0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, // PST-CREDIT.PCR-REFERENCE @24 X(14)
		0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, //
		0xc6, 0xc7, 0xc8, 0xc9, // (slack) @38 4 bytes no item covers
		0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, // PST-TAIL @42 X(8)
	}

	r, err := codec.NewReader(bytes.NewReader(in), ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record ledger.CreditPosting

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.PstAccount != "AAAAAAAAAA" {
		t.Errorf("PST-ACCOUNT: got %q, want %q", record.PstAccount, "AAAAAAAAAA")
	}

	if record.PstSequence != 11 {
		t.Errorf("PST-SEQUENCE: got %d, want %d", record.PstSequence, 11)
	}

	if record.PstType != "CA" {
		t.Errorf("PST-TYPE: got %q, want %q", record.PstType, "CA")
	}

	if record.PstCredit.PcrSource != "OOOO" {
		t.Errorf("PST-CREDIT.PCR-SOURCE: got %q, want %q", record.PstCredit.PcrSource, "OOOO")
	}

	if record.PstCredit.PcrAmount != -19 {
		t.Errorf("PST-CREDIT.PCR-AMOUNT: got %d, want %d", record.PstCredit.PcrAmount, -19)
	}

	if record.PstCredit.PcrReference != "YYYYYYYYYYYYYY" {
		t.Errorf("PST-CREDIT.PCR-REFERENCE: got %q, want %q", record.PstCredit.PcrReference, "YYYYYYYYYYYYYY")
	}

	if record.PstTail != "QQQQQQQQ" {
		t.Errorf("PST-TAIL: got %q, want %q", record.PstTail, "QQQQQQQQ")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestCreditPostingRefReadsBackTheBytesItWasReadFrom is POSTING-RECORD: the
// bytes below, every field they decode into, and the same bytes written back.
func TestCreditPostingRefReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // PST-ACCOUNT @0 X(10)
		0xc1, 0xc1, //
		0xf1, 0xf1, // PST-SEQUENCE @10 9(2)
		0xc3, 0xc2, // PST-TYPE @12 X(2)
		0xd6, 0xd6, 0xd6, 0xd6, // PST-CREDIT.PCR-SOURCE @14 X(4)
		0x00, 0x00, 0x00, 0x00, 0x01, 0x9d, // PST-CREDIT.PCR-AMOUNT @18 S9(9)V9(2) PACKED-DECIMAL
		0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, // PST-CREDIT.PCR-REFERENCE @24 X(14)
		0xe8, 0xe8, 0xe8, 0xe8, 0xe8, 0xe8, //
		0xc6, 0xc7, 0xc8, 0xc9, // (slack) @38 4 bytes no item covers
		0xf0, 0xf0, 0xf4, 0xf3, // PST-TAIL-REF.PTR-BATCH @42 9(4)
		0xf0, 0xf0, 0xf4, 0xf7, // PST-TAIL-REF.PTR-LINE @46 9(4)
	}

	r, err := codec.NewReader(bytes.NewReader(in), ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record ledger.CreditPostingRef

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.PstAccount != "AAAAAAAAAA" {
		t.Errorf("PST-ACCOUNT: got %q, want %q", record.PstAccount, "AAAAAAAAAA")
	}

	if record.PstSequence != 11 {
		t.Errorf("PST-SEQUENCE: got %d, want %d", record.PstSequence, 11)
	}

	if record.PstType != "CB" {
		t.Errorf("PST-TYPE: got %q, want %q", record.PstType, "CB")
	}

	if record.PstCredit.PcrSource != "OOOO" {
		t.Errorf("PST-CREDIT.PCR-SOURCE: got %q, want %q", record.PstCredit.PcrSource, "OOOO")
	}

	if record.PstCredit.PcrAmount != -19 {
		t.Errorf("PST-CREDIT.PCR-AMOUNT: got %d, want %d", record.PstCredit.PcrAmount, -19)
	}

	if record.PstCredit.PcrReference != "YYYYYYYYYYYYYY" {
		t.Errorf("PST-CREDIT.PCR-REFERENCE: got %q, want %q", record.PstCredit.PcrReference, "YYYYYYYYYYYYYY")
	}

	if record.PstTailRef.PtrBatch != 43 {
		t.Errorf("PST-TAIL-REF.PTR-BATCH: got %d, want %d", record.PstTailRef.PtrBatch, 43)
	}

	if record.PstTailRef.PtrLine != 47 {
		t.Errorf("PST-TAIL-REF.PTR-LINE: got %d, want %d", record.PstTailRef.PtrLine, 47)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestMemoPostingReadsBackTheBytesItWasReadFrom is POSTING-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestMemoPostingReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // PST-ACCOUNT @0 X(10)
		0xc1, 0xc1, //
		0xf1, 0xf1, // PST-SEQUENCE @10 9(2)
		0xd4, 0xc1, // PST-TYPE @12 X(2)
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // PST-BODY @14 X(28)
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, //
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, //
		0xd6, 0xd6, 0xd6, 0xd6, //
		0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, 0xd8, // PST-TAIL @42 X(8)
	}

	r, err := codec.NewReader(bytes.NewReader(in), ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record ledger.MemoPosting

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.PstAccount != "AAAAAAAAAA" {
		t.Errorf("PST-ACCOUNT: got %q, want %q", record.PstAccount, "AAAAAAAAAA")
	}

	if record.PstSequence != 11 {
		t.Errorf("PST-SEQUENCE: got %d, want %d", record.PstSequence, 11)
	}

	if record.PstType != "MA" {
		t.Errorf("PST-TYPE: got %q, want %q", record.PstType, "MA")
	}

	if record.PstBody != "OOOOOOOOOOOOOOOOOOOOOOOOOOOO" {
		t.Errorf("PST-BODY: got %q, want %q", record.PstBody, "OOOOOOOOOOOOOOOOOOOOOOOOOOOO")
	}

	if record.PstTail != "QQQQQQQQ" {
		t.Errorf("PST-TAIL: got %q, want %q", record.PstTail, "QQQQQQQQ")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestMemoPostingRefReadsBackTheBytesItWasReadFrom is POSTING-RECORD: the
// bytes below, every field they decode into, and the same bytes written back.
func TestMemoPostingRefReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // PST-ACCOUNT @0 X(10)
		0xc1, 0xc1, //
		0xf1, 0xf1, // PST-SEQUENCE @10 9(2)
		0xd4, 0xc2, // PST-TYPE @12 X(2)
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // PST-BODY @14 X(28)
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, //
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, //
		0xd6, 0xd6, 0xd6, 0xd6, //
		0xf0, 0xf0, 0xf4, 0xf3, // PST-TAIL-REF.PTR-BATCH @42 9(4)
		0xf0, 0xf0, 0xf4, 0xf7, // PST-TAIL-REF.PTR-LINE @46 9(4)
	}

	r, err := codec.NewReader(bytes.NewReader(in), ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record ledger.MemoPostingRef

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.PstAccount != "AAAAAAAAAA" {
		t.Errorf("PST-ACCOUNT: got %q, want %q", record.PstAccount, "AAAAAAAAAA")
	}

	if record.PstSequence != 11 {
		t.Errorf("PST-SEQUENCE: got %d, want %d", record.PstSequence, 11)
	}

	if record.PstType != "MB" {
		t.Errorf("PST-TYPE: got %q, want %q", record.PstType, "MB")
	}

	if record.PstBody != "OOOOOOOOOOOOOOOOOOOOOOOOOOOO" {
		t.Errorf("PST-BODY: got %q, want %q", record.PstBody, "OOOOOOOOOOOOOOOOOOOOOOOOOOOO")
	}

	if record.PstTailRef.PtrBatch != 43 {
		t.Errorf("PST-TAIL-REF.PTR-BATCH: got %d, want %d", record.PstTailRef.PtrBatch, 43)
	}

	if record.PstTailRef.PtrLine != 47 {
		t.Errorf("PST-TAIL-REF.PTR-LINE: got %d, want %d", record.PstTailRef.PtrLine, 47)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, ledger.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
