// Code generated by cpybkc-gen-go. DO NOT EDIT.

package ledger

// LedgerHeader is the LEDGER-HEADER record, as docs/ir/SPEC.md resolved it.
type LedgerHeader struct {
	// HdrType is HDR-TYPE — alphanumeric, DISPLAY, 2 bytes.
	HdrType string

	// HdrLedgerId is HDR-LEDGER-ID — alphanumeric, DISPLAY, 10 bytes.
	HdrLedgerId string

	// HdrPeriod is HDR-PERIOD — numeric, DISPLAY, 6 digits, unsigned, 6 bytes.
	HdrPeriod int32

	// HdrCurrency is HDR-CURRENCY — alphanumeric, DISPLAY, 3 bytes.
	HdrCurrency string

	// HdrCount is HDR-COUNT — numeric, DISPLAY, 3 digits, unsigned, 3 bytes.
	HdrCount int32
}

// LedgerTrailer is the LEDGER-TRAILER record, as docs/ir/SPEC.md resolved it.
type LedgerTrailer struct {
	// TrlType is TRL-TYPE — alphanumeric, DISPLAY, 2 bytes.
	TrlType string

	// TrlCount is TRL-COUNT — numeric, DISPLAY, 6 digits, unsigned, 6 bytes.
	TrlCount int32

	// TrlNet is TRL-NET — numeric, PACKED-DECIMAL, 15 digits, signed, 8 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	TrlNet int64

	// filler is the bytes of the items among this item's members that the
	// copybook gives no data-name — its FILLER — in the order they occupy the
	// record: one run each, as they stood when the record was read, and one set
	// of them per occurrence of this struct. A nil run is one the record does
	// not carry; an empty run is a run of no bytes, and the two are not the
	// same.
	//
	// A FILLER is an item, and it is one no program names: it holds no value a
	// caller of this package could set and none it could read. So it travels
	// with the record and there is nothing here for a caller to do. An item you
	// do want to read or write is one to give a data-name in the copybook,
	// which makes it a field like any other.
	filler [1][]byte
}

// DebitPosting is the POSTING-RECORD record, as docs/ir/SPEC.md resolved it.
// The layout renames it to DEBIT-POSTING.
type DebitPosting struct {
	// PstAccount is PST-ACCOUNT — alphanumeric, DISPLAY, 10 bytes.
	PstAccount string

	// PstSequence is PST-SEQUENCE — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	PstSequence int32

	// PstType is PST-TYPE — alphanumeric, DISPLAY, 2 bytes.
	PstType string

	// PstDebit is PST-DEBIT — a group of 3 members.
	PstDebit struct {
		// PdbCostCentre is PDB-COST-CENTRE — alphanumeric, DISPLAY, 6 bytes.
		PdbCostCentre string

		// PdbAmount is PDB-AMOUNT — numeric, PACKED-DECIMAL, 13 digits, signed, 7 bytes.
		// The value is unscaled: the item's value is this field times 10^-2.
		PdbAmount int64

		// PdbMemo is PDB-MEMO — alphanumeric, DISPLAY, 15 bytes.
		PdbMemo string
	}

	// PstTail is PST-TAIL — alphanumeric, DISPLAY, 8 bytes.
	PstTail string
}

// DebitPostingRef is the POSTING-RECORD record, as docs/ir/SPEC.md resolved it.
// The layout renames it to DEBIT-POSTING-REF.
type DebitPostingRef struct {
	// PstAccount is PST-ACCOUNT — alphanumeric, DISPLAY, 10 bytes.
	PstAccount string

	// PstSequence is PST-SEQUENCE — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	PstSequence int32

	// PstType is PST-TYPE — alphanumeric, DISPLAY, 2 bytes.
	PstType string

	// PstDebit is PST-DEBIT — a group of 3 members.
	PstDebit struct {
		// PdbCostCentre is PDB-COST-CENTRE — alphanumeric, DISPLAY, 6 bytes.
		PdbCostCentre string

		// PdbAmount is PDB-AMOUNT — numeric, PACKED-DECIMAL, 13 digits, signed, 7 bytes.
		// The value is unscaled: the item's value is this field times 10^-2.
		PdbAmount int64

		// PdbMemo is PDB-MEMO — alphanumeric, DISPLAY, 15 bytes.
		PdbMemo string
	}

	// PstTailRef is PST-TAIL-REF — a group of 2 members.
	PstTailRef struct {
		// PtrBatch is PTR-BATCH — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
		PtrBatch int32

		// PtrLine is PTR-LINE — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
		PtrLine int32
	}
}

// CreditPosting is the POSTING-RECORD record, as docs/ir/SPEC.md resolved it.
// The layout renames it to CREDIT-POSTING.
type CreditPosting struct {
	// PstAccount is PST-ACCOUNT — alphanumeric, DISPLAY, 10 bytes.
	PstAccount string

	// PstSequence is PST-SEQUENCE — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	PstSequence int32

	// PstType is PST-TYPE — alphanumeric, DISPLAY, 2 bytes.
	PstType string

	// PstCredit is PST-CREDIT — a group of 3 members.
	PstCredit struct {
		// PcrSource is PCR-SOURCE — alphanumeric, DISPLAY, 4 bytes.
		PcrSource string

		// PcrAmount is PCR-AMOUNT — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
		// The value is unscaled: the item's value is this field times 10^-2.
		PcrAmount int64

		// PcrReference is PCR-REFERENCE — alphanumeric, DISPLAY, 14 bytes.
		PcrReference string
	}

	// PstTail is PST-TAIL — alphanumeric, DISPLAY, 8 bytes.
	PstTail string

	// slack is the bytes retained for the slack nodes among this item's
	// members, in the order those nodes occupy the record: one run each, as
	// they stood when the record was read, and one set of them per occurrence
	// of this struct. A nil run is one the record does not carry; an empty run
	// is a run of no bytes, and the two are not the same.
	//
	// They travel with the record and there is nothing here for a caller to do.
	// See docs/ir/SPEC.md, "Slack survives a read".
	slack [1][]byte
}

// CreditPostingRef is the POSTING-RECORD record, as docs/ir/SPEC.md resolved it.
// The layout renames it to CREDIT-POSTING-REF.
type CreditPostingRef struct {
	// PstAccount is PST-ACCOUNT — alphanumeric, DISPLAY, 10 bytes.
	PstAccount string

	// PstSequence is PST-SEQUENCE — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	PstSequence int32

	// PstType is PST-TYPE — alphanumeric, DISPLAY, 2 bytes.
	PstType string

	// PstCredit is PST-CREDIT — a group of 3 members.
	PstCredit struct {
		// PcrSource is PCR-SOURCE — alphanumeric, DISPLAY, 4 bytes.
		PcrSource string

		// PcrAmount is PCR-AMOUNT — numeric, PACKED-DECIMAL, 11 digits, signed, 6 bytes.
		// The value is unscaled: the item's value is this field times 10^-2.
		PcrAmount int64

		// PcrReference is PCR-REFERENCE — alphanumeric, DISPLAY, 14 bytes.
		PcrReference string
	}

	// PstTailRef is PST-TAIL-REF — a group of 2 members.
	PstTailRef struct {
		// PtrBatch is PTR-BATCH — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
		PtrBatch int32

		// PtrLine is PTR-LINE — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
		PtrLine int32
	}

	// slack is the bytes retained for the slack nodes among this item's
	// members, in the order those nodes occupy the record: one run each, as
	// they stood when the record was read, and one set of them per occurrence
	// of this struct. A nil run is one the record does not carry; an empty run
	// is a run of no bytes, and the two are not the same.
	//
	// They travel with the record and there is nothing here for a caller to do.
	// See docs/ir/SPEC.md, "Slack survives a read".
	slack [1][]byte
}

// MemoPosting is the POSTING-RECORD record, as docs/ir/SPEC.md resolved it.
// The layout renames it to MEMO-POSTING.
type MemoPosting struct {
	// PstAccount is PST-ACCOUNT — alphanumeric, DISPLAY, 10 bytes.
	PstAccount string

	// PstSequence is PST-SEQUENCE — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	PstSequence int32

	// PstType is PST-TYPE — alphanumeric, DISPLAY, 2 bytes.
	PstType string

	// PstBody is PST-BODY — alphanumeric, DISPLAY, 28 bytes.
	PstBody string

	// PstTail is PST-TAIL — alphanumeric, DISPLAY, 8 bytes.
	PstTail string
}

// MemoPostingRef is the POSTING-RECORD record, as docs/ir/SPEC.md resolved it.
// The layout renames it to MEMO-POSTING-REF.
type MemoPostingRef struct {
	// PstAccount is PST-ACCOUNT — alphanumeric, DISPLAY, 10 bytes.
	PstAccount string

	// PstSequence is PST-SEQUENCE — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	PstSequence int32

	// PstType is PST-TYPE — alphanumeric, DISPLAY, 2 bytes.
	PstType string

	// PstBody is PST-BODY — alphanumeric, DISPLAY, 28 bytes.
	PstBody string

	// PstTailRef is PST-TAIL-REF — a group of 2 members.
	PstTailRef struct {
		// PtrBatch is PTR-BATCH — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
		PtrBatch int32

		// PtrLine is PTR-LINE — numeric, DISPLAY, 4 digits, unsigned, 4 bytes.
		PtrLine int32
	}
}
