// Code generated by cpybkc-gen-go. DO NOT EDIT.

package opt

// LineRecord is the LINE-RECORD record, as docs/ir/SPEC.md resolved it.
type LineRecord struct {
	// LineText is LINE-TEXT — alphanumeric, DISPLAY, 5 bytes.
	LineText string

	// LineAmount is LINE-AMOUNT — numeric, PACKED-DECIMAL, 5 digits, signed, 3 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	LineAmount int32
}
