// Code generated by cpybkc-gen-go. DO NOT EDIT.

package fixed

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
)

// Encoding is the byte-level interpretation of the files these records live in:
// the five axes as they were resolved — four the layout declared, and the binary
// width staircase the copybook's items were laid out under.
//
// None of the five has a default and every one of them fails silently when
// wrong, so codec has no usable zero-value Reader and this function is how a
// caller states all five at once:
//
//	r, err := codec.NewReader(f, Encoding())
//
// Binary is the odd one. The other four say how a byte becomes a value; this one
// says how many bytes a COMP item is, which is a property of the compiler that
// wrote the file rather than of the copybook — PIC S9(2) COMP is two bytes under
// IBM Enterprise COBOL and one under GnuCOBOL's default. It is the staircase the
// offsets in these records were computed under, so changing it here does not
// reinterpret the file, it describes a different one.
//
// It is a value a caller passes rather than one anything applies on its own. A
// file this descriptor describes that was converted to another character set is
// read by passing a different Encoding, not by regenerating.
func Encoding() codec.Encoding {
	return codec.Encoding{
		Charset:   codec.CP037(),
		Sign:      codec.SignEBCDIC,
		ByteOrder: binary.BigEndian,
		Float:     codec.FloatHFP,
		Binary:    codec.BinarySize248,
	}
}

// Every record reads and writes itself, which is codec's Unmarshaler and
// Marshaler. Asserted here so that a drift in either interface fails in the
// file that implements it.
var (
	_ codec.Unmarshaler = (*LedgerRecord)(nil)
	_ codec.Marshaler   = (*LedgerRecord)(nil)
)

// zeroFill is what a writer emits for a run of bytes a record its caller built
// rather than read carries none for: zero bytes, 6 of them at the most, sliced
// to the run's own width.
//
// Three kinds of run reach it. A slack node and an item the copybook gives no
// data-name hold bytes no program names. An item the layout says carries a
// payload rather than characters is a []byte a caller can name and set, and
// this is what it gets where they left it nil.
//
// Zero rather than a space, and the reason differs by run. Charset is a
// property of a field and slack is not a field, so there is no charset to
// resolve a space against and zero is the byte that names none. A FILLER is a
// field and does have one, and filling it with spaces would be choosing a value
// on behalf of a caller who never had one to give. A payload item has no pad
// byte that is not also a legal value of it — the space that pads a text item
// is a byte such an item may hold — so a writer handed nothing writes zeros
// rather than choosing a byte that could have been data.
//
// Those bytes were never in a file, so nothing is being overwritten — a record
// that was read carries the bytes it was read from and they are emitted
// instead. See docs/ir/SPEC.md, "What the descriptor determines, a writer
// supplies".
var zeroFill = make([]byte, 6)

// fresh is a zeroed arm to decode into, reusing the one the record already holds
// where it holds one.
//
// It exists for the reason resized does: an arm's body is an anonymous struct type,
// so there is no name for a new to take, and the pointer's own type is what
// supplies it.
func fresh[T any](p *T) *T {
	if p != nil {
		var zero T
		*p = zero

		return p
	}

	return new(T)
}

// UnmarshalCOBOL reads one LEDGER-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *LedgerRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.LedgerId, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("LEDGER-RECORD: reading LEDGER-ID: %w", err)
	}

	for i0 := range x.Entry {
		var occurrence1 []byte
		if occurrence1, err = r.ReadBytes(7); err != nil {
			return fmt.Errorf("LEDGER-RECORD: reading its bytes in occurrence %d of ENTRY: %w", i0, err)
		}
		var entry1 *codec.Reader
		if entry1, err = codec.NewReader(bytes.NewReader(occurrence1), r.Encoding()); err != nil {
			return fmt.Errorf("LEDGER-RECORD: reading over its bytes in occurrence %d of ENTRY: %w", i0, err)
		}
		if x.Entry[i0].EntryType, err = entry1.ReadAlphanumeric(1); err != nil {
			return fmt.Errorf("LEDGER-RECORD: reading ENTRY-TYPE in occurrence %d of ENTRY: %w", i0, err)
		}

		switch {
		case bytes.Equal(occurrence1[0:1], []byte("\xc4")):
			x.Entry[i0].EntryDetail = fresh(x.Entry[i0].EntryDetail)
			x.Entry[i0].EntrySummary = nil
			if x.Entry[i0].EntryDetail.DetailSku, err = entry1.ReadAlphanumeric(4); err != nil {
				return fmt.Errorf("LEDGER-RECORD: reading DETAIL-SKU in occurrence %d of ENTRY: %w", i0, err)
			}

			if x.Entry[i0].EntryDetail.DetailQty, err = entry1.ReadBinaryInt16(4); err != nil {
				return fmt.Errorf("LEDGER-RECORD: reading DETAIL-QTY in occurrence %d of ENTRY: %w", i0, err)
			}
		case bytes.Equal(occurrence1[0:1], []byte("\xe2")):
			x.Entry[i0].EntrySummary = fresh(x.Entry[i0].EntrySummary)
			x.Entry[i0].EntryDetail = nil
			if x.Entry[i0].EntrySummary.SummaryText, err = entry1.ReadAlphanumeric(4); err != nil {
				return fmt.Errorf("LEDGER-RECORD: reading SUMMARY-TEXT in occurrence %d of ENTRY: %w", i0, err)
			}

			if x.Entry[i0].EntrySummary.slack[0], err = entry1.ReadBytes(2); err != nil {
				return fmt.Errorf("LEDGER-RECORD: reading the 2 bytes no item of it covers in occurrence %d of ENTRY: %w", i0, err)
			}
		default:
			return fmt.Errorf("LEDGER-RECORD: the record type is one the layout describes and no arm of the alternation over ENTRY-DETAIL matches the entry in occurrence %d of ENTRY", i0)
		}
	}

	if x.slack[0], err = r.ReadBytes(6); err != nil {
		return fmt.Errorf("LEDGER-RECORD: reading the 6 bytes no item of it covers: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this LEDGER-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *LedgerRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(x.LedgerId, 4); err != nil {
		return fmt.Errorf("LEDGER-RECORD: writing LEDGER-ID: %w", err)
	}

	for i0 := range x.Entry {
		var occurrence1 bytes.Buffer
		var entry1 *codec.Writer
		if entry1, err = codec.NewWriter(&occurrence1, w.Encoding()); err != nil {
			return fmt.Errorf("LEDGER-RECORD: writing over its bytes in occurrence %d of ENTRY: %w", i0, err)
		}
		if err = entry1.WriteAlphanumeric(x.Entry[i0].EntryType, 1); err != nil {
			return fmt.Errorf("LEDGER-RECORD: writing ENTRY-TYPE in occurrence %d of ENTRY: %w", i0, err)
		}

		switch {
		case x.Entry[i0].EntryDetail != nil:
			if err = entry1.WriteAlphanumeric(x.Entry[i0].EntryDetail.DetailSku, 4); err != nil {
				return fmt.Errorf("LEDGER-RECORD: writing DETAIL-SKU in occurrence %d of ENTRY: %w", i0, err)
			}

			if err = entry1.WriteBinaryInt16(x.Entry[i0].EntryDetail.DetailQty, 4, codec.Signed); err != nil {
				return fmt.Errorf("LEDGER-RECORD: writing DETAIL-QTY in occurrence %d of ENTRY: %w", i0, err)
			}
		case x.Entry[i0].EntrySummary != nil:
			if err = entry1.WriteAlphanumeric(x.Entry[i0].EntrySummary.SummaryText, 4); err != nil {
				return fmt.Errorf("LEDGER-RECORD: writing SUMMARY-TEXT in occurrence %d of ENTRY: %w", i0, err)
			}

			switch {
			case x.Entry[i0].EntrySummary.slack[0] == nil:
				if err = entry1.WriteBytes(zeroFill[:2]); err != nil {
					return fmt.Errorf("LEDGER-RECORD: writing 2 zero bytes for slack this record carries none for in occurrence %d of ENTRY: %w", i0, err)
				}
			case len(x.Entry[i0].EntrySummary.slack[0]) != 2:
				return fmt.Errorf("LEDGER-RECORD: a writer reports a retained run rather than truncating or padding it, and the run for a slack node of 2 bytes is %d in occurrence %d of ENTRY", len(x.Entry[i0].EntrySummary.slack[0]), i0)
			default:
				if err = entry1.WriteBytes(x.Entry[i0].EntrySummary.slack[0]); err != nil {
					return fmt.Errorf("LEDGER-RECORD: writing the 2 bytes no item of it covers in occurrence %d of ENTRY: %w", i0, err)
				}
			}
		default:
			return fmt.Errorf("LEDGER-RECORD: an occurrence holds exactly one arm of the alternation over ENTRY-DETAIL and this one holds none in occurrence %d of ENTRY", i0)
		}
		matched1, holds1 := -1, -1
		switch {
		case bytes.Equal(occurrence1.Bytes()[0:1], []byte("\xc4")):
			matched1 = 0
		case bytes.Equal(occurrence1.Bytes()[0:1], []byte("\xe2")):
			matched1 = 1
		}
		switch {
		case x.Entry[i0].EntryDetail != nil:
			holds1 = 0
		case x.Entry[i0].EntrySummary != nil:
			holds1 = 1
		}
		if matched1 < 0 {
			return fmt.Errorf("LEDGER-RECORD: a writer reports an occurrence satisfying no arm's predicate rather than emitting it, and none of the alternation over ENTRY-DETAIL is satisfied in occurrence %d of ENTRY", i0)
		}
		if matched1 != holds1 {
			return fmt.Errorf("LEDGER-RECORD: a writer evaluates the predicate of the arm its caller supplied and never derives a value satisfying one, and this occurrence holds arm %d of the alternation over ENTRY-DETAIL while its values satisfy the predicate of arm %d in occurrence %d of ENTRY", holds1, matched1, i0)
		}
		if err = w.WriteBytes(occurrence1.Bytes()); err != nil {
			return fmt.Errorf("LEDGER-RECORD: writing its bytes in occurrence %d of ENTRY: %w", i0, err)
		}
	}

	switch {
	case x.slack[0] == nil:
		if err = w.WriteBytes(zeroFill[:6]); err != nil {
			return fmt.Errorf("LEDGER-RECORD: writing 6 zero bytes for slack this record carries none for: %w", err)
		}
	case len(x.slack[0]) != 6:
		return fmt.Errorf("LEDGER-RECORD: a writer reports a retained run rather than truncating or padding it, and the run for a slack node of 6 bytes is %d", len(x.slack[0]))
	default:
		if err = w.WriteBytes(x.slack[0]); err != nil {
			return fmt.Errorf("LEDGER-RECORD: writing the 6 bytes no item of it covers: %w", err)
		}
	}

	return nil
}
