// Code generated by cpybkc-gen-go. DO NOT EDIT.

package fixed

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
	"io"
)

// Record is one record of the file this package describes: what a [Reader]
// produces and what a [Writer] takes.
//
// It is codec's two interfaces together rather than a method this generator
// invented. Every record type here already implements both, and a marker method
// would be an identifier neither the copybook nor the layout wrote — which is
// the thing this generator refuses to produce everywhere else. A value that is
// not one of this package's record types satisfies it too, and the writer
// reports one rather than emitting it.
type Record interface {
	codec.Unmarshaler
	codec.Marshaler
}

// readAhead is the reader's buffer, which is bufio's own default: this file's
// framing puts a record's bytes in hand before a predicate is evaluated
// against them, so nothing has to be seen in front of a record.
const readAhead = 4096

// Reader reads the records of one file, walking the automaton this descriptor
// carries.
//
// One record at a time and in this order, which is docs/ir/SPEC.md's "Where
// framing is consumed, and where it is emitted": test for end of input at a
// record boundary, consume the framing in front of the record, evaluate the
// state's transitions — guards first, then predicates, in the order the state
// carries them — admit the record the first one that matches names, check the
// framing against that record's extent, consume the framing behind it, and apply
// that transition's bindings.
//
// The file is never held. What this carries is one record's bytes and the
// register file the automaton remembers in, whatever the file's size.
type Reader struct {
	src *bufio.Reader
	enc codec.Encoding

	// state is where in the automaton the read is, as a position in the switch
	// [Reader.Next] walks. The descriptor's state nodes are numbered by ascending
	// identifier, so a state is a small integer rather than a lookup.
	state int

	// ordinal is which record of the file has been read, counting from one, so
	// that a diagnostic can say where.
	ordinal int

	// done is whether the end of the file has been reached and reported.
	done bool
}

// NewReader reads the records of r under enc.
//
// Neither the charset, the zoned sign convention, the byte order nor the
// floating-point format is chosen here. They are properties of the file in hand
// rather than of this descriptor's items, so the caller states all four at once
// — [Encoding] is what this descriptor resolved, and a file of these records
// converted to another character set is read by passing a different one.
func NewReader(r io.Reader, enc codec.Encoding) (*Reader, error) {
	if r == nil {
		return nil, codec.ErrNilReader
	}

	if err := enc.Validate(); err != nil {
		return nil, err
	}

	return &Reader{
		src:   bufio.NewReaderSize(r, readAhead),
		enc:   enc,
		state: 0,
	}, nil
}

// Next is the next record of the file, or io.EOF where the file is complete.
//
// io.EOF means that and only that. A file cut short is reported as an error of
// its own and never wraps io.EOF, so a caller stepping through records tells
// the two apart with errors.Is and does not have to read the message.
//
// A file that ends in a state that does not accept, or whose acceptance guards
// do not all hold, is reported as truncated rather than returning the records
// that were read: an automaton whose accepting states nobody checks detects
// nothing.
func (r *Reader) Next() (Record, error) {
	if r.done {
		return nil, io.EOF
	}

	// End of input is tested here, at a record boundary, and nowhere else. By
	// the time it runs, framing behind the record before this one has been
	// consumed as the framing it is, so a file whose last record carries a
	// well-formed trailing delimiter is complete rather than holding a record
	// the layout does not describe.
	if _, err := r.src.Peek(1); err != nil {
		if !errors.Is(err, io.EOF) {
			return nil, fmt.Errorf("reading record %d: %w", r.ordinal+1, err)
		}

		r.done = true

		if err := r.accepts(); err != nil {
			return nil, err
		}

		return nil, io.EOF
	}

	r.ordinal++

	if err := r.leading(); err != nil {
		return nil, err
	}

	switch r.state {
	case 0: // the state the descriptor carries as node 2
		// Its one transition, which admits LEDGER-RECORD and carries no predicate: it
		// matches every record, and this state offers nowhere else for one to go.
		rec := new(LedgerRecord)

		if err := r.admit(rec); err != nil {
			return nil, err
		}

		r.state = 0

		return rec, nil
	default:
		return nil, fmt.Errorf("record %d: the automaton is in a state this file does not carry", r.ordinal)
	}
}

// accepts is the truncation rule: a file is complete where the state the read
// ends in accepts and its acceptance guards all hold, and truncated otherwise.
//
// Guarded acceptance is what makes the last iteration of a count detectable. A
// state that reads details while a counter is positive would otherwise have to
// accept unconditionally, and would accept a file stopping three details short
// of what its own header promised.
func (r *Reader) accepts() error {
	switch r.state {
	case 0:
		return nil
	default:
		return fmt.Errorf("the file ends after %d records and the layout describes a record to come", r.ordinal)
	}
}

// leading consumes the framing in front of a record, of which an unframed file has none: a record begins at the byte
// after the record before it.
//
// Framing bytes belong to the dataset and not to any record: no item covers
// them, they are not slack, and no predicate ever sees one.
func (r *Reader) leading() error {
	return nil
}

// admit decodes one record and takes its end from its extent.
//
// The input is never searched for a delimiter and a descriptor word's length is
// never preferred to the extent. Scanning is the obvious way to write a
// line-oriented reader and is wrong on exactly these files: a PIC S9(3)V99
// COMP-3 field holding +152.50 is the bytes 15 25 0C, and both 0x15 and 0x25
// are line delimiters on some mainframe code page. A reader counting the extent
// never reads those bytes as anything but the number they are.
func (r *Reader) admit(rec Record) error {
	cr, err := codec.NewReader(r.src, r.enc)
	if err != nil {
		return fmt.Errorf("reading record %d: %w", r.ordinal, err)
	}

	if err := rec.UnmarshalCOBOL(cr); err != nil {
		if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
			return fmt.Errorf("the file ends part-way through record %d: %v", r.ordinal, err)
		}

		return fmt.Errorf("reading record %d: %w", r.ordinal, err)
	}

	return nil
}

// Writer writes the records of one file, walking the automaton this descriptor
// carries in the other direction.
//
// Its caller names a record and supplies that record's values. It narrows to
// the transitions leaving the state it is in that admit such a record and whose
// guards all hold, evaluates their predicates in the order the state carries
// them, and takes the first that carries no predicate or whose predicate matches
// the bytes it is about to emit. A record satisfying none is reported rather
// than emitted: refusing where the mistake was made costs one diagnostic, and
// emitting costs a file somebody has to read before anyone finds out.
//
// Nothing is buffered beyond the record in hand. A count in a header is never
// back-filled from the records behind it, because holding a group to count it
// gives up exactly the streaming this type exists to have — and because a
// writer that has emitted a record cannot reach back into a stream it does not
// own.
type Writer struct {
	dst io.Writer
	enc codec.Encoding

	// state is where in the automaton the write is, numbered as [Reader.state] is.
	state int

	// ordinal is how many records have been written, so that a diagnostic can
	// say where.
	ordinal int

	// raw is the record in hand, laid out before it is emitted: a predicate is
	// evaluated against the bytes that are about to go out, so they exist
	// before the transition is chosen. It is reused between records.
	raw bytes.Buffer
}

// NewWriter writes records into w under enc.
//
// The four axes are the caller's for the reason they are on [NewReader]: they are
// properties of the file being written rather than of this descriptor's items.
func NewWriter(w io.Writer, enc codec.Encoding) (*Writer, error) {
	if w == nil {
		return nil, codec.ErrNilWriter
	}

	if err := enc.Validate(); err != nil {
		return nil, err
	}

	return &Writer{
		dst:   w,
		enc:   enc,
		state: 0,
	}, nil
}

// Write emits one record.
//
// A value that is not one of this file's record types is reported rather than
// emitted: no transition admits a record the descriptor does not carry, and
// [Record] is satisfied by anything codec can encode.
func (w *Writer) Write(rec Record) error {
	switch v := rec.(type) {
	case *LedgerRecord:
		return w.writeLedgerRecord(v)
	default:
		return fmt.Errorf("record %d: this file's records are LEDGER-RECORD, and a %T is none of them", w.ordinal+1, rec)
	}
}

// Close ends the file, and reports a state that does not accept — or whose
// acceptance guards do not all hold — rather than closing it.
//
// A group that promised four details and was given three is caught here. It is
// the reader's truncation rule from the other side, and a writer skipping the
// check emits the truncated file its reader complains about one build later.
//
// It does not close the io.Writer it was handed, which belongs to the caller.
func (w *Writer) Close() error {
	switch w.state {
	case 0:
		return nil
	default:
		return fmt.Errorf("the file is closed after %d records and the layout describes a record to come", w.ordinal)
	}
}

// writeLedgerRecord emits one LEDGER-RECORD.
//
// The record is laid out first and the transition is chosen against those
// bytes, because what a predicate tests is what is about to be emitted.
func (w *Writer) writeLedgerRecord(rec *LedgerRecord) error {
	w.raw.Reset()

	cw, err := codec.NewWriter(&w.raw, w.enc)
	if err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	if err := rec.MarshalCOBOL(cw); err != nil {
		return fmt.Errorf("writing record %d: %w", w.ordinal+1, err)
	}

	raw := w.raw.Bytes()

	switch w.state {
	case 0: // the state the descriptor carries as node 2
		// Transition 1 of that state.
		if err := w.emit(raw); err != nil {
			return err
		}

		w.state = 0
		w.ordinal++

		return nil
	}

	return w.refuse("LEDGER-RECORD", "")
}

// refuse is what a writer says when no transition leaving the state it is in
// took the record it was asked to write.
//
// The record does not belong at this point in the file with the values it has,
// and the value a predicate tests is the caller's: a writer checks it and
// reports it when it is wrong rather than deriving one that would satisfy the
// test and storing it into the field.
func (w *Writer) refuse(record string, excluded string) error {
	if excluded != "" {
		return fmt.Errorf("record %d is a %s and does not belong here: %s", w.ordinal+1, record, excluded)
	}

	return fmt.Errorf("record %d is a %s and no transition leaving the state the automaton is in admits one whose values satisfy that transition's predicate, so it is reported rather than emitted", w.ordinal+1, record)
}

// emit writes one record's bytes with this file's framing around them.
//
// An unframed file has none: a record is its extent and the next one begins at
// the byte after it.
func (w *Writer) emit(raw []byte) error {
	_, err := w.dst.Write(raw)

	return err
}
