// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The file tier of this package's generated tests: one case per path through the
// automaton this layout describes, and between them every transition predicate it
// carries and every literal of a set-membership one.
//
// Each case carries a whole file as a literal — the framing as well as the records
// — reads it with the generated Reader, checks that the record types came back in
// the order the automaton admits them, writes them back with the generated Writer
// and checks that the bytes are the bytes it started from. The file is synthesized
// from the layout rather than read from a dataset, so it is what to hold against
// the file on your desk: the comment column names each run, the offset inside its
// record, and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports fixed.
package fixed_test

import (
	"bytes"
	"errors"
	"github.com/Zaba505/cpybkc/cmd/cpybkc-gen-go/internal/fixed"
	"io"
	"testing"
)

// TestTwoLedgerRecords is a file of two LEDGER-RECORD records: the bytes
// below, the records they read back as, and the same bytes written back.
func TestTwoLedgerRecords(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, // record 1: LEDGER-ID @0 X(4)
		0xc4,                   // record 1: ENTRY(1).ENTRY-TYPE @4 X(1)
		0xc6, 0xc6, 0xc6, 0xc6, // record 1: ENTRY(1).ENTRY-DETAIL.DETAIL-SKU @5 X(4)
		0xff, 0xf6, // record 1: ENTRY(1).ENTRY-DETAIL.DETAIL-QTY @9 S9(4) BINARY
		0xc4,                   // record 1: ENTRY(2).ENTRY-TYPE @11 X(1)
		0xd4, 0xd4, 0xd4, 0xd4, // record 1: ENTRY(2).ENTRY-DETAIL.DETAIL-SKU @12 X(4)
		0xff, 0xef, // record 1: ENTRY(2).ENTRY-DETAIL.DETAIL-QTY @16 S9(4) BINARY
		0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, // record 1: (slack) @18 6 bytes no item covers
		0xc1, 0xc1, 0xc1, 0xc1, // record 2: LEDGER-ID @0 X(4)
		0xc4,                   // record 2: ENTRY(1).ENTRY-TYPE @4 X(1)
		0xc6, 0xc6, 0xc6, 0xc6, // record 2: ENTRY(1).ENTRY-DETAIL.DETAIL-SKU @5 X(4)
		0xff, 0xf6, // record 2: ENTRY(1).ENTRY-DETAIL.DETAIL-QTY @9 S9(4) BINARY
		0xc4,                   // record 2: ENTRY(2).ENTRY-TYPE @11 X(1)
		0xd4, 0xd4, 0xd4, 0xd4, // record 2: ENTRY(2).ENTRY-DETAIL.DETAIL-SKU @12 X(4)
		0xff, 0xef, // record 2: ENTRY(2).ENTRY-DETAIL.DETAIL-QTY @16 S9(4) BINARY
		0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, // record 2: (slack) @18 6 bytes no item covers
	}

	r, err := fixed.NewReader(bytes.NewReader(in), fixed.Encoding())
	if err != nil {
		t.Fatalf("NewReader: %v", err)
	}

	var records []fixed.Record

	for {
		rec, err := r.Next()
		if errors.Is(err, io.EOF) {
			break
		}

		if err != nil {
			t.Fatalf("Next: %v", err)
		}

		records = append(records, rec)
	}

	if len(records) != 2 {
		t.Fatalf("the file holds 2 records and the reader produced %d", len(records))
	}

	if _, ok := records[0].(*fixed.LedgerRecord); !ok {
		t.Fatalf("record 1 is LEDGER-RECORD and came back as a %T, want a *fixed.LedgerRecord", records[0])
	}

	if _, ok := records[1].(*fixed.LedgerRecord); !ok {
		t.Fatalf("record 2 is LEDGER-RECORD and came back as a %T, want a *fixed.LedgerRecord", records[1])
	}

	var out bytes.Buffer

	w, err := fixed.NewWriter(&out, fixed.Encoding())
	if err != nil {
		t.Fatalf("NewWriter: %v", err)
	}

	for _, rec := range records {
		if err := w.Write(rec); err != nil {
			t.Fatalf("Write: %v", err)
		}
	}

	if err := w.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the file does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
