// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The record tier of this package's generated tests: one case per record the
// layout describes, and one per arm of an alternation inside one.
//
// Each case carries the bytes it reads as a literal, decodes them, checks every
// field against the value the literal was laid out with, and writes the record
// back out byte for byte. The bytes are synthesized from the layout rather than
// read from a file, so they are what to hold against the file on your desk: the
// comment column names the item, the offset summed from the widths ahead of it,
// and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports fixed.
package fixed_test

import (
	"bytes"
	"github.com/Zaba505/cobol-go/codec"
	"github.com/Zaba505/cpybkc/cmd/cpybkc-gen-go/internal/fixed"
	"testing"
)

// TestLedgerRecordReadsBackTheBytesItWasReadFrom is LEDGER-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestLedgerRecordReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, // LEDGER-ID @0 X(4)
		0xc4,                   // ENTRY(1).ENTRY-TYPE @4 X(1)
		0xc6, 0xc6, 0xc6, 0xc6, // ENTRY(1).ENTRY-DETAIL.DETAIL-SKU @5 X(4)
		0xff, 0xf6, // ENTRY(1).ENTRY-DETAIL.DETAIL-QTY @9 S9(4) BINARY
		0xc4,                   // ENTRY(2).ENTRY-TYPE @11 X(1)
		0xd4, 0xd4, 0xd4, 0xd4, // ENTRY(2).ENTRY-DETAIL.DETAIL-SKU @12 X(4)
		0xff, 0xef, // ENTRY(2).ENTRY-DETAIL.DETAIL-QTY @16 S9(4) BINARY
		0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, // (slack) @18 6 bytes no item covers
	}

	r, err := codec.NewReader(bytes.NewReader(in), fixed.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record fixed.LedgerRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.LedgerId != "AAAA" {
		t.Errorf("LEDGER-ID: got %q, want %q", record.LedgerId, "AAAA")
	}

	if record.Entry[0].EntryType != "D" {
		t.Errorf("ENTRY(1).ENTRY-TYPE: got %q, want %q", record.Entry[0].EntryType, "D")
	}

	if record.Entry[0].EntryDetail == nil {
		t.Fatalf("ENTRY(1).ENTRY-DETAIL: the record holds no arm, and its bytes select this one")
	}

	if record.Entry[0].EntrySummary != nil {
		t.Errorf("ENTRY(1).ENTRY-SUMMARY: the record holds this arm, and its bytes select another")
	}

	if record.Entry[0].EntryDetail.DetailSku != "FFFF" {
		t.Errorf("ENTRY(1).ENTRY-DETAIL.DETAIL-SKU: got %q, want %q", record.Entry[0].EntryDetail.DetailSku, "FFFF")
	}

	if record.Entry[0].EntryDetail.DetailQty != -10 {
		t.Errorf("ENTRY(1).ENTRY-DETAIL.DETAIL-QTY: got %d, want %d", record.Entry[0].EntryDetail.DetailQty, -10)
	}

	if record.Entry[1].EntryType != "D" {
		t.Errorf("ENTRY(2).ENTRY-TYPE: got %q, want %q", record.Entry[1].EntryType, "D")
	}

	if record.Entry[1].EntryDetail == nil {
		t.Fatalf("ENTRY(2).ENTRY-DETAIL: the record holds no arm, and its bytes select this one")
	}

	if record.Entry[1].EntrySummary != nil {
		t.Errorf("ENTRY(2).ENTRY-SUMMARY: the record holds this arm, and its bytes select another")
	}

	if record.Entry[1].EntryDetail.DetailSku != "MMMM" {
		t.Errorf("ENTRY(2).ENTRY-DETAIL.DETAIL-SKU: got %q, want %q", record.Entry[1].EntryDetail.DetailSku, "MMMM")
	}

	if record.Entry[1].EntryDetail.DetailQty != -17 {
		t.Errorf("ENTRY(2).ENTRY-DETAIL.DETAIL-QTY: got %d, want %d", record.Entry[1].EntryDetail.DetailQty, -17)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, fixed.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestLedgerRecordHoldingEntrySummaryReadsBackTheBytesItWasReadFrom is
// LEDGER-RECORD: the bytes below, every field they decode into, and the same
// bytes written back.
//
// The alternation this case is for holds ENTRY-SUMMARY.
func TestLedgerRecordHoldingEntrySummaryReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, // LEDGER-ID @0 X(4)
		0xe2,                   // ENTRY(1).ENTRY-TYPE @4 X(1)
		0xc6, 0xc6, 0xc6, 0xc6, // ENTRY(1).ENTRY-SUMMARY.SUMMARY-TEXT @5 X(4)
		0xa9, 0xaa, // ENTRY(1).ENTRY-SUMMARY.(slack) @9 2 bytes no item covers
		0xe2,                   // ENTRY(2).ENTRY-TYPE @11 X(1)
		0xd4, 0xd4, 0xd4, 0xd4, // ENTRY(2).ENTRY-SUMMARY.SUMMARY-TEXT @12 X(4)
		0xb0, 0xb1, // ENTRY(2).ENTRY-SUMMARY.(slack) @16 2 bytes no item covers
		0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, // (slack) @18 6 bytes no item covers
	}

	r, err := codec.NewReader(bytes.NewReader(in), fixed.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record fixed.LedgerRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.LedgerId != "AAAA" {
		t.Errorf("LEDGER-ID: got %q, want %q", record.LedgerId, "AAAA")
	}

	if record.Entry[0].EntryType != "S" {
		t.Errorf("ENTRY(1).ENTRY-TYPE: got %q, want %q", record.Entry[0].EntryType, "S")
	}

	if record.Entry[0].EntryDetail != nil {
		t.Errorf("ENTRY(1).ENTRY-DETAIL: the record holds this arm, and its bytes select another")
	}

	if record.Entry[0].EntrySummary == nil {
		t.Fatalf("ENTRY(1).ENTRY-SUMMARY: the record holds no arm, and its bytes select this one")
	}

	if record.Entry[0].EntrySummary.SummaryText != "FFFF" {
		t.Errorf("ENTRY(1).ENTRY-SUMMARY.SUMMARY-TEXT: got %q, want %q", record.Entry[0].EntrySummary.SummaryText, "FFFF")
	}

	if record.Entry[1].EntryType != "S" {
		t.Errorf("ENTRY(2).ENTRY-TYPE: got %q, want %q", record.Entry[1].EntryType, "S")
	}

	if record.Entry[1].EntryDetail != nil {
		t.Errorf("ENTRY(2).ENTRY-DETAIL: the record holds this arm, and its bytes select another")
	}

	if record.Entry[1].EntrySummary == nil {
		t.Fatalf("ENTRY(2).ENTRY-SUMMARY: the record holds no arm, and its bytes select this one")
	}

	if record.Entry[1].EntrySummary.SummaryText != "MMMM" {
		t.Errorf("ENTRY(2).ENTRY-SUMMARY.SUMMARY-TEXT: got %q, want %q", record.Entry[1].EntrySummary.SummaryText, "MMMM")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, fixed.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
