// Copyright (c) 2026 Richard Carson Derr
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/Zaba505/cpybkc/irpb"
)

// The one file a run writes, named for the notation it is written in.
//
// The names are fixed rather than derived, and there is no option to change
// them: the descriptor carries no name for the layout it describes, and
// docs/plugin/SPEC.md's "The descriptor" forbids deriving anything from the
// descriptor's own path or the directory holding it. The output directory's
// name is cpybkc's to choose and varies between runs, so a filename taken from
// it would make the output a function of a path — which is what "Determinism"
// forbids. What is left is a constant, and one document per run is what this
// generator produces.
const (
	mermaidFile = "graph.md"
	dotFile     = "graph.dot"
)

// generatedBy is the line that says a file was not written by hand, in each
// notation's own comment syntax.
//
// Go's own tooling matches `^// Code generated .* DO NOT EDIT\.$` and neither
// of these files is Go, but the sentence is the one a reader of a diff already
// knows, and the Markdown document carries it as an HTML comment so that it
// does not render.
const (
	generatedBy = "Code generated by " + pluginName + ". DO NOT EDIT."

	mermaidGeneratedBy = "<!-- " + generatedBy + " -->"
	dotGeneratedBy     = "// " + generatedBy
)

// write writes this invocation's document beneath out.
//
// docs/plugin/SPEC.md's "Determinism" is met by there being nothing in the
// output that is not a function of the descriptor and the options: no
// timestamp, no hostname, no user, no absolute path, and no value read from
// anywhere but the arguments. The generator's own name is in the output and is
// allowed to be — it is a property of the executable rather than of the
// invocation, and output that changes when the generator is upgraded is
// expected.
//
// The document is composed whole and then written, so that a descriptor this
// generator refuses leaves the output directory as it found it — empty. A
// generator that wrote as it went would hand cpybkc a directory it is entitled
// to merge, holding half a document.
func write(descriptor *irpb.Descriptor, out string, opts options) error {
	name, content, err := document(descriptor, opts)
	if err != nil {
		return err
	}

	// Written directly beneath out, and beneath it only: docs/plugin/SPEC.md
	// gives this program an empty, writable directory of its own and forbids it
	// to write anywhere else. The path is joined here rather than anywhere a
	// file name could arrive from outside this program.
	if err := os.WriteFile(filepath.Join(out, name), []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", name, err)
	}

	return nil
}

// document is the file this invocation writes: its name, and its whole
// contents.
//
// # What it draws today
//
// The sequencing automaton: the states the descriptor carries, the transitions
// between them, where a read begins and where one may end — and, on each
// transition, the record it admits, the predicate that selects it, the guards
// that make it eligible and the bindings it applies, with a table of the
// registers those bindings write. The descriptor is read once, by [read], into
// a [graph] — and an emitter is a function over that, so #190's `dot` rendering
// is a second arm below rather than a second walk.
//
// What it does not draw yet is each record's items with their offsets (#189).
// That is a field on [graph] and a few lines in each emitter when it lands,
// which is what the model is shaped for and how everything above arrived.
//
// # Why the default arm is a failure rather than a notation
//
// [parse] admits exactly the two formats below and defaults the option, so the
// last arm cannot be reached from an argument vector. It is a failure anyway,
// because the way it *would* be reached is a third format added to the closed
// set with no arm added here — and the alternative to failing is writing a
// Mermaid document under the Mermaid filename for a caller who asked for
// something else. That is the "silently rounded to a default" outcome the
// option vocabulary refuses on the way in, and it would be worse arriving on
// the way out, where nothing is left to say it happened.
func document(descriptor *irpb.Descriptor, opts options) (string, string, error) {
	// Before the switch, and once: the walk is the same walk whichever notation
	// asked for it, and a descriptor this generator refuses is refused before a
	// notation has been chosen to refuse it in.
	g, err := read(descriptor)
	if err != nil {
		return "", "", err
	}

	switch opts.format {
	case formatDot:
		// The graph is named for this project rather than for the layout,
		// because the descriptor states no name for the layout and the two paths
		// this generator can see are ones it may not read a name out of. `dot`
		// requires a name-or-nothing here and an anonymous digraph is one a
		// reader cannot refer to from a document that embeds it.
		//
		// Still empty, and #190 is where it fills in. The Graphviz rendering is
		// a story of its own because Mermaid is what renders in a diff without
		// a toolchain and `dot` is what stays legible when Mermaid's layout
		// gives up — two different readers, and one of them is served by the
		// document above today.
		return dotFile, dotGeneratedBy + "\n\ndigraph cpybkc {\n}\n", nil
	case formatMermaid:
		return mermaidFile, mermaid(g), nil
	default:
		return "", "", fmt.Errorf("this generator has no document for %s=%q, which is a bug in %s",
			formatOption, opts.format, pluginName)
	}
}
