// Copyright (c) 2026 Richard Carson Derr
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/Zaba505/cpybkc/irpb"
)

// goldenDir is where the documents this generator is pinned to are checked in.
//
// Files under testdata/ rather than a Go package, which is where
// cmd/cpybkc-gen-go keeps its golden. That generator's output is Go, so making
// the golden a package presses this repository's own compiler, `go vet` and
// lint into asserting that what it writes compiles; a Markdown document has no
// compiler to press into service, and a `.md` in testdata/ is a file a reviewer
// reads in a diff exactly as an adopter reads it in their own tree.
const goldenDir = "testdata"

// TestTheDocumentEachFramingProducesIsTheGolden regenerates the document for
// every framing and holds every byte of it against the file checked in beside
// this command.
//
// # Why a golden and not assertions
//
// What this generator produces is a document somebody reads. A change to the
// shape of it is a change to what an adopter sees, and a test asserting that
// some state appears somewhere would pass through most of those changes without
// noticing — including the ones that make the document unreadable. Holding the
// whole file is what makes "the diagram still reads well" something a reviewer
// is shown rather than something they would have to run the generator to see.
//
// # Why one per framing
//
// The four goldens are drawn from one automaton, so the only difference between
// any two of them is the sentence stating the framing. That is the point:
// [framings] is the closed set docs/ir/SPEC.md's "Four framings, and none of
// them is a RECFM" fixes, each of its members says something different about
// what stands between two records, and a document that stated the wrong one
// would be wrong about the bytes while being right about every record.
//
// # Regenerating them
//
// The failure below prints the document that was generated. A golden is
// regenerated by replacing the file with it — deliberately by hand, and
// deliberately not by a flag on this test: these files are the review surface
// for a change to what this generator writes, and a `-update` that rewrote them
// in the same command that checked them would let a change to the output land
// without anybody having read it.
func TestTheDocumentEachFramingProducesIsTheGolden(t *testing.T) {
	t.Parallel()

	for name, g := range goldens() {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			path := filepath.Join(goldenDir, name+".md")

			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("reading the golden: %v", err)
			}

			got := writtenDocument(t, g.descriptor(), g.opts...)

			if got != string(want) {
				t.Errorf("the document for %s is not %s\n got:\n%s\nwant:\n%s", name, path, got, want)
			}
		})
	}
}

// countedGolden is the name of the one golden that is not a framing.
//
// The four above are one automaton under four framings, so what they hold
// constant is everything the automaton says and what they vary is the sentence
// above the diagram. This one is the other way round: one framing, and an
// automaton carrying every part of the half of it that chooses a transition —
// docs/ir/SPEC.md's "Appendix: A counted run, as nodes", which is also the
// descriptor cmd/cpybkc-gen-go/internal/counted is generated from.
//
// It earns a golden of its own for the reason the framings do. A predicate's
// literal, a guard's conjunction, a decrement and a register table are things
// somebody reads, an assertion that each appears somewhere would pass through
// most of the changes that make them unreadable, and holding the whole file is
// what puts "this still reads well" in front of a reviewer instead of behind a
// command they would have to run.
const countedGolden = "counted"

// The two goldens that are neither a framing nor the counted run.
//
// [variableGolden] is the item tables' own: one record whose offsets are a sum
// with a variable term, a slack run, a variant and a constant table, and one
// record that is every USAGE and every category of picture this generator can
// spell. It exists because the arithmetic in records.go is the part of this
// generator a reader trusts without being able to check — an offset one byte out
// draws exactly as confidently as a right one — and the whole file held against
// a checked-in copy is what puts it in front of a reviewer.
//
// [noRecordsGolden] is the same automaton as [countedGolden] under
// `records=none`, and the pair is the option: two files that differ by the
// section, over one descriptor, so that "the tables are omitted entirely" is a
// diff rather than a claim.
const (
	variableGolden  = "variable"
	noRecordsGolden = "counted-records-none"
)

// golden is one checked-in document: the descriptor it is drawn from, and the
// options the run that draws it states.
//
// The options are part of the golden and not a property of the harness, because
// what this generator writes is a function of both — `records=none` over the
// counted automaton is a different document from `records=all` over it, and a
// list carrying only descriptors could not say so.
type golden struct {
	descriptor func() *irpb.Descriptor
	opts       []string
}

// goldens is every document checked in beneath testdata/, by the name of the
// file holding it.
//
// One list, so that "there is a golden for each of these and nothing else"
// stays a question with one place to answer it — a fifth framing added to the
// schema lands here as a golden nobody wrote, and a file left behind by a
// rename is one a reviewer would otherwise keep reading as though it described
// something.
func goldens() map[string]golden {
	all := map[string]golden{
		countedGolden:  {descriptor: countedAutomaton},
		variableGolden: {descriptor: variableAutomaton},
		noRecordsGolden: {
			descriptor: countedAutomaton,
			opts:       []string{optFlag, recordsOption + "=" + recordsNone},
		},
	}

	for _, framing := range framings() {
		file := framing.file
		all[framing.name] = golden{descriptor: func() *irpb.Descriptor { return ordersAutomaton(file) }}
	}

	return all
}

// TestThereIsAGoldenForEveryDocumentAndNoOthers keeps testdata/ and [goldens]
// in step from both directions.
//
// A fifth framing added to the schema advances the IR version and lands here as
// a golden nobody wrote; a golden left behind by a framing that was renamed is a
// file a reviewer would keep reading as though it described something.
func TestThereIsAGoldenForEveryDocumentAndNoOthers(t *testing.T) {
	t.Parallel()

	entries, err := os.ReadDir(goldenDir)
	if err != nil {
		t.Fatalf("reading %s: %v", goldenDir, err)
	}

	// The invariant is "one `.md` per document", not "nothing but documents may
	// live here". A directory or a checked-in fixture beside the goldens is not
	// a document that went missing, and reporting it as one would send a reader
	// looking for a rename that never happened.
	checked := map[string]bool{}

	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}

		checked[entry.Name()] = true
	}

	for golden := range goldens() {
		name := golden + ".md"

		if !checked[name] {
			t.Errorf("%s is a golden and %s carries no file for it", golden, goldenDir)
		}

		delete(checked, name)
	}

	for name := range checked {
		t.Errorf("%s holds the golden %s, and nothing produces it", goldenDir, name)
	}
}
