// Copyright (c) 2026 Richard Carson Derr
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package main

import (
	"os"
	"path/filepath"
	"testing"
)

// goldenDir is where the documents this generator is pinned to are checked in.
//
// Files under testdata/ rather than a Go package, which is where
// cmd/cpybkc-gen-go keeps its golden. That generator's output is Go, so making
// the golden a package presses this repository's own compiler, `go vet` and
// lint into asserting that what it writes compiles; a Markdown document has no
// compiler to press into service, and a `.md` in testdata/ is a file a reviewer
// reads in a diff exactly as an adopter reads it in their own tree.
const goldenDir = "testdata"

// TestTheDocumentEachFramingProducesIsTheGolden regenerates the document for
// every framing and holds every byte of it against the file checked in beside
// this command.
//
// # Why a golden and not assertions
//
// What this generator produces is a document somebody reads. A change to the
// shape of it is a change to what an adopter sees, and a test asserting that
// some state appears somewhere would pass through most of those changes without
// noticing — including the ones that make the document unreadable. Holding the
// whole file is what makes "the diagram still reads well" something a reviewer
// is shown rather than something they would have to run the generator to see.
//
// # Why one per framing
//
// The four goldens are drawn from one automaton, so the only difference between
// any two of them is the sentence stating the framing. That is the point:
// [framings] is the closed set docs/ir/SPEC.md's "Four framings, and none of
// them is a RECFM" fixes, each of its members says something different about
// what stands between two records, and a document that stated the wrong one
// would be wrong about the bytes while being right about every record.
//
// # Regenerating them
//
// The failure below prints the document that was generated. A golden is
// regenerated by replacing the file with it — deliberately by hand, and
// deliberately not by a flag on this test: these files are the review surface
// for a change to what this generator writes, and a `-update` that rewrote them
// in the same command that checked them would let a change to the output land
// without anybody having read it.
func TestTheDocumentEachFramingProducesIsTheGolden(t *testing.T) {
	t.Parallel()

	for _, testCase := range framings() {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			path := filepath.Join(goldenDir, testCase.name+".md")

			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("reading the golden: %v", err)
			}

			got := writtenDocument(t, ordersAutomaton(testCase.file))

			if got != string(want) {
				t.Errorf("the document for %s is not %s\n got:\n%s\nwant:\n%s", testCase.name, path, got, want)
			}
		})
	}
}

// TestThereIsAGoldenForEveryFramingAndNoOthers keeps testdata/ and the closed
// set in step from both directions.
//
// A fifth framing added to the schema advances the IR version and lands here as
// a golden nobody wrote; a golden left behind by a framing that was renamed is a
// file a reviewer would keep reading as though it described something.
func TestThereIsAGoldenForEveryFramingAndNoOthers(t *testing.T) {
	t.Parallel()

	entries, err := os.ReadDir(goldenDir)
	if err != nil {
		t.Fatalf("reading %s: %v", goldenDir, err)
	}

	checked := map[string]bool{}
	for _, entry := range entries {
		checked[entry.Name()] = true
	}

	for _, testCase := range framings() {
		name := testCase.name + ".md"

		if !checked[name] {
			t.Errorf("%s is a framing and %s carries no golden for it", testCase.name, goldenDir)
		}

		delete(checked, name)
	}

	for name := range checked {
		t.Errorf("%s holds %s, and no framing produces it", goldenDir, name)
	}
}
