// Code generated by cpybkc-gen-go. DO NOT EDIT.

package chunks

import (
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
)

// Encoding is the byte-level interpretation of the files these records live in:
// the five axes as they were resolved — four the layout declared, and the binary
// width staircase the copybook's items were laid out under.
//
// None of the five has a default and every one of them fails silently when
// wrong, so codec has no usable zero-value Reader and this function is how a
// caller states all five at once:
//
//	r, err := codec.NewReader(f, Encoding())
//
// Binary is the odd one. The other four say how a byte becomes a value; this one
// says how many bytes a COMP item is, which is a property of the compiler that
// wrote the file rather than of the copybook — PIC S9(2) COMP is two bytes under
// IBM Enterprise COBOL and one under GnuCOBOL's default. It is the staircase the
// offsets in these records were computed under, so changing it here does not
// reinterpret the file, it describes a different one.
//
// It is a value a caller passes rather than one anything applies on its own. A
// file this descriptor describes that was converted to another character set is
// read by passing a different Encoding, not by regenerating.
func Encoding() codec.Encoding {
	return codec.Encoding{
		Charset:   codec.CP037(),
		Sign:      codec.SignEBCDIC,
		ByteOrder: binary.BigEndian,
		Float:     codec.FloatHFP,
		Binary:    codec.BinarySize248,
	}
}

// Every record reads and writes itself, which is codec's Unmarshaler and
// Marshaler. Asserted here so that a drift in either interface fails in the
// file that implements it.
var (
	_ codec.Unmarshaler = (*ChunkRecord)(nil)
	_ codec.Marshaler   = (*ChunkRecord)(nil)
)

// UnmarshalCOBOL reads one CHUNK-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *ChunkRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.ChunkId, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("CHUNK-RECORD: reading CHUNK-ID: %w", err)
	}

	if x.ChunkBody, err = r.ReadAlphanumeric(20); err != nil {
		return fmt.Errorf("CHUNK-RECORD: reading CHUNK-BODY: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this CHUNK-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *ChunkRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(x.ChunkId, 4); err != nil {
		return fmt.Errorf("CHUNK-RECORD: writing CHUNK-ID: %w", err)
	}

	if err = w.WriteAlphanumeric(x.ChunkBody, 20); err != nil {
		return fmt.Errorf("CHUNK-RECORD: writing CHUNK-BODY: %w", err)
	}

	return nil
}
