// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The file tier of this package's generated tests: one case per path through the
// automaton this layout describes, and between them every transition predicate it
// carries and every literal of a set-membership one.
//
// Each case carries a whole file as a literal — the framing as well as the records
// — reads it with the generated Reader, checks that the record types came back in
// the order the automaton admits them, writes them back with the generated Writer
// and checks that the bytes are the bytes it started from. The file is synthesized
// from the layout rather than read from a dataset, so it is what to hold against
// the file on your desk: the comment column names each run, the offset inside its
// record, and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports chunks.
package chunks_test

import (
	"bytes"
	"errors"
	"github.com/Zaba505/cpybkc/cmd/cpybkc-gen-go/internal/chunks"
	"io"
	"testing"
)

// TestTwoChunkRecords is a file of two CHUNK-RECORD records: the bytes below,
// the records they read back as, and the same bytes written back.
func TestTwoChunkRecords(t *testing.T) {
	t.Parallel()

	in := []byte{
		0x00, 0x0c, 0x01, 0x00, // record 1: segment 1's descriptor word — 12 bytes, itself included
		0xc1, 0xc1, 0xc1, 0xc1, // record 1: CHUNK-ID @0 X(4)
		0xc5, 0xc5, 0xc5, 0xc5, // record 1: CHUNK-BODY @4 X(20)
		0x00, 0x0c, 0x03, 0x00, // record 1: segment 2's descriptor word — 12 bytes, itself included
		0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, // record 1: CHUNK-BODY @4 X(20) (continued)
		0x00, 0x0c, 0x02, 0x00, // record 1: segment 3's descriptor word — 12 bytes, itself included
		0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, // record 1: CHUNK-BODY @4 X(20) (continued)
		0x00, 0x0c, 0x01, 0x00, // record 2: segment 1's descriptor word — 12 bytes, itself included
		0xc1, 0xc1, 0xc1, 0xc1, // record 2: CHUNK-ID @0 X(4)
		0xc5, 0xc5, 0xc5, 0xc5, // record 2: CHUNK-BODY @4 X(20)
		0x00, 0x0c, 0x03, 0x00, // record 2: segment 2's descriptor word — 12 bytes, itself included
		0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, // record 2: CHUNK-BODY @4 X(20) (continued)
		0x00, 0x0c, 0x02, 0x00, // record 2: segment 3's descriptor word — 12 bytes, itself included
		0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, 0xc5, // record 2: CHUNK-BODY @4 X(20) (continued)
	}

	r, err := chunks.NewReader(bytes.NewReader(in), chunks.Encoding())
	if err != nil {
		t.Fatalf("NewReader: %v", err)
	}

	var records []chunks.Record

	for {
		rec, err := r.Next()
		if errors.Is(err, io.EOF) {
			break
		}

		if err != nil {
			t.Fatalf("Next: %v", err)
		}

		records = append(records, rec)
	}

	if len(records) != 2 {
		t.Fatalf("the file holds 2 records and the reader produced %d", len(records))
	}

	if _, ok := records[0].(*chunks.ChunkRecord); !ok {
		t.Fatalf("record 1 is CHUNK-RECORD and came back as a %T, want a *chunks.ChunkRecord", records[0])
	}

	if _, ok := records[1].(*chunks.ChunkRecord); !ok {
		t.Fatalf("record 2 is CHUNK-RECORD and came back as a %T, want a *chunks.ChunkRecord", records[1])
	}

	var out bytes.Buffer

	w, err := chunks.NewWriter(&out, chunks.Encoding())
	if err != nil {
		t.Fatalf("NewWriter: %v", err)
	}

	for _, rec := range records {
		if err := w.Write(rec); err != nil {
			t.Fatalf("Write: %v", err)
		}
	}

	if err := w.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the file does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
