// Code generated by cpybkc-gen-go. DO NOT EDIT.

package chunks

// ChunkRecord is the CHUNK-RECORD record, as docs/ir/SPEC.md resolved it.
type ChunkRecord struct {
	// ChunkId is CHUNK-ID — alphanumeric, DISPLAY, 4 bytes.
	ChunkId string

	// ChunkBody is CHUNK-BODY — alphanumeric, DISPLAY, 20 bytes.
	ChunkBody string
}
