// Code generated by cpybkc-gen-go. DO NOT EDIT.

package counted

import (
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
)

// Encoding is the byte-level interpretation of the files these records live in:
// the five axes as they were resolved — four the layout declared, and the binary
// width staircase the copybook's items were laid out under.
//
// None of the five has a default and every one of them fails silently when
// wrong, so codec has no usable zero-value Reader and this function is how a
// caller states all five at once:
//
//	r, err := codec.NewReader(f, Encoding())
//
// Binary is the odd one. The other four say how a byte becomes a value; this one
// says how many bytes a COMP item is, which is a property of the compiler that
// wrote the file rather than of the copybook — PIC S9(2) COMP is two bytes under
// IBM Enterprise COBOL and one under GnuCOBOL's default. It is the staircase the
// offsets in these records were computed under, so changing it here does not
// reinterpret the file, it describes a different one.
//
// It is a value a caller passes rather than one anything applies on its own. A
// file this descriptor describes that was converted to another character set is
// read by passing a different Encoding, not by regenerating.
func Encoding() codec.Encoding {
	return codec.Encoding{
		Charset:   codec.CP037(),
		Sign:      codec.SignEBCDIC,
		ByteOrder: binary.BigEndian,
		Float:     codec.FloatHFP,
		Binary:    codec.BinarySize248,
	}
}

// Every record reads and writes itself, which is codec's Unmarshaler and
// Marshaler. Asserted here so that a drift in either interface fails in the
// file that implements it.
var (
	_ codec.Unmarshaler = (*HeaderRecord)(nil)
	_ codec.Marshaler   = (*HeaderRecord)(nil)
	_ codec.Unmarshaler = (*DetailRecord)(nil)
	_ codec.Marshaler   = (*DetailRecord)(nil)
	_ codec.Unmarshaler = (*SummaryRecord)(nil)
	_ codec.Marshaler   = (*SummaryRecord)(nil)
)

// UnmarshalCOBOL reads one HEADER-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *HeaderRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.TypeCode, err = r.ReadAlphanumeric(1); err != nil {
		return fmt.Errorf("HEADER-RECORD: reading TYPE-CODE: %w", err)
	}

	if x.DtlCount, err = r.ReadZonedInt32(2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("HEADER-RECORD: reading DTL-COUNT: %w", err)
	}

	if x.SumFlag, err = r.ReadAlphanumeric(1); err != nil {
		return fmt.Errorf("HEADER-RECORD: reading SUM-FLAG: %w", err)
	}

	if x.TotalCount, err = r.ReadZonedInt32(2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("HEADER-RECORD: reading TOTAL-COUNT: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this HEADER-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *HeaderRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(x.TypeCode, 1); err != nil {
		return fmt.Errorf("HEADER-RECORD: writing TYPE-CODE: %w", err)
	}

	if err = w.WriteZonedInt32(x.DtlCount, 2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("HEADER-RECORD: writing DTL-COUNT: %w", err)
	}

	if err = w.WriteAlphanumeric(x.SumFlag, 1); err != nil {
		return fmt.Errorf("HEADER-RECORD: writing SUM-FLAG: %w", err)
	}

	if err = w.WriteZonedInt32(x.TotalCount, 2, codec.SignUnsigned); err != nil {
		return fmt.Errorf("HEADER-RECORD: writing TOTAL-COUNT: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one DETAIL-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *DetailRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.TypeCode, err = r.ReadAlphanumeric(1); err != nil {
		return fmt.Errorf("DETAIL-RECORD: reading TYPE-CODE: %w", err)
	}

	if x.Amount, err = r.ReadPackedInt32(5); err != nil {
		return fmt.Errorf("DETAIL-RECORD: reading AMOUNT: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this DETAIL-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *DetailRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(x.TypeCode, 1); err != nil {
		return fmt.Errorf("DETAIL-RECORD: writing TYPE-CODE: %w", err)
	}

	if err = w.WritePackedInt32(x.Amount, 5, codec.Signed); err != nil {
		return fmt.Errorf("DETAIL-RECORD: writing AMOUNT: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one SUMMARY-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *SummaryRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.TypeCode, err = r.ReadAlphanumeric(1); err != nil {
		return fmt.Errorf("SUMMARY-RECORD: reading TYPE-CODE: %w", err)
	}

	for i0 := range x.Line {
		if x.Line[i0].LineText, err = r.ReadAlphanumeric(3); err != nil {
			return fmt.Errorf("SUMMARY-RECORD: reading LINE-TEXT in occurrence %d of LINE: %w", i0, err)
		}
	}

	for i0 := range x.Note {
		if x.Note[i0].NoteText, err = r.ReadAlphanumeric(2); err != nil {
			return fmt.Errorf("SUMMARY-RECORD: reading NOTE-TEXT in occurrence %d of NOTE: %w", i0, err)
		}
	}

	return nil
}

// MarshalCOBOL writes this SUMMARY-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *SummaryRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(x.TypeCode, 1); err != nil {
		return fmt.Errorf("SUMMARY-RECORD: writing TYPE-CODE: %w", err)
	}

	if n := len(x.Line); n < 0 || n > 4 {
		return fmt.Errorf("SUMMARY-RECORD: LINE occurs 0 to 4 times and the record holds %d occurrences of it", n)
	}
	for i0 := range x.Line {
		if err = w.WriteAlphanumeric(x.Line[i0].LineText, 3); err != nil {
			return fmt.Errorf("SUMMARY-RECORD: writing LINE-TEXT in occurrence %d of LINE: %w", i0, err)
		}
	}

	if n := len(x.Note); n < 0 || n > 4 {
		return fmt.Errorf("SUMMARY-RECORD: NOTE occurs 0 to 4 times and the record holds %d occurrences of it", n)
	}
	for i0 := range x.Note {
		if err = w.WriteAlphanumeric(x.Note[i0].NoteText, 2); err != nil {
			return fmt.Errorf("SUMMARY-RECORD: writing NOTE-TEXT in occurrence %d of NOTE: %w", i0, err)
		}
	}

	return nil
}
