// Code generated by cpybkc-gen-go. DO NOT EDIT.

package counted

// HeaderRecord is the HEADER-RECORD record, as docs/ir/SPEC.md resolved it.
type HeaderRecord struct {
	// TypeCode is TYPE-CODE — alphanumeric, DISPLAY, 1 byte.
	TypeCode string

	// DtlCount is DTL-COUNT — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	DtlCount int32

	// SumFlag is SUM-FLAG — alphanumeric, DISPLAY, 1 byte.
	SumFlag string

	// TotalCount is TOTAL-COUNT — numeric, DISPLAY, 2 digits, unsigned, 2 bytes.
	TotalCount int32
}

// DetailRecord is the DETAIL-RECORD record, as docs/ir/SPEC.md resolved it.
type DetailRecord struct {
	// TypeCode is TYPE-CODE — alphanumeric, DISPLAY, 1 byte.
	TypeCode string

	// Amount is AMOUNT — numeric, PACKED-DECIMAL, 5 digits, signed, 3 bytes.
	// The value is unscaled: the item's value is this field times 10^-2.
	Amount int32
}

// SummaryRecord is the SUMMARY-RECORD record, as docs/ir/SPEC.md resolved it.
type SummaryRecord struct {
	// TypeCode is TYPE-CODE — alphanumeric, DISPLAY, 1 byte.
	TypeCode string

	// Line is LINE — a group of 1 member, OCCURS 0 TO 4 DEPENDING ON a register an earlier record bound.
	Line []struct {
		// LineText is LINE-TEXT — alphanumeric, DISPLAY, 3 bytes.
		LineText string
	}

	// Note is NOTE — a group of 1 member, OCCURS 0 TO 4 DEPENDING ON a register an earlier record bound.
	Note []struct {
		// NoteText is NOTE-TEXT — alphanumeric, DISPLAY, 2 bytes.
		NoteText string
	}
}
