// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The record tier of this package's generated tests: one case per record the
// layout describes, and one per arm of an alternation inside one.
//
// Each case carries the bytes it reads as a literal, decodes them, checks every
// field against the value the literal was laid out with, and writes the record
// back out byte for byte. The bytes are synthesized from the layout rather than
// read from a file, so they are what to hold against the file on your desk: the
// comment column names the item, the offset summed from the widths ahead of it,
// and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports counted.
package counted_test

import (
	"bytes"
	"github.com/Zaba505/cobol-go/codec"
	"github.com/Zaba505/cpybkc/cmd/cpybkc-gen-go/internal/counted"
	"testing"
)

// TestHeaderRecordReadsBackTheBytesItWasReadFrom is HEADER-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestHeaderRecordReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc8,       // TYPE-CODE @0 X(1)
		0xf0, 0xf2, // DTL-COUNT @1 9(2)
		0xc4,       // SUM-FLAG @3 X(1)
		0xf0, 0xf5, // TOTAL-COUNT @4 9(2)
	}

	r, err := codec.NewReader(bytes.NewReader(in), counted.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record counted.HeaderRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.TypeCode != "H" {
		t.Errorf("TYPE-CODE: got %q, want %q", record.TypeCode, "H")
	}

	if record.DtlCount != 2 {
		t.Errorf("DTL-COUNT: got %d, want %d", record.DtlCount, 2)
	}

	if record.SumFlag != "D" {
		t.Errorf("SUM-FLAG: got %q, want %q", record.SumFlag, "D")
	}

	if record.TotalCount != 5 {
		t.Errorf("TOTAL-COUNT: got %d, want %d", record.TotalCount, 5)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, counted.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestDetailRecordReadsBackTheBytesItWasReadFrom is DETAIL-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestDetailRecordReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc4,             // TYPE-CODE @0 X(1)
		0x00, 0x00, 0x2d, // AMOUNT @1 S9(3)V9(2) PACKED-DECIMAL
	}

	r, err := codec.NewReader(bytes.NewReader(in), counted.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record counted.DetailRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.TypeCode != "D" {
		t.Errorf("TYPE-CODE: got %q, want %q", record.TypeCode, "D")
	}

	if record.Amount != -2 {
		t.Errorf("AMOUNT: got %d, want %d", record.Amount, -2)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, counted.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestSummaryRecordReadsBackTheBytesItWasReadFrom is SUMMARY-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestSummaryRecordReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xe2, // TYPE-CODE @0 X(1)
	}

	r, err := codec.NewReader(bytes.NewReader(in), counted.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record counted.SummaryRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.TypeCode != "S" {
		t.Errorf("TYPE-CODE: got %q, want %q", record.TypeCode, "S")
	}

	if len(record.Line) != 0 {
		t.Fatalf("LINE: got %d occurrences, want %d", len(record.Line), 0)
	}

	if len(record.Note) != 0 {
		t.Fatalf("NOTE: got %d occurrences, want %d", len(record.Note), 0)
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, counted.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
