// Copyright (c) 2026 Richard Carson Derr
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"testing"

	"github.com/Zaba505/cpybkc/internal/generate"
	"github.com/Zaba505/cpybkc/internal/plugin"
)

// The project every test below generates from: one fixed-length record type,
// small enough to read and complete enough to resolve.
//
// The copybook is fixed-format COBOL, six columns of sequence area in front of
// every line, because that is what cpybkc reads and what a copybook out of a
// mainframe library is written in.
const (
	testLayout = `(encoding
  (charset ascii)
  (sign-convention ascii-zone-37)
  (byte-order big-endian)
  (float-format ieee-754))

(framing (recfm F) (lrecl 7))

(record ORDER (copybook "cpy/orders.cpy" ORDER-REC))

(discriminate ORDER single-record-type)

(sequence (* ORDER))
`

	testCopybook = "      01  ORDER-REC.\n" +
		"          05  ORDER-ID   PIC X(4).\n" +
		"          05  ORDER-QTY  PIC 9(3).\n"
)

// generator is a whole generator, as a shell script.
//
// It is a real process started by a real PATH search — docs/plugin/SPEC.md
// makes a generator an executable and says nothing about what it is written in,
// and a shell script is the smallest thing that can be one. It reads the vector
// the contract fixes, writes one source file, and copies the descriptor it was
// handed into its output directory so that a test can compare the bytes two
// generators of one run received.
func generatorScript(name string) string {
	return `#!/bin/sh
set -e
while [ $# -gt 0 ]; do
  case "$1" in
    --descriptor) descriptor="$2"; shift 2 ;;
    --out) out="$2"; shift 2 ;;
    --opt) options="$options $2"; shift 2 ;;
    *) shift ;;
  esac
done
cp "$descriptor" "$out/` + name + `.ir"
printf 'generated by ` + name + `%s\n' "$options" > "$out/` + name + `.txt"
`
}

// install writes a generator onto a directory that will be this run's PATH.
func install(t *testing.T, bin, name, body string) {
	t.Helper()

	path := filepath.Join(bin, plugin.Filename(name))
	if err := writeGenerator(path, body); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}

// writeGenerator writes an executable plugin, under [syscall.ForkLock] held for
// reading.
//
// The lock is the whole point of this function existing rather than the
// [os.WriteFile] it wraps, and internal/generate/generate_test.go's generator
// carries the same treatment for the same reason: a fork made anywhere in this
// process while the script is open for writing hands the child a copy of that
// descriptor, and the child holds it until it execs — so an exec of the script
// inside that window fails with ETXTBSY (golang/go#22315).
//
// Every test in this package writes a generator and runs one, so the window is
// real, and it is CI — more tests running than the machine has cores — that
// finds it. Seen as `fork/exec …/cpybkc-gen-go: text file busy` from a
// generator the run had just installed, which reads like a fault in the code
// under test and is a fault in the test's own setup.
func writeGenerator(path, body string) error {
	syscall.ForkLock.RLock()
	defer syscall.ForkLock.RUnlock()

	return os.WriteFile(path, []byte(body), 0o755)
}

// projectIn writes a whole project — the manifest, the layout it names and the
// copybook the layout names — and hands back the directory holding it.
func projectIn(t *testing.T, generators string) string {
	t.Helper()

	dir := t.TempDir()

	writeFile(t, filepath.Join(dir, "cpy", "orders.cpy"), testCopybook)
	writeFile(t, filepath.Join(dir, "orders.sexpr"), testLayout)
	writeFile(t, filepath.Join(dir, "cpybkc.json"),
		`{"layout": "orders.sexpr", "generators": `+generators+`}`)

	return dir
}

// writeFile puts a file where a test needs one, making the directory above it.
func writeFile(t *testing.T, path, body string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("making %s: %v", filepath.Dir(path), err)
	}

	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}

// generateIn runs one whole invocation against the project in dir, with bin at
// the front of PATH.
//
// bin leads rather than replacing PATH because a generator here is a shell
// script and a shell script needs the commands it calls; the search takes the
// earliest match, so the generators this test installed are the ones found
// whatever else is on the machine. It also means these tests cannot be
// parallel, which is what t.Setenv already enforces.
func generateIn(t *testing.T, dir, bin string, args ...string) (stdout, stderr string, code status) {
	t.Helper()

	t.Setenv("PATH", bin+string(os.PathListSeparator)+os.Getenv("PATH"))

	var out, errs bytes.Buffer

	code = run(context.Background(),
		append([]string{manifestFlag, filepath.Join(dir, "cpybkc.json")}, args...), &out, &errs)

	return out.String(), errs.String(), code
}

// tree is every regular file under dir, by slash-separated path relative to it,
// with the SHA-256 of its contents.
//
// It is a hash rather than the bytes so that a failure names the file that
// differs rather than printing a descriptor at somebody.
func tree(t *testing.T, dir string) map[string]string {
	t.Helper()

	found := map[string]string{}

	err := filepath.WalkDir(dir, func(path string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}

		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		sum := sha256.Sum256(body)
		found[filepath.ToSlash(rel)] = hex.EncodeToString(sum[:])

		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v", dir, err)
	}

	return found
}

// paths is the paths of a tree, sorted, for a message naming what is there.
func paths(found map[string]string) string {
	names := make([]string, 0, len(found))
	for name := range found {
		names = append(names, name)
	}

	sort.Strings(names)

	return strings.Join(names, ", ")
}

// TestARunGeneratesThroughRealGeneratorProcesses is the end-to-end criterion:
// a fixture manifest, a layout, a copybook, two generators that are actual
// executables found on PATH, and the file tree they produced.
//
// It also asserts the equality docs/cli/SPEC.md and the plugin contract both
// rest reproducibility on, in its strong form: every generator of one run is
// handed **the same bytes**, not a descriptor assembled the same way. Each
// generator copies the descriptor it was given, and the two copies are compared.
func TestARunGeneratesThroughRealGeneratorProcesses(t *testing.T) {
	bin := t.TempDir()
	install(t, bin, "one", generatorScript("one"))
	install(t, bin, "two", generatorScript("two"))

	dir := projectIn(t, `[
	  {"name": "one", "out": "gen", "options": {"package_name": "orders"}},
	  {"name": "two", "out": "gen"}
	]`)

	stdout, stderr, code := generateIn(t, dir, bin)

	if code != statusOK {
		t.Fatalf("the run exited %d, want %d:\n%s", code, statusOK, stderr)
	}

	// docs/cli/SPEC.md: a run that generates writes nothing to standard output.
	// Silence is success, and the exit status is the verdict.
	if stdout != "" {
		t.Errorf("the run wrote %q to standard output, and a generating run writes nothing there", stdout)
	}

	found := tree(t, dir)

	for _, want := range []string{
		"gen/one.txt", "gen/two.txt", "gen/one.ir", "gen/two.ir", generate.RecordName,
	} {
		if _, made := found[want]; !made {
			t.Errorf("the run produced no %s; it produced %s", want, paths(found))
		}
	}

	// The strong form of the equality: the same bytes, because there is one
	// descriptor and one encoder.
	if found["gen/one.ir"] != found["gen/two.ir"] {
		t.Error("two generators of one run were handed different descriptors")
	}

	// The options the manifest declared reach the generator that declared them,
	// and only that one.
	one := read(t, filepath.Join(dir, "gen", "one.txt"))
	if !strings.Contains(one, "package_name=orders") {
		t.Errorf("the first generator was invoked as %q, want its option", one)
	}

	if two := read(t, filepath.Join(dir, "gen", "two.txt")); strings.Contains(two, "package_name") {
		t.Errorf("the second generator was invoked as %q, and it declared no options", two)
	}
}

// TestARunIsAFunctionOfItsInputs is #47 through the whole command: the same
// project generated twice produces a byte-identical tree.
func TestARunIsAFunctionOfItsInputs(t *testing.T) {
	bin := t.TempDir()
	install(t, bin, "one", generatorScript("one"))

	dir := projectIn(t, `[{"name": "one", "out": "gen"}]`)

	if _, stderr, code := generateIn(t, dir, bin); code != statusOK {
		t.Fatalf("the first run exited %d:\n%s", code, stderr)
	}

	first := tree(t, dir)

	if _, stderr, code := generateIn(t, dir, bin); code != statusOK {
		t.Fatalf("the second run exited %d:\n%s", code, stderr)
	}

	second := tree(t, dir)

	if len(first) != len(second) {
		t.Fatalf("the two runs produced %s and %s", paths(first), paths(second))
	}

	for path, sum := range first {
		if second[path] != sum {
			t.Errorf("%s differs between two runs over the same inputs", path)
		}
	}
}

// TestAStaleGeneratedFileIsPruned is #45 reached through the CLI: the record a
// run leaves at the project's root is what lets the next one remove a file it
// no longer produces, and a project's root is the directory holding its
// manifest.
func TestAStaleGeneratedFileIsPruned(t *testing.T) {
	bin := t.TempDir()
	install(t, bin, "one", generatorScript("one"))

	dir := projectIn(t, `[{"name": "one", "out": "gen"}]`)

	if _, stderr, code := generateIn(t, dir, bin); code != statusOK {
		t.Fatalf("the first run exited %d:\n%s", code, stderr)
	}

	if _, err := os.Stat(filepath.Join(dir, "gen", "one.txt")); err != nil {
		t.Fatalf("the first run produced nothing to go stale: %v", err)
	}

	// The generator is replaced by one producing a different file, which is
	// what a record removed from a layout looks like from the output tree's
	// side.
	install(t, bin, "one", generatorScript("later"))

	if _, stderr, code := generateIn(t, dir, bin); code != statusOK {
		t.Fatalf("the second run exited %d:\n%s", code, stderr)
	}

	if _, err := os.Stat(filepath.Join(dir, "gen", "one.txt")); !os.IsNotExist(err) {
		t.Errorf("the file the first run generated is still there: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "gen", "later.txt")); err != nil {
		t.Errorf("the second run generated nothing: %v", err)
	}
}

// TestAHandWrittenFileIsNotPruned is the other half of the same rule, and the
// one that matters: the record is the only source, so a file no run wrote is a
// file cpybkc has no claim on.
func TestAHandWrittenFileIsNotPruned(t *testing.T) {
	bin := t.TempDir()
	install(t, bin, "one", generatorScript("one"))

	dir := projectIn(t, `[{"name": "one", "out": "."}]`)

	writeFile(t, filepath.Join(dir, "mine.txt"), "a person wrote this\n")

	if _, stderr, code := generateIn(t, dir, bin); code != statusOK {
		t.Fatalf("the first run exited %d:\n%s", code, stderr)
	}

	install(t, bin, "one", generatorScript("later"))

	if _, stderr, code := generateIn(t, dir, bin); code != statusOK {
		t.Fatalf("the second run exited %d:\n%s", code, stderr)
	}

	if body := read(t, filepath.Join(dir, "mine.txt")); body != "a person wrote this\n" {
		t.Errorf("a hand-written file read back as %q", body)
	}
}

// TestEveryFailureModeExitsOneAndReportsThroughTheDiagnosticPath is the
// criterion stated as a table: each fault docs/cli/SPEC.md files under status 1
// exits 1, writes nothing to standard output, and comes out on standard error as
// a diagnostic rather than as usage.
func TestEveryFailureModeExitsOneAndReportsThroughTheDiagnosticPath(t *testing.T) {
	for name, test := range map[string]struct {
		project    func(t *testing.T, bin string) string
		names      string
		untouched  bool
		generators string
	}{
		"the manifest is not there": {
			project: func(t *testing.T, _ string) string {
				t.Helper()

				return t.TempDir()
			},
			names: "cpybkc.json",
		},
		"the manifest does not parse": {
			project: func(t *testing.T, _ string) string {
				t.Helper()

				dir := t.TempDir()
				writeFile(t, filepath.Join(dir, "cpybkc.json"), "{not json")

				return dir
			},
		},
		"the layout is not there": {
			project: func(t *testing.T, _ string) string {
				t.Helper()

				dir := t.TempDir()
				writeFile(t, filepath.Join(dir, "cpybkc.json"),
					`{"layout": "nowhere.sexpr", "generators": [{"name": "one", "out": "gen"}]}`)

				return dir
			},
			names: "nowhere.sexpr",
		},
		"the layout does not resolve": {
			project: func(t *testing.T, _ string) string {
				t.Helper()

				dir := t.TempDir()
				writeFile(t, filepath.Join(dir, "cpy", "orders.cpy"), testCopybook)
				writeFile(t, filepath.Join(dir, "orders.sexpr"),
					strings.Replace(testLayout, "ORDER-REC", "NOT-A-RECORD", 1))
				writeFile(t, filepath.Join(dir, "cpybkc.json"),
					`{"layout": "orders.sexpr", "generators": [{"name": "one", "out": "gen"}]}`)

				return dir
			},
			names: "NOT-A-RECORD",
		},
		"a copybook is not there": {
			project: func(t *testing.T, _ string) string {
				t.Helper()

				dir := t.TempDir()
				writeFile(t, filepath.Join(dir, "orders.sexpr"), testLayout)
				writeFile(t, filepath.Join(dir, "cpybkc.json"),
					`{"layout": "orders.sexpr", "generators": [{"name": "one", "out": "gen"}]}`)

				return dir
			},
			names: "cpy/orders.cpy",
		},
		"a generator is not on PATH": {
			project: func(t *testing.T, _ string) string {
				t.Helper()

				return projectIn(t, `[{"name": "nowhere", "out": "gen"}]`)
			},
			names:     plugin.Filename("nowhere"),
			untouched: true,
		},
		"a generator exits non-zero": {
			project: func(t *testing.T, bin string) string {
				t.Helper()

				install(t, bin, "one", "#!/bin/sh\necho 'error: I refuse' >&2\nexit 3\n")

				return projectIn(t, `[{"name": "one", "out": "gen"}]`)
			},
			untouched: true,
		},
		"two generators collide on one path": {
			project: func(t *testing.T, bin string) string {
				t.Helper()

				install(t, bin, "one", generatorScript("both"))
				install(t, bin, "two", generatorScript("both"))

				return projectIn(t, `[{"name": "one", "out": "gen"}, {"name": "two", "out": "gen"}]`)
			},
			untouched: true,
		},
	} {
		t.Run(name, func(t *testing.T) {
			bin := t.TempDir()
			dir := test.project(t, bin)

			stdout, stderr, code := generateIn(t, dir, bin)

			if code != statusFailed {
				t.Fatalf("%s exited %d, want %d:\n%s", name, code, statusFailed, stderr)
			}

			if stdout != "" {
				t.Errorf("%s wrote %q to standard output", name, stdout)
			}

			if !strings.HasPrefix(stderr, severityError+severitySeparator) {
				t.Errorf("%s reported %q, want an %s%s line", name, stderr, severityError, severitySeparator)
			}

			// A fault in the work is not a fault in the vector, so the command
			// set is not what the reader needs in front of them.
			if strings.Contains(stderr, "Usage:") {
				t.Errorf("%s was answered with usage: %q", name, stderr)
			}

			if test.names != "" && !strings.Contains(stderr, test.names) {
				t.Errorf("%s does not name %s: %q", name, test.names, stderr)
			}

			// docs/plugin/SPEC.md: nothing reaches the project's tree unless
			// every generator succeeded, so a run that failed after resolving
			// leaves the tree exactly as it found it.
			if test.untouched {
				if _, err := os.Stat(filepath.Join(dir, "gen")); !os.IsNotExist(err) {
					t.Errorf("%s left an output directory behind: %v", name, err)
				}

				if _, err := os.Stat(filepath.Join(dir, generate.RecordName)); !os.IsNotExist(err) {
					t.Errorf("%s left a record behind: %v", name, err)
				}
			}
		})
	}
}

// TestAGeneratorsOwnLinesAreRelayedAndAttributed is the seam between this
// command and the plugin contract, reached the way an adopter reaches it: a
// generator writes a diagnostic, and it comes out on cpybkc's standard error at
// the same severity with the generator's name between the severity and the
// message.
func TestAGeneratorsOwnLinesAreRelayedAndAttributed(t *testing.T) {
	bin := t.TempDir()
	install(t, bin, "one", "#!/bin/sh\necho 'warning: nothing to do' >&2\nexit 0\n")

	dir := projectIn(t, `[{"name": "one", "out": "gen"}]`)

	_, stderr, code := generateIn(t, dir, bin)

	if code != statusOK {
		t.Fatalf("the run exited %d, want %d:\n%s", code, statusOK, stderr)
	}

	want := severityWarning + severitySeparator + "one" + severitySeparator + "nothing to do\n"
	if !strings.Contains(stderr, want) {
		t.Errorf("the generator's line came out as %q, want %q", stderr, want)
	}
}

// TestACancelledRunFailsAndSaysSo is docs/cli/SPEC.md's cancellation rule at
// the point it is decided: a run whose context is done is reported as a
// cancelled run rather than as whatever the stage it interrupted made of it,
// and a cancelled run is a failed run.
func TestACancelledRunFailsAndSaysSo(t *testing.T) {
	bin := t.TempDir()
	install(t, bin, "one", "#!/bin/sh\nsleep 30\n")

	dir := projectIn(t, `[{"name": "one", "out": "gen"}]`)

	t.Setenv("PATH", bin+string(os.PathListSeparator)+os.Getenv("PATH"))

	ctx, cancel := context.WithCancelCause(context.Background())
	cancel(errCancelled)

	var out, errs bytes.Buffer

	code := run(ctx, []string{manifestFlag, filepath.Join(dir, "cpybkc.json")}, &out, &errs)

	if code != statusFailed {
		t.Fatalf("a cancelled run exited %d, want %d:\n%s", code, statusFailed, errs.String())
	}

	if !strings.Contains(errs.String(), errCancelled.Error()) {
		t.Errorf("a cancelled run reported %q, want it to say the run was cancelled", errs.String())
	}

	// It leaves the project's output tree exactly as it found it.
	if _, err := os.Stat(filepath.Join(dir, "gen")); !os.IsNotExist(err) {
		t.Errorf("a cancelled run left an output directory behind: %v", err)
	}
}

// TestCancellableStopsAtTheFirstSignal is the other half of cancellation: the
// context is cancelled with the cause the diagnostic is written from, and the
// notification is released so that a second signal takes its default
// disposition.
func TestCancellableStopsAtTheFirstSignal(t *testing.T) {
	ctx, stop := cancellable(context.Background())
	defer stop()

	if ctx.Err() != nil {
		t.Fatalf("the context is done before anything was signalled: %v", ctx.Err())
	}

	process, err := os.FindProcess(os.Getpid())
	if err != nil {
		t.Fatalf("finding this process: %v", err)
	}

	if err := process.Signal(signalled[0]); err != nil {
		t.Fatalf("signalling this process: %v", err)
	}

	<-ctx.Done()

	if cause := context.Cause(ctx); cause != errCancelled {
		t.Errorf("the run was cancelled with %v, want %v", cause, errCancelled)
	}
}

// read is a file a test asserts about.
func read(t *testing.T, path string) string {
	t.Helper()

	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}

	return string(body)
}
