// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The record tier of this package's generated tests: one case per record the
// layout describes, and one per arm of an alternation inside one.
//
// Each case carries the bytes it reads as a literal, decodes them, checks every
// field against the value the literal was laid out with, and writes the record
// back out byte for byte. The bytes are synthesized from the layout rather than
// read from a file, so they are what to hold against the file on your desk: the
// comment column names the item, the offset summed from the widths ahead of it,
// and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports batched.
package batched_test

import (
	"bytes"
	"github.com/Zaba505/cobol-go/codec"
	"github.com/Zaba505/cpybkc/cmd/cpybkc-gen-go/internal/batched"
	"testing"
)

// TestBatchHeaderReadsBackTheBytesItWasReadFrom is BATCH-HEADER: the bytes
// below, every field they decode into, and the same bytes written back.
func TestBatchHeaderReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc8, 0xc4, // HDR-TYPE @0 X(2)
		0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, // HDR-NAME @2 X(18)
		0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, //
		0xc3, 0xc3, //
	}

	r, err := codec.NewReader(bytes.NewReader(in), batched.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record batched.BatchHeader

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.HdrType != "HD" {
		t.Errorf("HDR-TYPE: got %q, want %q", record.HdrType, "HD")
	}

	if record.HdrName != "CCCCCCCCCCCCCCCCCC" {
		t.Errorf("HDR-NAME: got %q, want %q", record.HdrName, "CCCCCCCCCCCCCCCCCC")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, batched.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestBatchDetailReadsBackTheBytesItWasReadFrom is BATCH-DETAIL: the bytes
// below, every field they decode into, and the same bytes written back.
func TestBatchDetailReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, 0xc1, // DTL-ACCOUNT @0 X(10)
		0xc1, 0xc1, //
		0xc4, 0xe3, // DTL-TYPE @10 X(2)
		0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, // DTL-MEMO @12 X(8)
	}

	r, err := codec.NewReader(bytes.NewReader(in), batched.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record batched.BatchDetail

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.DtlAccount != "AAAAAAAAAA" {
		t.Errorf("DTL-ACCOUNT: got %q, want %q", record.DtlAccount, "AAAAAAAAAA")
	}

	if record.DtlType != "DT" {
		t.Errorf("DTL-TYPE: got %q, want %q", record.DtlType, "DT")
	}

	if record.DtlMemo != "MMMMMMMM" {
		t.Errorf("DTL-MEMO: got %q, want %q", record.DtlMemo, "MMMMMMMM")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, batched.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
