// Code generated by cpybkc-gen-go. DO NOT EDIT.

package batched

// BatchHeader is the BATCH-HEADER record, as docs/ir/SPEC.md resolved it.
type BatchHeader struct {
	// HdrType is HDR-TYPE — alphanumeric, DISPLAY, 2 bytes.
	HdrType string

	// HdrName is HDR-NAME — alphanumeric, DISPLAY, 18 bytes.
	HdrName string
}

// BatchDetail is the BATCH-DETAIL record, as docs/ir/SPEC.md resolved it.
type BatchDetail struct {
	// DtlAccount is DTL-ACCOUNT — alphanumeric, DISPLAY, 10 bytes.
	DtlAccount string

	// DtlType is DTL-TYPE — alphanumeric, DISPLAY, 2 bytes.
	DtlType string

	// DtlMemo is DTL-MEMO — alphanumeric, DISPLAY, 8 bytes.
	DtlMemo string
}
