// Code generated by cpybkc-gen-go. DO NOT EDIT.

package signs

import (
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
)

// Encoding is the encoding the layout this package was generated from states for
// its files: the four byte axes it declares — charset, zoned sign convention,
// byte order and floating-point format — and the binary width staircase the
// copybook's items were laid out under.
//
// It is what [NewReader] and [NewWriter] build under when handed no [Option],
// and each option replaces one of the four axes a layout states and no other.
//
// It is also what a record's own methods are used with. They are codec's
// Unmarshaler and Marshaler, so a caller reading or writing one record at a time
// builds the codec.Reader or codec.Writer they are handed from it:
//
//	r, err := codec.NewReader(f, Encoding())
//
// It is a default in a sense codec does not have one. codec knows nothing about
// the file, so none of the five has a default there, and every one of them fails
// silently when wrong. This package does know: the layout it was generated from
// states all four byte axes with no default for any, and resolve put the
// staircase into the descriptor. So what this returns is not a guess about the
// file — it is the one thing this package was generated from.
//
// Binary is the odd one. The other four say how a byte becomes a value; this one
// says how many bytes a COMP item is, which is a property of the compiler that
// wrote the file rather than of the copybook — PIC S9(2) COMP is two bytes under
// IBM Enterprise COBOL and one under GnuCOBOL's default. It is the staircase the
// offsets in these records were computed under, so changing it does not
// reinterpret the file, it describes a different one — and one this package
// refuses. No option replaces it, and a record's own methods handed a
// codec.Reader or codec.Writer carrying another refuse it before any byte is read
// or written, naming both staircases.
//
// A file this descriptor describes that was converted to another character set is
// read under other axes, not by regenerating: the four axes a layout states may
// each be replaced, and every literal this package compares a field against — a
// record's type code, an arm's, a guard's — is re-expressed under them once,
// before the first record is read or written, as a file under them spells it. An
// item whose charset is none carries bytes rather than characters, and its
// literals never move. A literal no file under the axes asked for can hold — a
// character the charset has no byte for, a sign byte in no column of the
// convention it was resolved under, a float the format cannot hold exactly, two
// literals that come to one byte string — is refused when the reader or writer is
// built, naming the literal, the item, the record and the axis.
func Encoding() codec.Encoding {
	return codec.Encoding{
		Charset:   codec.CP037(),
		Sign:      codec.SignEBCDIC,
		ByteOrder: binary.BigEndian,
		Float:     codec.FloatHFP,
		Binary:    codec.BinarySize248,
	}
}

// refuseStaircase refuses a binary width staircase that is not Encoding's.
//
// Every offset this package slices at — an item's, a predicate's window, a
// variant's occurrence, a run of slack — was computed when it was generated,
// under [codec.BinarySize248]. The four axes a layout states may be replaced
// by the caller; the staircase may not, because a different one does not read
// the same file another way, it puts every item behind a binary item at an
// offset nothing here computed, and nothing in the record disagrees. So it is
// refused before any byte is read or written, rather than reported later as a
// fault in data that was never at fault.
//
// It compares staircases and never whole encodings: a caller's Charset need
// not be comparable, and a comparison of two Encodings holding one would
// panic.
func refuseStaircase(binary codec.BinarySize) error {
	if binary == codec.BinarySize248 {
		return nil
	}

	return fmt.Errorf("the encoding's binary width staircase is %s, and this package's offsets were computed under the descriptor's, %s: the staircase is not an axis a caller may replace, because every item behind a binary item would be read or written at an offset nothing here computed", binary, codec.BinarySize248)
}

// Every record reads and writes itself, which is codec's Unmarshaler and
// Marshaler. Asserted here so that a drift in either interface fails in the
// file that implements it.
var (
	_ codec.Unmarshaler = (*TextRecord)(nil)
	_ codec.Marshaler   = (*TextRecord)(nil)
	_ codec.Unmarshaler = (*PositiveRecord)(nil)
	_ codec.Marshaler   = (*PositiveRecord)(nil)
	_ codec.Unmarshaler = (*NegativeRecord)(nil)
	_ codec.Marshaler   = (*NegativeRecord)(nil)
	_ codec.Unmarshaler = (*CountRecord)(nil)
	_ codec.Marshaler   = (*CountRecord)(nil)
)

// UnmarshalCOBOL reads one TEXT-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
//
// The binary width staircase is the one of the five r may not replace: every
// offset here was computed under Encoding's, and r's is refused where it is
// another, before any item is read.
func (x *TextRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	// Every offset below was computed under the descriptor's binary width
	// staircase, so r's encoding is refused where it carries another.
	if err = refuseStaircase(r.Encoding().Binary); err != nil {
		return err
	}

	if x.Code, err = r.ReadAlphanumeric(1); err != nil {
		return fmt.Errorf("TEXT-RECORD: reading CODE: %w", err)
	}

	if x.TextNote, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("TEXT-RECORD: reading TEXT-NOTE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this TEXT-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
//
// The binary width staircase is not the caller's either: every offset here was
// computed under Encoding's, and w's is refused where it is another, before
// any item is written.
func (x *TextRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	// Every offset below was computed under the descriptor's binary width
	// staircase, so w's encoding is refused where it carries another.
	if err = refuseStaircase(w.Encoding().Binary); err != nil {
		return err
	}

	if err = w.WriteAlphanumeric(x.Code, 1); err != nil {
		return fmt.Errorf("TEXT-RECORD: writing CODE: %w", err)
	}

	if err = w.WriteAlphanumeric(x.TextNote, 4); err != nil {
		return fmt.Errorf("TEXT-RECORD: writing TEXT-NOTE: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one POSITIVE-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
//
// The binary width staircase is the one of the five r may not replace: every
// offset here was computed under Encoding's, and r's is refused where it is
// another, before any item is read.
func (x *PositiveRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	// Every offset below was computed under the descriptor's binary width
	// staircase, so r's encoding is refused where it carries another.
	if err = refuseStaircase(r.Encoding().Binary); err != nil {
		return err
	}

	if x.Kind, err = r.ReadZonedInt32(1, codec.SignTrailing); err != nil {
		return fmt.Errorf("POSITIVE-RECORD: reading KIND: %w", err)
	}

	if x.PositiveNote, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("POSITIVE-RECORD: reading POSITIVE-NOTE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this POSITIVE-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
//
// The binary width staircase is not the caller's either: every offset here was
// computed under Encoding's, and w's is refused where it is another, before
// any item is written.
func (x *PositiveRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	// Every offset below was computed under the descriptor's binary width
	// staircase, so w's encoding is refused where it carries another.
	if err = refuseStaircase(w.Encoding().Binary); err != nil {
		return err
	}

	if err = w.WriteZonedInt32(x.Kind, 1, codec.SignTrailing); err != nil {
		return fmt.Errorf("POSITIVE-RECORD: writing KIND: %w", err)
	}

	if err = w.WriteAlphanumeric(x.PositiveNote, 4); err != nil {
		return fmt.Errorf("POSITIVE-RECORD: writing POSITIVE-NOTE: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one NEGATIVE-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
//
// The binary width staircase is the one of the five r may not replace: every
// offset here was computed under Encoding's, and r's is refused where it is
// another, before any item is read.
func (x *NegativeRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	// Every offset below was computed under the descriptor's binary width
	// staircase, so r's encoding is refused where it carries another.
	if err = refuseStaircase(r.Encoding().Binary); err != nil {
		return err
	}

	if x.Kind, err = r.ReadZonedInt32(1, codec.SignTrailing); err != nil {
		return fmt.Errorf("NEGATIVE-RECORD: reading KIND: %w", err)
	}

	if x.NegativeNote, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("NEGATIVE-RECORD: reading NEGATIVE-NOTE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this NEGATIVE-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
//
// The binary width staircase is not the caller's either: every offset here was
// computed under Encoding's, and w's is refused where it is another, before
// any item is written.
func (x *NegativeRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	// Every offset below was computed under the descriptor's binary width
	// staircase, so w's encoding is refused where it carries another.
	if err = refuseStaircase(w.Encoding().Binary); err != nil {
		return err
	}

	if err = w.WriteZonedInt32(x.Kind, 1, codec.SignTrailing); err != nil {
		return fmt.Errorf("NEGATIVE-RECORD: writing KIND: %w", err)
	}

	if err = w.WriteAlphanumeric(x.NegativeNote, 4); err != nil {
		return fmt.Errorf("NEGATIVE-RECORD: writing NEGATIVE-NOTE: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one COUNT-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
//
// The binary width staircase is the one of the five r may not replace: every
// offset here was computed under Encoding's, and r's is refused where it is
// another, before any item is read.
func (x *CountRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	// Every offset below was computed under the descriptor's binary width
	// staircase, so r's encoding is refused where it carries another.
	if err = refuseStaircase(r.Encoding().Binary); err != nil {
		return err
	}

	if x.Count, err = r.ReadBinaryInt16(4); err != nil {
		return fmt.Errorf("COUNT-RECORD: reading COUNT: %w", err)
	}

	if x.CountNote, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("COUNT-RECORD: reading COUNT-NOTE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this COUNT-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
//
// The binary width staircase is not the caller's either: every offset here was
// computed under Encoding's, and w's is refused where it is another, before
// any item is written.
func (x *CountRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	// Every offset below was computed under the descriptor's binary width
	// staircase, so w's encoding is refused where it carries another.
	if err = refuseStaircase(w.Encoding().Binary); err != nil {
		return err
	}

	if err = w.WriteBinaryInt16(x.Count, 4, codec.Signed); err != nil {
		return fmt.Errorf("COUNT-RECORD: writing COUNT: %w", err)
	}

	if err = w.WriteAlphanumeric(x.CountNote, 4); err != nil {
		return fmt.Errorf("COUNT-RECORD: writing COUNT-NOTE: %w", err)
	}

	return nil
}
