// Code generated by cpybkc-gen-go. DO NOT EDIT.

package signs

import (
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
)

// Encoding is the byte-level interpretation of the files these records live in:
// the five axes as they were resolved — four the layout declared, and the binary
// width staircase the copybook's items were laid out under.
//
// None of the five has a default and every one of them fails silently when
// wrong, so codec has no usable zero-value Reader and this function is how a
// caller states all five at once:
//
//	r, err := codec.NewReader(f, Encoding())
//
// Binary is the odd one. The other four say how a byte becomes a value; this one
// says how many bytes a COMP item is, which is a property of the compiler that
// wrote the file rather than of the copybook — PIC S9(2) COMP is two bytes under
// IBM Enterprise COBOL and one under GnuCOBOL's default. It is the staircase the
// offsets in these records were computed under, so changing it here does not
// reinterpret the file, it describes a different one.
//
// It is a value a caller passes rather than one anything applies on its own. A
// file this descriptor describes that was converted to another character set is
// read by passing a different Encoding, not by regenerating: the four axes a
// layout states may each be replaced, and every literal this package compares a
// field against — a record's type code, an arm's, a guard's — is re-expressed
// under them once, before the first record is read or written, as a file under
// them spells it. An item whose charset is none carries bytes rather than
// characters, and its literals never move. A literal no file under the axes
// asked for can hold — a character the charset has no byte for, a sign byte in
// no column of the convention it was resolved under, a float the format cannot
// hold exactly, two literals that come to one byte string — is refused when the
// reader or writer is built, naming the literal, the item, the record and the
// axis. Binary, the staircase, is not one of the four.
func Encoding() codec.Encoding {
	return codec.Encoding{
		Charset:   codec.CP037(),
		Sign:      codec.SignEBCDIC,
		ByteOrder: binary.BigEndian,
		Float:     codec.FloatHFP,
		Binary:    codec.BinarySize248,
	}
}

// Every record reads and writes itself, which is codec's Unmarshaler and
// Marshaler. Asserted here so that a drift in either interface fails in the
// file that implements it.
var (
	_ codec.Unmarshaler = (*TextRecord)(nil)
	_ codec.Marshaler   = (*TextRecord)(nil)
	_ codec.Unmarshaler = (*PositiveRecord)(nil)
	_ codec.Marshaler   = (*PositiveRecord)(nil)
	_ codec.Unmarshaler = (*NegativeRecord)(nil)
	_ codec.Marshaler   = (*NegativeRecord)(nil)
	_ codec.Unmarshaler = (*CountRecord)(nil)
	_ codec.Marshaler   = (*CountRecord)(nil)
)

// UnmarshalCOBOL reads one TEXT-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *TextRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.Code, err = r.ReadAlphanumeric(1); err != nil {
		return fmt.Errorf("TEXT-RECORD: reading CODE: %w", err)
	}

	if x.TextNote, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("TEXT-RECORD: reading TEXT-NOTE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this TEXT-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *TextRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteAlphanumeric(x.Code, 1); err != nil {
		return fmt.Errorf("TEXT-RECORD: writing CODE: %w", err)
	}

	if err = w.WriteAlphanumeric(x.TextNote, 4); err != nil {
		return fmt.Errorf("TEXT-RECORD: writing TEXT-NOTE: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one POSITIVE-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *PositiveRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.Kind, err = r.ReadZonedInt32(1, codec.SignTrailing); err != nil {
		return fmt.Errorf("POSITIVE-RECORD: reading KIND: %w", err)
	}

	if x.PositiveNote, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("POSITIVE-RECORD: reading POSITIVE-NOTE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this POSITIVE-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *PositiveRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteZonedInt32(x.Kind, 1, codec.SignTrailing); err != nil {
		return fmt.Errorf("POSITIVE-RECORD: writing KIND: %w", err)
	}

	if err = w.WriteAlphanumeric(x.PositiveNote, 4); err != nil {
		return fmt.Errorf("POSITIVE-RECORD: writing POSITIVE-NOTE: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one NEGATIVE-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *NegativeRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.Kind, err = r.ReadZonedInt32(1, codec.SignTrailing); err != nil {
		return fmt.Errorf("NEGATIVE-RECORD: reading KIND: %w", err)
	}

	if x.NegativeNote, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("NEGATIVE-RECORD: reading NEGATIVE-NOTE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this NEGATIVE-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *NegativeRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteZonedInt32(x.Kind, 1, codec.SignTrailing); err != nil {
		return fmt.Errorf("NEGATIVE-RECORD: writing KIND: %w", err)
	}

	if err = w.WriteAlphanumeric(x.NegativeNote, 4); err != nil {
		return fmt.Errorf("NEGATIVE-RECORD: writing NEGATIVE-NOTE: %w", err)
	}

	return nil
}

// UnmarshalCOBOL reads one COUNT-RECORD out of r, in the order docs/ir/SPEC.md
// resolved its items, and retains the bytes of every slack node it carries and
// of every item the copybook gives no data-name.
//
// It is codec's Unmarshaler. The Encoding is r's: the five axes are properties
// of the file in hand, and Encoding is what this descriptor resolved.
func (x *CountRecord) UnmarshalCOBOL(r *codec.Reader) error {
	var err error

	if x.Count, err = r.ReadBinaryInt16(4); err != nil {
		return fmt.Errorf("COUNT-RECORD: reading COUNT: %w", err)
	}

	if x.CountNote, err = r.ReadAlphanumeric(4); err != nil {
		return fmt.Errorf("COUNT-RECORD: reading COUNT-NOTE: %w", err)
	}

	return nil
}

// MarshalCOBOL writes this COUNT-RECORD into w, in the order docs/ir/SPEC.md
// resolved its items, emitting the bytes retained for every slack node and
// every unnamed item it carries, and zero bytes for one it does not.
//
// It is codec's Marshaler. Two values are the descriptor's rather than the
// caller's and are supplied rather than taken from the record: an OCCURS
// DEPENDING ON count is emitted as the number of occurrences written, and
// slack — and the bytes of an item the copybook gives no data-name — is
// emitted as what was retained for it. Everything else is the caller's,
// including the value a discriminator tests — a writer evaluates a predicate
// and never inverts one.
func (x *CountRecord) MarshalCOBOL(w *codec.Writer) error {
	var err error

	if err = w.WriteBinaryInt16(x.Count, 4, codec.Signed); err != nil {
		return fmt.Errorf("COUNT-RECORD: writing COUNT: %w", err)
	}

	if err = w.WriteAlphanumeric(x.CountNote, 4); err != nil {
		return fmt.Errorf("COUNT-RECORD: writing COUNT-NOTE: %w", err)
	}

	return nil
}
