// Code generated by cpybkc-gen-go. DO NOT EDIT.

package signs

import (
	"encoding/binary"
	"fmt"
	"github.com/Zaba505/cobol-go/codec"
	"slices"
	"strings"
	"sync/atomic"
)

// literals is every byte string this package compares a field against: the
// literals of a transition's predicate, of an arm's predicate and of a guard
// over a bytes register.
//
// Each is the bytes a file under the descriptor's own axes holds there, which
// is what resolvedLiterals holds them as. A reader or a writer built under
// other axes — a converted copy of the same file, say — compares against
// them as a file under those axes spells them instead, re-expressed once,
// before its first record, by literalsFor. See docs/ir/SPEC.md, "A consumer
// may read under other axes, and re-expresses what it compares".
type literals struct {
	// lit1 is what CODE of TEXT-RECORD is compared against: the literal "\xf5",
	// "5" under cp037.
	lit1 []byte

	// lit2 is what KIND of POSITIVE-RECORD is compared against: the literal
	// "\xc5".
	lit2 []byte

	// lit3 is what KIND of NEGATIVE-RECORD is compared against: the literal
	// "\xd5".
	lit3 []byte

	// lit4 is what COUNT of COUNT-RECORD is compared against: the literal
	// "\x00\a".
	lit4 []byte
}

// resolvedLiterals is every literal as the descriptor resolved it. A reader or
// a writer under the descriptor's own axes compares against these and nothing
// else.
var resolvedLiterals = literals{
	lit1: []byte("\xf5"),
	lit2: []byte("\xc5"),
	lit3: []byte("\xd5"),
	lit4: []byte("\x00\a"),
}

// resolvedAxes is enc with the four axes a layout states — charset, sign
// convention, byte order and float format — put back to the ones this
// descriptor resolved, which is the encoding every literal in resolvedLiterals
// is spelled under.
func resolvedAxes(enc codec.Encoding) codec.Encoding {
	enc.Charset = codec.CP037()
	enc.Sign = codec.SignEBCDIC
	enc.ByteOrder = binary.BigEndian
	enc.Float = codec.FloatHFP

	return enc
}

// heldLiterals is every re-expression this package has made, by the encoding
// it was made under. See reexpressedUnder.
var heldLiterals atomic.Pointer[[]reexpression[literals]]

// literalsFor is the literals as a file under enc spells them.
//
// Where enc is the descriptor's own on every axis an item compared here
// depends on — the charset, sign convention and byte order — that is
// resolvedLiterals, and nothing is re-expressed: the comparisons a reader and
// a writer make are the ones the descriptor resolved. Otherwise it is
// literalsUnder's answer, worked out the first time this package meets enc and
// held after that — so the record methods, which are handed an encoding on
// every call, re-express once per encoding rather than once per record. Asking
// costs the comparisons that decide whether enc moves anything and, where it
// does, one lookup.
//
// A literal that has no spelling under enc is refused here, which is before
// any record is read or written under it.
func literalsFor(enc codec.Encoding) (*literals, error) {
	from := resolvedAxes(enc)

	if sameCharset(enc.Charset, from.Charset) && enc.Sign == from.Sign && sameByteOrder(enc.ByteOrder, from.ByteOrder) {
		return &resolvedLiterals, nil
	}

	return reexpressedUnder(&heldLiterals, enc, literalsUnder)
}

// literalsUnder is every literal re-expressed under enc, each through the axes
// that reach the item it is compared against and no other: a literal whose
// item enc does not move is carried as it is, and never refused on its own
// account.
func literalsUnder(enc codec.Encoding) (*literals, error) {
	from := resolvedAxes(enc)
	l := resolvedLiterals

	var err error

	if l.lit1, err = reexpressText(l.lit1, from.Charset, enc.Charset); err != nil {
		return nil, cannotReexpress("the literal \"\\xf5\", \"5\" under cp037", "CODE", "TEXT-RECORD", err)
	}

	if l.lit2, err = reexpressZoned(l.lit2, from, enc, 0); err != nil {
		return nil, cannotReexpress("the literal \"\\xc5\"", "KIND", "POSITIVE-RECORD", err)
	}

	if l.lit3, err = reexpressZoned(l.lit3, from, enc, 0); err != nil {
		return nil, cannotReexpress("the literal \"\\xd5\"", "KIND", "NEGATIVE-RECORD", err)
	}

	l.lit4 = reexpressBinary(l.lit4, from.ByteOrder, enc.ByteOrder)

	// Pairs `resolve` proved apart under the descriptor's axes, whose proof a
	// re-expression does not carry: held to it again, under enc.
	if !literalsApart(l.lit1, 0, l.lit2, 0) {
		return nil, literalsNotApart(from, enc, "the literal \"\\xf5\", \"5\" under cp037", "CODE", "TEXT-RECORD", "the literal \"\\xc5\"", "KIND", "POSITIVE-RECORD")
	}
	if !literalsApart(l.lit1, 0, l.lit3, 0) {
		return nil, literalsNotApart(from, enc, "the literal \"\\xf5\", \"5\" under cp037", "CODE", "TEXT-RECORD", "the literal \"\\xd5\"", "KIND", "NEGATIVE-RECORD")
	}
	if !literalsApart(l.lit1, 0, l.lit4, 0) {
		return nil, literalsNotApart(from, enc, "the literal \"\\xf5\", \"5\" under cp037", "CODE", "TEXT-RECORD", "the literal \"\\x00\\a\"", "COUNT", "COUNT-RECORD")
	}
	if !literalsApart(l.lit2, 0, l.lit3, 0) {
		return nil, literalsNotApart(from, enc, "the literal \"\\xc5\"", "KIND", "POSITIVE-RECORD", "the literal \"\\xd5\"", "KIND", "NEGATIVE-RECORD")
	}
	if !literalsApart(l.lit2, 0, l.lit4, 0) {
		return nil, literalsNotApart(from, enc, "the literal \"\\xc5\"", "KIND", "POSITIVE-RECORD", "the literal \"\\x00\\a\"", "COUNT", "COUNT-RECORD")
	}
	if !literalsApart(l.lit3, 0, l.lit4, 0) {
		return nil, literalsNotApart(from, enc, "the literal \"\\xd5\"", "KIND", "NEGATIVE-RECORD", "the literal \"\\x00\\a\"", "COUNT", "COUNT-RECORD")
	}

	return &l, nil
}

// reexpression is one re-expression a package has made: the encoding it was
// made under, and what came of it — the literals, or the refusal.
//
// A refusal is held as well as a success. It is a statement about the
// descriptor and the encoding and about nothing a record holds, so the answer
// the second time is the answer the first time, and working it out again per
// record is exactly the per-record re-expression docs/ir/SPEC.md forbids.
type reexpression[T any] struct {
	enc  codec.Encoding
	lits *T
	err  error
}

// reexpressionsKept is how many encodings a package remembers re-expressing
// under.
//
// A process reading one file under one encoding needs one. The number is not a
// performance claim about anything larger — a process juggling more encodings
// than this at once re-expresses again when one falls out, which is correct
// and merely slower — and it is small because every lookup walks it.
const reexpressionsKept = 4

// reexpressedUnder is the literals under enc, re-expressed by under the first
// time a package meets enc and read back from cache every time after.
//
// It exists for the record-level methods. UnmarshalCOBOL and MarshalCOBOL are
// codec's interfaces and take nothing but a codec.Reader or codec.Writer, so
// there is nowhere to hand them literals a caller re-expressed once; what they
// have is the encoding, on every call. A file-level reader and writer
// re-express once, when they are built, and reach this for that one time —
// which is also what puts their encoding here before the first record-level
// call asks.
//
// The cache is a copy-on-write list behind one atomic pointer rather than a map
// behind a lock: an encoding is not a comparable key in general (see
// [sameAxes]), a lookup is on every record of a converted file and a store is
// on the first, and two goroutines that miss together both re-express and both
// store, which costs a repetition and nothing else — the answer is a function
// of the encoding, so either store is the right one.
func reexpressedUnder[T any](cache *atomic.Pointer[[]reexpression[T]], enc codec.Encoding, under func(codec.Encoding) (*T, error)) (*T, error) {
	if known := cache.Load(); known != nil {
		for _, one := range *known {
			if sameAxes(one.enc, enc) {
				return one.lits, one.err
			}
		}
	}

	lits, err := under(enc)

	next := []reexpression[T]{{enc: enc, lits: lits, err: err}}
	if known := cache.Load(); known != nil {
		next = append(next, (*known)[:min(len(*known), reexpressionsKept-1)]...)
	}

	cache.Store(&next)

	return lits, err
}

// sameAxes reports whether two encodings agree on the four axes a layout states
// — charset, sign convention, byte order and float format — which are the four
// a literal is re-expressed through.
//
// The staircase is not compared. It is not an axis a literal moves along
// (docs/ir/SPEC.md, "The staircase is not an axis a consumer may replace"), and
// refusing one that is not the descriptor's is a check of its own, not this.
func sameAxes(a, b codec.Encoding) bool {
	return a.Sign == b.Sign && a.Float == b.Float && sameCharset(a.Charset, b.Charset) && sameByteOrder(a.ByteOrder, b.ByteOrder)
}

// sameCharset reports whether two charsets spell every byte alike.
//
// Compared as values where Go can compare them, which is every charset codec
// ships and almost every other, and by what they do where it cannot. A charset
// is an interface a caller may implement, and Go compares two interface values
// holding the same dynamic type by comparing the values — which panics where
// that type holds a slice, a map or a func, and a caller's charset built around
// a lookup table is exactly that type. Answering "different" for it would
// re-express the literals on every record the record methods read, since those
// ask again on every call; answering with a panic would take down a reader for
// handing it an encoding codec itself accepts. So such a pair is compared by its
// name, its space and the character each of the 256 bytes spells, which is
// everything a re-expression reads of a charset.
func sameCharset(a, b codec.Charset) bool {
	if same, ok := compared(a, b); ok {
		return same
	}

	if a.Name() != b.Name() || a.Space() != b.Space() {
		return false
	}

	for c := range 256 {
		if a.ToUnicode(byte(c)) != b.ToUnicode(byte(c)) {
			return false
		}
	}

	return true
}

// sameByteOrder reports whether two byte orders put the bytes of a value in the
// same order.
//
// By what they do rather than by value, for the reason [sameCharset] falls back
// to it and one more: binary.NativeEndian is a type of its own that agrees with
// one of the other two, and a literal cares only which.
//
// The two are asked to read the same two bytes rather than to write a value,
// because the record methods ask this on every call and a buffer handed to an
// interface method escapes: reading a package-level array allocates nothing.
func sameByteOrder(a, b binary.ByteOrder) bool {
	return a.Uint16(byteOrderProbe[:]) == b.Uint16(byteOrderProbe[:])
}

// byteOrderProbe is the two bytes [sameByteOrder] reads: 1 under a
// little-endian order and 256 under a big-endian one.
var byteOrderProbe = [2]byte{1, 0}

// compared is a == b where Go can compare the two, and ok false where it
// cannot rather than a panic.
func compared(a, b any) (same, ok bool) {
	defer func() {
		if recover() != nil {
			same, ok = false, false
		}
	}()

	return a == b, true
}

// literalError is why one literal has no spelling under the axes asked for:
// the axis it could not cross, and what about the literal stopped it.
//
// It is not the refusal a caller sees. It knows the literal's bytes and the
// axes and nothing about where the literal is compared, which is what
// [cannotReexpress] adds.
type literalError struct {
	// axis is the axis the literal could not cross, spelled with the value
	// asked for — "the charset ASCII", "the sign convention realia".
	axis string

	// reason is what about the literal stopped it, as a clause following the
	// axis: "which has no byte for '€'".
	reason string
}

// Error implements the error interface.
func (e literalError) Error() string {
	return "under " + e.axis + ", " + e.reason
}

// cannotReexpress is the refusal of a reader or a writer over one literal that
// has no spelling under the axes it was built with.
//
// It names the literal, the field it is compared against, the record holding
// that field and the axis, and says what docs/ir/SPEC.md requires it to: that
// no file under those axes holds that value in that field. It says as plainly
// that it is not about a file's data, because it is raised before any record is
// read and the adopter meeting it has made no mistake in their data or their
// layout — they have asked for axes under which the layout's own distinction
// cannot be written down, and this is where they learn that rather than where
// they start looking for a corrupt record.
func cannotReexpress(literal, field, record string, err error) error {
	return fmt.Errorf("%s is compared against %s, which a file cannot spell %v: no file under those axes holds that value in %s, "+
		"so no %s in one could be told apart by it. That is a property of the layout and the axes asked for, and not a fault in any file's data",
		field+" of "+record, literal, err, field, record)
}

// reexpressText is a literal compared against a text item — every byte of it
// a character under the charset from — as the same characters under the
// charset to.
//
// Byte by byte, which is how a file crosses a charset: a transfer rewrites
// each byte through the two code pages and keeps each character, including the
// padding the producer applied, which arrives as the new charset's own space.
// The width therefore does not change, and nothing about COBOL's comparison
// rules is applied here — they were applied when the literal was resolved
// (docs/ir/SPEC.md, "Each axis carries a literal the way a file crosses it").
//
// A charset that is the same value on both sides moves nothing and is answered
// without a translation, so a literal is never refused over an axis that did
// not change. Where the charset does change, the one failure is a character the
// charset to has no byte for, and that is a [literalError] for the refusal to
// name. A literal that comes out as the bytes it went in as — "01" between two
// EBCDIC code pages agreeing on every digit — is carried, not refused.
func reexpressText(lit []byte, from, to codec.Charset) ([]byte, error) {
	if sameCharset(from, to) {
		return lit, nil
	}

	out := make([]byte, len(lit))

	for i, b := range lit {
		r := from.ToUnicode(b)

		spelled, ok := to.FromUnicode(r)
		if !ok {
			return nil, literalError{
				axis:   "the charset " + to.Name(),
				reason: fmt.Sprintf("since it holds %q and %s has no byte for that character", r, to.Name()),
			}
		}

		out[i] = spelled
	}

	return out, nil
}

// reexpressZoned is a literal compared against a zoned decimal item, resolved
// under from, as a file under to spells it.
//
// signAt is the byte of the literal that carries an overpunched sign — the
// first under SIGN LEADING, the last under SIGN TRAILING — and -1 where the
// item carries none: an unsigned item, and one whose sign is SEPARATE, which is
// a character like any other.
//
// Two axes govern a zoned item and they do not compete for a byte
// (docs/ir/SPEC.md, "Each axis carries a literal the way a file crosses it").
// The sign-carrying byte is the sign convention's, whose table spells the whole
// byte; every other byte is a digit, or the character a file leaves in a blank
// numeric field, and is the charset's. So the charset moves every byte but that
// one, character by character as [reexpressText] moves text, and the sign
// convention moves that one by its column.
//
// Each axis moves only where it changed. A literal survives a charset change
// with its sign byte untouched and a sign change with its digits untouched, and
// neither is refused over an axis that did not move.
func reexpressZoned(lit []byte, from, to codec.Encoding, signAt int) ([]byte, error) {
	out := make([]byte, len(lit))
	copy(out, lit)

	if !sameCharset(from.Charset, to.Charset) {
		for i := range lit {
			if i == signAt {
				continue
			}

			spelled, err := reexpressText(lit[i:i+1], from.Charset, to.Charset)
			if err != nil {
				return nil, err
			}

			out[i] = spelled[0]
		}
	}

	if signAt < 0 || from.Sign == to.Sign {
		return out, nil
	}

	b := lit[signAt]

	digit, column, ok := signColumnsOf(from).find(b)
	if !ok {
		return nil, literalError{
			axis: "the sign convention " + to.Sign.String(),
			reason: fmt.Sprintf("since its sign byte, 0x%02X, is in none of the %s convention's columns: it is no digit carrying a sign that a writer under %s emits, so there is nothing to carry into another",
				b, from.Sign, from.Sign),
		}
	}

	spelled, ok := signColumnsOf(to).at(digit, column)
	if !ok {
		return nil, literalError{
			axis:   "the sign convention " + to.Sign.String(),
			reason: fmt.Sprintf("since its sign byte is digit %d in the %s column, and that convention spells no byte for digit %d in that column under the charset %s", digit, column, digit, to.Charset.Name()),
		}
	}

	out[signAt] = spelled

	return out, nil
}

// signColumn is which of a sign convention's three columns a sign-carrying
// byte is in: the byte a writer puts on a positive signed item, the one it puts
// on a negative one, or the plain digit a writer puts on an unsigned item and a
// reader of a signed one takes as non-negative.
type signColumn int

const (
	positiveColumn signColumn = iota
	negativeColumn
	unsignedColumn
)

// String names a column for a refusal.
func (c signColumn) String() string {
	switch c {
	case positiveColumn:
		return "positive"
	case negativeColumn:
		return "negative"
	default:
		return "unsigned"
	}
}

// signColumns is the three columns of one encoding's sign convention, as the
// bytes codec reads and writes under it: signColumns[column][digit], and -1
// where the column spells no byte for that digit.
//
// # Why the column and not the value
//
// A signed zoned item reads both F5 and C5 as +5 under the EBCDIC convention,
// and a copybook-aware transfer to ASCII writes 35 for the one and 45 for the
// other: two bytes, because they were two bytes before. Re-expressing through
// the value would ask for 45 for both, and a `one of` holding the two would
// collapse into one literal. The column keeps what the file keeps, and it does
// it from the conventions' own tables rather than from a transfer, so it lands
// the same way on a file no transfer produced (docs/ir/SPEC.md, "Each axis
// carries a literal the way a file crosses it").
//
// # Why they are asked of codec rather than written down
//
// The tables are codec/SPEC.md's, and codec does not export them. They are
// asked of it instead, through the accessors every generated package already
// calls: the positive and negative columns are the sign byte codec writes for
// +1d and -1d — two digits, so that the negative zero the trailing byte of -10
// carries is reachable, which no one-digit value is — and the unsigned column
// is the charset's own digit wherever codec reads that digit, in a signed
// item's sign position, as non-negative. That last is the one column codec
// never writes into a signed item, and it is the column the EBCDIC F zone and
// the translated-EBCDIC 3 zone sit in. Where a convention reads the digit as
// positive — zone 3 under ascii-zone-3-7 and realia — the two columns spell one
// byte, and [signColumns.find] reads it as positive, which is what a writer
// under that convention means by it on a signed item.
type signColumns [3][10]int

// signColumnsOf is the columns of enc's sign convention under enc's charset.
//
// Nothing here can fail for an encoding a reader or a writer was built with,
// because building one validated it; an entry codec will not produce is -1
// rather than an error, and it is a refusal only if a literal needs it.
func signColumnsOf(enc codec.Encoding) signColumns {
	var cols signColumns

	for c := range cols {
		for d := range cols[c] {
			cols[c][d] = -1
		}
	}

	w, err := codec.NewBytesWriter(nil, enc)
	if err != nil {
		return cols
	}

	for d := range 10 {
		for c, sign := range [2]int32{1, -1} {
			w.Reset(nil)

			if err := w.WriteZonedInt32(sign*int32(10+d), 2, codec.SignTrailing); err != nil {
				continue
			}

			cols[c][d] = int(w.Bytes()[1])
		}
	}

	one, ok := enc.Charset.FromUnicode('1')
	if !ok {
		return cols
	}

	for d := range 10 {
		digit, ok := enc.Charset.FromUnicode(rune('0' + d))
		if !ok {
			continue
		}

		r, err := codec.NewBytesReader([]byte{one, digit}, enc)
		if err != nil {
			continue
		}

		if v, err := r.ReadZonedInt32(2, codec.SignTrailing); err == nil && v == int32(10+d) {
			cols[unsignedColumn][d] = int(digit)
		}
	}

	return cols
}

// find is the digit and the column the byte b spells in, searched positive
// first, then negative, then unsigned — so that a byte two columns share is
// read as the column a writer emits.
func (cols signColumns) find(b byte) (byte, signColumn, bool) {
	for c := range cols {
		for d, spelled := range cols[c] {
			if spelled == int(b) {
				return byte(d), signColumn(c), true
			}
		}
	}

	return 0, 0, false
}

// at is the byte that spells digit d in column c.
func (cols signColumns) at(d byte, c signColumn) (byte, bool) {
	spelled := cols[c][d]

	return byte(spelled), spelled >= 0
}

// reexpressBinary is a literal compared against a binary item — COMP, COMP-4,
// BINARY or COMP-5 — resolved under the byte order from, as a file under the
// byte order to spells it.
//
// By value, because a file under another byte order was written from values by
// a program encoding them its own way rather than converted from this one. The
// width is fixed and the value is the same integer, so the answer is the same
// bytes reversed — which is exact for every bit pattern, including one the
// item's PICTURE does not admit, and is why this is the one axis a literal can
// always cross and the one helper here that returns no error.
//
// The two orders are compared by what they do rather than by value; see
// [sameByteOrder].
func reexpressBinary(lit []byte, from, to binary.ByteOrder) []byte {
	if sameByteOrder(from, to) {
		return lit
	}

	out := slices.Clone(lit)
	slices.Reverse(out)

	return out
}

// literalsApart reports whether two literals still disagree somewhere over the
// bytes both of their predicates read, oneAt and otherAt being where in the
// record or the occurrence each literal starts.
//
// `resolve` proved the pair apart under the descriptor's axes, and
// re-expression carries that proof across two axes and not the other two
// (docs/ir/SPEC.md, "What cannot be re-expressed is refused before any record
// is read"). A code page is a bijection over its bytes and so is reversing
// them, but a sign convention may spell two columns with one byte, as
// ascii-zone-3-7 does positive and unsigned, and HFP spells one value more than
// one way. So the pairs whose proof could have been lost are held to it again,
// and this is the test: agreeing over every shared byte is two predicates one
// record satisfies at once.
func literalsApart(one []byte, oneAt int, other []byte, otherAt int) bool {
	start, end := max(oneAt, otherAt), min(oneAt+len(one), otherAt+len(other))

	for at := start; at < end; at++ {
		if one[at-oneAt] != other[at-otherAt] {
			return true
		}
	}

	return start >= end
}

// literalsNotApart is the refusal of a reader or a writer under whose axes two
// predicates `resolve` proved apart can both match one record.
//
// It names both literals, both fields and both records, and the axes that
// moved, and says that no file under those axes tells the two apart — which is
// a statement about the descriptor and the axes, raised before any record is
// read, and not about any file's data.
func literalsNotApart(from, to codec.Encoding, oneLiteral, oneField, oneRecord, otherLiteral, otherField, otherRecord string) error {
	return fmt.Errorf("%s of %s is compared against %s and %s of %s against %s, and under %s the two are the same bytes over every byte both read: "+
		"no file under those axes tells a %s from a %s there, so a record of one could be read as the other. "+
		"That is a property of the layout and the axes asked for, and not a fault in any file's data",
		oneField, oneRecord, oneLiteral, otherField, otherRecord, otherLiteral, movedAxes(from, to), oneRecord, otherRecord)
}

// movedAxes names the axes on which to differs from from, with the values to
// gives them.
func movedAxes(from, to codec.Encoding) string {
	var axes []string

	if !sameCharset(from.Charset, to.Charset) {
		axes = append(axes, "the charset "+to.Charset.Name())
	}

	if from.Sign != to.Sign {
		axes = append(axes, "the sign convention "+to.Sign.String())
	}

	if !sameByteOrder(from.ByteOrder, to.ByteOrder) {
		axes = append(axes, fmt.Sprintf("the byte order %v", to.ByteOrder))
	}

	if from.Float != to.Float {
		axes = append(axes, "the floating-point format "+to.Float.String())
	}

	if len(axes) == 0 {
		return "the axes asked for"
	}

	if len(axes) == 1 {
		return axes[0]
	}

	return strings.Join(axes[:len(axes)-1], ", ") + " and " + axes[len(axes)-1]
}
