// Code generated by cpybkc-gen-go. DO NOT EDIT.

package signs

// TextRecord is the TEXT-RECORD record, as docs/ir/SPEC.md resolved it.
type TextRecord struct {
	// Code is CODE — alphanumeric, DISPLAY, 1 byte.
	Code string

	// TextNote is TEXT-NOTE — alphanumeric, DISPLAY, 4 bytes.
	TextNote string
}

// PositiveRecord is the POSITIVE-RECORD record, as docs/ir/SPEC.md resolved it.
type PositiveRecord struct {
	// Kind is KIND — numeric, DISPLAY, 1 digit, signed, 1 byte.
	Kind int32

	// PositiveNote is POSITIVE-NOTE — alphanumeric, DISPLAY, 4 bytes.
	PositiveNote string
}

// NegativeRecord is the NEGATIVE-RECORD record, as docs/ir/SPEC.md resolved it.
type NegativeRecord struct {
	// Kind is KIND — numeric, DISPLAY, 1 digit, signed, 1 byte.
	Kind int32

	// NegativeNote is NEGATIVE-NOTE — alphanumeric, DISPLAY, 4 bytes.
	NegativeNote string
}

// CountRecord is the COUNT-RECORD record, as docs/ir/SPEC.md resolved it.
type CountRecord struct {
	// Count is COUNT — numeric, BINARY, 4 digits, signed, 2 bytes.
	Count int16

	// CountNote is COUNT-NOTE — alphanumeric, DISPLAY, 4 bytes.
	CountNote string
}
