// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The file tier of this package's generated tests: one case per path through the
// automaton this layout describes, and between them every transition predicate it
// carries and every literal of a set-membership one.
//
// Each case carries a whole file as a literal — the framing as well as the records
// — reads it with the generated Reader, checks that the record types came back in
// the order the automaton admits them, writes them back with the generated Writer
// and checks that the bytes are the bytes it started from. The file is synthesized
// from the layout rather than read from a dataset, so it is what to hold against
// the file on your desk: the comment column names each run, the offset inside its
// record, and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports claim.
package claim_test

import (
	"bytes"
	"errors"
	"github.com/Zaba505/cpybkc/example/claim/claim"
	"io"
	"testing"
)

// TestTwoClaimRecords is a file of two CLAIM-RECORD records: the bytes below,
// the records they read back as, and the same bytes written back.
func TestTwoClaimRecords(t *testing.T) {
	t.Parallel()

	in := []byte{
		0x00, 0x3e, 0x00, 0x00, // record 1: the record descriptor word — 62 bytes, itself included
		0xc1, 0xc1, // record 1: CLM-TYPE @0 X(2)
		0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, // record 1: CLM-NUMBER @2 X(12)
		0xc3, 0xc3, 0xc3, 0xc3, //
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // record 1: CLM-MEMBER @14 X(10)
		0xd6, 0xd6, //
		0xf1,                         // record 1: CLM-LINE-COUNT @24 9(1)
		0xd7,                         // record 1: CLM-LINE(1).CLN-KIND @25 X(1)
		0x00, 0x00, 0x00, 0x02, 0x7d, // record 1: CLM-LINE(1).CLN-CHARGE @26 S9(7)V9(2) PACKED-DECIMAL
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, // record 1: CLM-LINE(1).CLN-PROFESSIONAL.CPR-PROVIDER @31 X(10)
		0xc6, 0xc6, //
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, // record 1: CLM-LINE(1).CLN-PROFESSIONAL.CPR-PROCEDURE @41 X(5)
		0xe4, 0xe4, // record 1: CLM-LINE(1).CLN-PROFESSIONAL.CPR-MODIFIER @46 X(2)
		0xf0, 0xf4, 0xf9, // record 1: CLM-LINE(1).CLN-PROFESSIONAL.CPR-UNITS @48 9(3)
		0x00, 0x00, 0x00, 0x00, 0x05, 0x2d, // record 1: CLM-TOTAL-CHARGE @51 S9(9)V9(2) PACKED-DECIMAL
		0xc6,                   // record 1: CLM-STATUS @57 X(1)
		0x00, 0x3e, 0x00, 0x00, // record 2: the record descriptor word — 62 bytes, itself included
		0xc1, 0xc1, // record 2: CLM-TYPE @0 X(2)
		0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, // record 2: CLM-NUMBER @2 X(12)
		0xc3, 0xc3, 0xc3, 0xc3, //
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // record 2: CLM-MEMBER @14 X(10)
		0xd6, 0xd6, //
		0xf1,                         // record 2: CLM-LINE-COUNT @24 9(1)
		0xd7,                         // record 2: CLM-LINE(1).CLN-KIND @25 X(1)
		0x00, 0x00, 0x00, 0x02, 0x7d, // record 2: CLM-LINE(1).CLN-CHARGE @26 S9(7)V9(2) PACKED-DECIMAL
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, // record 2: CLM-LINE(1).CLN-PROFESSIONAL.CPR-PROVIDER @31 X(10)
		0xc6, 0xc6, //
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, // record 2: CLM-LINE(1).CLN-PROFESSIONAL.CPR-PROCEDURE @41 X(5)
		0xe4, 0xe4, // record 2: CLM-LINE(1).CLN-PROFESSIONAL.CPR-MODIFIER @46 X(2)
		0xf0, 0xf4, 0xf9, // record 2: CLM-LINE(1).CLN-PROFESSIONAL.CPR-UNITS @48 9(3)
		0x00, 0x00, 0x00, 0x00, 0x05, 0x2d, // record 2: CLM-TOTAL-CHARGE @51 S9(9)V9(2) PACKED-DECIMAL
		0xc6, // record 2: CLM-STATUS @57 X(1)
	}

	r, err := claim.NewReader(bytes.NewReader(in), claim.Encoding())
	if err != nil {
		t.Fatalf("NewReader: %v", err)
	}

	var records []claim.Record

	for {
		rec, err := r.Next()
		if errors.Is(err, io.EOF) {
			break
		}

		if err != nil {
			t.Fatalf("Next: %v", err)
		}

		records = append(records, rec)
	}

	if len(records) != 2 {
		t.Fatalf("the file holds 2 records and the reader produced %d", len(records))
	}

	if _, ok := records[0].(*claim.ClaimRecord); !ok {
		t.Fatalf("record 1 is CLAIM-RECORD and came back as a %T, want a *claim.ClaimRecord", records[0])
	}

	if _, ok := records[1].(*claim.ClaimRecord); !ok {
		t.Fatalf("record 2 is CLAIM-RECORD and came back as a %T, want a *claim.ClaimRecord", records[1])
	}

	var out bytes.Buffer

	w, err := claim.NewWriter(&out, claim.Encoding())
	if err != nil {
		t.Fatalf("NewWriter: %v", err)
	}

	for _, rec := range records {
		if err := w.Write(rec); err != nil {
			t.Fatalf("Write: %v", err)
		}
	}

	if err := w.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the file does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
