// Code generated by cpybkc-gen-go. DO NOT EDIT.

// The record tier of this package's generated tests: one case per record the
// layout describes, one per arm of an alternation inside one, and one more per
// record carrying a table that may be absent, holding that record at its
// shortest.
//
// Each case carries the bytes it reads as a literal, decodes them, checks every
// field against the value the literal was laid out with, and writes the record
// back out byte for byte. The bytes are synthesized from the layout rather than
// read from a file, so they are what to hold against the file on your desk: the
// comment column names the item, the offset summed from the widths ahead of it,
// and the picture.
//
// Nothing here is yours to edit — this directory is regenerated whole. Put your
// own tests in a package of your own that imports claim.
package claim_test

import (
	"bytes"
	"github.com/Zaba505/cobol-go/codec"
	"github.com/Zaba505/cpybkc/example/claim/claim"
	"testing"
)

// TestClaimRecordReadsBackTheBytesItWasReadFrom is CLAIM-RECORD: the bytes
// below, every field they decode into, and the same bytes written back.
func TestClaimRecordReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, // CLM-TYPE @0 X(2)
		0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, // CLM-NUMBER @2 X(12)
		0xc3, 0xc3, 0xc3, 0xc3, //
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // CLM-MEMBER @14 X(10)
		0xd6, 0xd6, //
		0xf1,                         // CLM-LINE-COUNT @24 9(1)
		0xd7,                         // CLM-LINE(1).CLN-KIND @25 X(1)
		0x00, 0x00, 0x00, 0x02, 0x7d, // CLM-LINE(1).CLN-CHARGE @26 S9(7)V9(2) PACKED-DECIMAL
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, // CLM-LINE(1).CLN-PROFESSIONAL.CPR-PROVIDER @31 X(10)
		0xc6, 0xc6, //
		0xd7, 0xd7, 0xd7, 0xd7, 0xd7, // CLM-LINE(1).CLN-PROFESSIONAL.CPR-PROCEDURE @41 X(5)
		0xe4, 0xe4, // CLM-LINE(1).CLN-PROFESSIONAL.CPR-MODIFIER @46 X(2)
		0xf0, 0xf4, 0xf9, // CLM-LINE(1).CLN-PROFESSIONAL.CPR-UNITS @48 9(3)
		0x00, 0x00, 0x00, 0x00, 0x05, 0x2d, // CLM-TOTAL-CHARGE @51 S9(9)V9(2) PACKED-DECIMAL
		0xc6, // CLM-STATUS @57 X(1)
	}

	r, err := codec.NewReader(bytes.NewReader(in), claim.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record claim.ClaimRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.ClmType != "AA" {
		t.Errorf("CLM-TYPE: got %q, want %q", record.ClmType, "AA")
	}

	if record.ClmNumber != "CCCCCCCCCCCC" {
		t.Errorf("CLM-NUMBER: got %q, want %q", record.ClmNumber, "CCCCCCCCCCCC")
	}

	if record.ClmMember != "OOOOOOOOOO" {
		t.Errorf("CLM-MEMBER: got %q, want %q", record.ClmMember, "OOOOOOOOOO")
	}

	if record.ClmLineCount != 1 {
		t.Errorf("CLM-LINE-COUNT: got %d, want %d", record.ClmLineCount, 1)
	}

	if len(record.ClmLine) != 1 {
		t.Fatalf("CLM-LINE: got %d occurrences, want %d", len(record.ClmLine), 1)
	}

	if record.ClmLine[0].ClnKind != "P" {
		t.Errorf("CLM-LINE(1).CLN-KIND: got %q, want %q", record.ClmLine[0].ClnKind, "P")
	}

	if record.ClmLine[0].ClnCharge != -27 {
		t.Errorf("CLM-LINE(1).CLN-CHARGE: got %d, want %d", record.ClmLine[0].ClnCharge, -27)
	}

	if record.ClmLine[0].ClnProfessional == nil {
		t.Fatalf("CLM-LINE(1).CLN-PROFESSIONAL: the record holds no arm, and its bytes select this one")
	}

	if record.ClmLine[0].ClnPharmacy != nil {
		t.Errorf("CLM-LINE(1).CLN-PHARMACY: the record holds this arm, and its bytes select another")
	}

	if record.ClmLine[0].ClnFacility != nil {
		t.Errorf("CLM-LINE(1).CLN-FACILITY: the record holds this arm, and its bytes select another")
	}

	if record.ClmLine[0].ClnProfessional.CprProvider != "FFFFFFFFFF" {
		t.Errorf("CLM-LINE(1).CLN-PROFESSIONAL.CPR-PROVIDER: got %q, want %q", record.ClmLine[0].ClnProfessional.CprProvider, "FFFFFFFFFF")
	}

	if record.ClmLine[0].ClnProfessional.CprProcedure != "PPPPP" {
		t.Errorf("CLM-LINE(1).CLN-PROFESSIONAL.CPR-PROCEDURE: got %q, want %q", record.ClmLine[0].ClnProfessional.CprProcedure, "PPPPP")
	}

	if record.ClmLine[0].ClnProfessional.CprModifier != "UU" {
		t.Errorf("CLM-LINE(1).CLN-PROFESSIONAL.CPR-MODIFIER: got %q, want %q", record.ClmLine[0].ClnProfessional.CprModifier, "UU")
	}

	if record.ClmLine[0].ClnProfessional.CprUnits != 49 {
		t.Errorf("CLM-LINE(1).CLN-PROFESSIONAL.CPR-UNITS: got %d, want %d", record.ClmLine[0].ClnProfessional.CprUnits, 49)
	}

	if record.ClmTotalCharge != -52 {
		t.Errorf("CLM-TOTAL-CHARGE: got %d, want %d", record.ClmTotalCharge, -52)
	}

	if record.ClmStatus != "F" {
		t.Errorf("CLM-STATUS: got %q, want %q", record.ClmStatus, "F")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, claim.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestClaimRecordHoldingClnPharmacyReadsBackTheBytesItWasReadFrom is
// CLAIM-RECORD: the bytes below, every field they decode into, and the same
// bytes written back.
//
// The alternation this case is for holds CLN-PHARMACY.
func TestClaimRecordHoldingClnPharmacyReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, // CLM-TYPE @0 X(2)
		0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, // CLM-NUMBER @2 X(12)
		0xc3, 0xc3, 0xc3, 0xc3, //
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // CLM-MEMBER @14 X(10)
		0xd6, 0xd6, //
		0xf1,                         // CLM-LINE-COUNT @24 9(1)
		0xc4,                         // CLM-LINE(1).CLN-KIND @25 X(1)
		0x00, 0x00, 0x00, 0x02, 0x7d, // CLM-LINE(1).CLN-CHARGE @26 S9(7)V9(2) PACKED-DECIMAL
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, // CLM-LINE(1).CLN-PHARMACY.CPH-NDC @31 X(11)
		0xc6, 0xc6, 0xc6, //
		0xf0, 0xf4, 0xf3, // CLM-LINE(1).CLN-PHARMACY.CPH-DAYS-SUPPLY @42 9(3)
		0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, // CLM-LINE(1).CLN-PHARMACY.(slack) @45 6 bytes no item covers
		0x00, 0x00, 0x00, 0x00, 0x05, 0x2d, // CLM-TOTAL-CHARGE @51 S9(9)V9(2) PACKED-DECIMAL
		0xc6, // CLM-STATUS @57 X(1)
	}

	r, err := codec.NewReader(bytes.NewReader(in), claim.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record claim.ClaimRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.ClmType != "AA" {
		t.Errorf("CLM-TYPE: got %q, want %q", record.ClmType, "AA")
	}

	if record.ClmNumber != "CCCCCCCCCCCC" {
		t.Errorf("CLM-NUMBER: got %q, want %q", record.ClmNumber, "CCCCCCCCCCCC")
	}

	if record.ClmMember != "OOOOOOOOOO" {
		t.Errorf("CLM-MEMBER: got %q, want %q", record.ClmMember, "OOOOOOOOOO")
	}

	if record.ClmLineCount != 1 {
		t.Errorf("CLM-LINE-COUNT: got %d, want %d", record.ClmLineCount, 1)
	}

	if len(record.ClmLine) != 1 {
		t.Fatalf("CLM-LINE: got %d occurrences, want %d", len(record.ClmLine), 1)
	}

	if record.ClmLine[0].ClnKind != "D" {
		t.Errorf("CLM-LINE(1).CLN-KIND: got %q, want %q", record.ClmLine[0].ClnKind, "D")
	}

	if record.ClmLine[0].ClnCharge != -27 {
		t.Errorf("CLM-LINE(1).CLN-CHARGE: got %d, want %d", record.ClmLine[0].ClnCharge, -27)
	}

	if record.ClmLine[0].ClnProfessional != nil {
		t.Errorf("CLM-LINE(1).CLN-PROFESSIONAL: the record holds this arm, and its bytes select another")
	}

	if record.ClmLine[0].ClnPharmacy == nil {
		t.Fatalf("CLM-LINE(1).CLN-PHARMACY: the record holds no arm, and its bytes select this one")
	}

	if record.ClmLine[0].ClnFacility != nil {
		t.Errorf("CLM-LINE(1).CLN-FACILITY: the record holds this arm, and its bytes select another")
	}

	if record.ClmLine[0].ClnPharmacy.CphNdc != "FFFFFFFFFFF" {
		t.Errorf("CLM-LINE(1).CLN-PHARMACY.CPH-NDC: got %q, want %q", record.ClmLine[0].ClnPharmacy.CphNdc, "FFFFFFFFFFF")
	}

	if record.ClmLine[0].ClnPharmacy.CphDaysSupply != 43 {
		t.Errorf("CLM-LINE(1).CLN-PHARMACY.CPH-DAYS-SUPPLY: got %d, want %d", record.ClmLine[0].ClnPharmacy.CphDaysSupply, 43)
	}

	if record.ClmTotalCharge != -52 {
		t.Errorf("CLM-TOTAL-CHARGE: got %d, want %d", record.ClmTotalCharge, -52)
	}

	if record.ClmStatus != "F" {
		t.Errorf("CLM-STATUS: got %q, want %q", record.ClmStatus, "F")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, claim.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}

// TestClaimRecordHoldingClnFacilityReadsBackTheBytesItWasReadFrom is
// CLAIM-RECORD: the bytes below, every field they decode into, and the same
// bytes written back.
//
// The alternation this case is for holds CLN-FACILITY.
func TestClaimRecordHoldingClnFacilityReadsBackTheBytesItWasReadFrom(t *testing.T) {
	t.Parallel()

	in := []byte{
		0xc1, 0xc1, // CLM-TYPE @0 X(2)
		0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, // CLM-NUMBER @2 X(12)
		0xc3, 0xc3, 0xc3, 0xc3, //
		0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, 0xd6, // CLM-MEMBER @14 X(10)
		0xd6, 0xd6, //
		0xf1,                         // CLM-LINE-COUNT @24 9(1)
		0xc6,                         // CLM-LINE(1).CLN-KIND @25 X(1)
		0x00, 0x00, 0x00, 0x02, 0x7d, // CLM-LINE(1).CLN-CHARGE @26 S9(7)V9(2) PACKED-DECIMAL
		0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, // CLM-LINE(1).CLN-FACILITY.CFA-FACILITY @31 X(10)
		0xc6, 0xc6, //
		0xd7, 0xd7, 0xd7, 0xd7, // CLM-LINE(1).CLN-FACILITY.CFA-REVENUE @41 X(4)
		0xe3, 0xe3, 0xe3, // CLM-LINE(1).CLN-FACILITY.CFA-BILL-TYPE @45 X(3)
		0xf0, 0xf4, 0xf9, // CLM-LINE(1).CLN-FACILITY.CFA-COVERED-DAYS @48 9(3)
		0x00, 0x00, 0x00, 0x00, 0x05, 0x2d, // CLM-TOTAL-CHARGE @51 S9(9)V9(2) PACKED-DECIMAL
		0xc6, // CLM-STATUS @57 X(1)
	}

	r, err := codec.NewReader(bytes.NewReader(in), claim.Encoding())
	if err != nil {
		t.Fatalf("codec.NewReader: %v", err)
	}

	var record claim.ClaimRecord

	if err := record.UnmarshalCOBOL(r); err != nil {
		t.Fatalf("UnmarshalCOBOL: %v", err)
	}

	if record.ClmType != "AA" {
		t.Errorf("CLM-TYPE: got %q, want %q", record.ClmType, "AA")
	}

	if record.ClmNumber != "CCCCCCCCCCCC" {
		t.Errorf("CLM-NUMBER: got %q, want %q", record.ClmNumber, "CCCCCCCCCCCC")
	}

	if record.ClmMember != "OOOOOOOOOO" {
		t.Errorf("CLM-MEMBER: got %q, want %q", record.ClmMember, "OOOOOOOOOO")
	}

	if record.ClmLineCount != 1 {
		t.Errorf("CLM-LINE-COUNT: got %d, want %d", record.ClmLineCount, 1)
	}

	if len(record.ClmLine) != 1 {
		t.Fatalf("CLM-LINE: got %d occurrences, want %d", len(record.ClmLine), 1)
	}

	if record.ClmLine[0].ClnKind != "F" {
		t.Errorf("CLM-LINE(1).CLN-KIND: got %q, want %q", record.ClmLine[0].ClnKind, "F")
	}

	if record.ClmLine[0].ClnCharge != -27 {
		t.Errorf("CLM-LINE(1).CLN-CHARGE: got %d, want %d", record.ClmLine[0].ClnCharge, -27)
	}

	if record.ClmLine[0].ClnProfessional != nil {
		t.Errorf("CLM-LINE(1).CLN-PROFESSIONAL: the record holds this arm, and its bytes select another")
	}

	if record.ClmLine[0].ClnPharmacy != nil {
		t.Errorf("CLM-LINE(1).CLN-PHARMACY: the record holds this arm, and its bytes select another")
	}

	if record.ClmLine[0].ClnFacility == nil {
		t.Fatalf("CLM-LINE(1).CLN-FACILITY: the record holds no arm, and its bytes select this one")
	}

	if record.ClmLine[0].ClnFacility.CfaFacility != "FFFFFFFFFF" {
		t.Errorf("CLM-LINE(1).CLN-FACILITY.CFA-FACILITY: got %q, want %q", record.ClmLine[0].ClnFacility.CfaFacility, "FFFFFFFFFF")
	}

	if record.ClmLine[0].ClnFacility.CfaRevenue != "PPPP" {
		t.Errorf("CLM-LINE(1).CLN-FACILITY.CFA-REVENUE: got %q, want %q", record.ClmLine[0].ClnFacility.CfaRevenue, "PPPP")
	}

	if record.ClmLine[0].ClnFacility.CfaBillType != "TTT" {
		t.Errorf("CLM-LINE(1).CLN-FACILITY.CFA-BILL-TYPE: got %q, want %q", record.ClmLine[0].ClnFacility.CfaBillType, "TTT")
	}

	if record.ClmLine[0].ClnFacility.CfaCoveredDays != 49 {
		t.Errorf("CLM-LINE(1).CLN-FACILITY.CFA-COVERED-DAYS: got %d, want %d", record.ClmLine[0].ClnFacility.CfaCoveredDays, 49)
	}

	if record.ClmTotalCharge != -52 {
		t.Errorf("CLM-TOTAL-CHARGE: got %d, want %d", record.ClmTotalCharge, -52)
	}

	if record.ClmStatus != "F" {
		t.Errorf("CLM-STATUS: got %q, want %q", record.ClmStatus, "F")
	}

	var out bytes.Buffer

	w, err := codec.NewWriter(&out, claim.Encoding())
	if err != nil {
		t.Fatalf("codec.NewWriter: %v", err)
	}

	if err := record.MarshalCOBOL(w); err != nil {
		t.Fatalf("MarshalCOBOL: %v", err)
	}

	if !bytes.Equal(out.Bytes(), in) {
		t.Errorf("the record does not write back the bytes it was read from\n got: % x\nwant: % x", out.Bytes(), in)
	}
}
